// MCP emitter: `sdk/mcp/src/tools.generated.ts`.
//
// The fifth thing rendered from the one IR, and the odd one out: the four language SDKs emit a
// client, this emits a TOOL TABLE — one entry per `/api/v1` operation, each carrying the JSON
// Schema an MCP host shows a model and a thunk that calls the TypeScript SDK. The facade is thin
// on purpose: it decides nothing about retries, auth, error classes, pagination or encoding,
// because `@cat-factory/sdk` already does, and a second implementation of those rules is a second
// place for them to be subtly wrong.
//
// Generating the table (rather than hand-writing 36 tools) buys the same property the SDKs get:
// an endpoint added to the contracts cannot ship as a hole. It also buys one the SDKs do not
// need — the input schema a model reads is derived from the SAME spec the server validates
// against, so a tool cannot describe a request shape the deployment would reject.
//
// Two rules are enforced here rather than left to review:
//
//   1. **A STREAMING operation must be classified.** A tool call has no streaming channel, so an
//      SSE endpoint cannot be a tool. Emitting one anyway would produce a tool that hangs or
//      returns a reader nobody can read, so generation FAILS on an unclassified stream: name it
//      in `MCP_OMITTED_OPERATIONS` with the reason a caller should read.
//   2. **A parameter name may not be claimed twice.** Path and query parameters are lifted to the
//      top level of the input schema (a model should not have to nest an id under `path`), so a
//      collision between them would silently drop one. It fails generation instead.

import {
  GROUP_DOCS,
  GROUPS,
  MCP_OMITTED_OPERATIONS,
  MCP_TOOL_HINTS,
  groupOperations,
} from './surface.mjs'

const BANNER = `// GENERATED by \`pnpm gen:sdk\` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the \`/api/v1\` contracts; \`pnpm check:sdk\` fails CI on drift.
`

/**
 * A single-quoted TS string literal (the repo's style; oxfmt does not touch generated files).
 *
 * Newlines are escaped rather than left raw, unlike the sibling emitters': a tool description is
 * the spec's whole prose paragraph, which the SDKs render into a doc comment and this has to put
 * inside a string.
 */
function lit(value) {
  return `'${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')}'`
}

/** camelCase → snake_case, for the tool name a model reads. */
function snake(text) {
  return String(text)
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

/**
 * The tool name a host lists and a model calls: `<group>_<method>`, e.g. `tasks_create`,
 * `debug_list_llm_calls`.
 *
 * Derived from the SDK surface table rather than from the `operationId`, so the two published
 * surfaces answer to one chosen vocabulary: `client.tasks.create()` and the `tasks_create` tool
 * are visibly the same call, and renaming one renames the other in the same reviewed diff.
 */
function toolName(operation) {
  return `${operation.group}_${snake(operation.method)}`
}

/** Look up a named IR type. */
function findType(ir, name) {
  const type = ir.types.find((candidate) => candidate.name === name)
  if (!type) throw new Error(`MCP: the IR has no type named '${name}'`)
  return type
}

/**
 * Which side of the wire a schema describes.
 *
 * The two are NOT symmetric, and the asymmetry is the whole reason this is a parameter rather than
 * one renderer used twice. An INPUT schema is advisory: a host may show it to a model, the model
 * composes a request, and the deployment is the authority on whether that request is acceptable,
 * so the schema may state everything the spec knows, and a wrong guess costs one 422 that names the
 * field. An OUTPUT schema is ENFORCED, by the caller's own MCP client, against an answer the
 * deployment has already committed to. `/api/v1` is additive forever, so anything an output schema
 * asserts is something a NEWER deployment's honest answer can be rejected for by an OLDER copy of
 * this package: a new enum member, a new union variant, a field that gained a constraint. Every
 * such assertion is therefore dropped on the way out, and what remains is the SHAPE.
 */
const INPUT = 'input'
const OUTPUT = 'output'

/**
 * A JSON Schema (draft 2020-12) for an IR type reference, INLINED.
 *
 * Inlined rather than emitted as `$defs` + `$ref` because the consumer is a model reading a tool's
 * parameters through whatever an MCP host renders, and `$ref` resolution is the part of JSON
 * Schema host support varies most on. Request bodies on this surface are small, so the cost is a
 * few extra lines rather than a combinatorial blow-up. A CYCLE would break that bet, so it throws
 * rather than truncating: a silently shortened schema is a tool that misdescribes its own input.
 */
function jsonSchema(ref, ir, ctx) {
  const schema = (() => {
    switch (ref.kind) {
      case 'string': {
        // An OPEN vocabulary (a closed set plus a documented escape hatch, e.g. a deployment's own
        // `ns:kind` task type) must NOT become an `enum`: that would make the tool refuse a value
        // the server accepts. The known members are named in the description instead, which is
        // what a model actually reads.
        if (ref.open && ref.suggestedValues?.length) {
          return {
            type: 'string',
            description: `Usually one of: ${ref.suggestedValues.join(', ')}. Other values are accepted where the deployment defines them.`,
          }
        }
        return { type: 'string' }
      }
      case 'number':
        return { type: 'number' }
      case 'integer':
        return { type: 'integer' }
      case 'boolean':
        return { type: 'boolean' }
      case 'const':
        // On the way out a literal is a value the deployment chose, not one the caller must match,
        // and pinning it would reject the day a variant is renamed. The type is what survives.
        return ctx.mode === OUTPUT ? { type: typeof ref.value } : { const: ref.value }
      case 'array':
        return { type: 'array', items: jsonSchema(ref.items, ir, ctx) }
      case 'map':
        return { type: 'object', additionalProperties: jsonSchema(ref.values, ir, ctx) }
      case 'ref': {
        if (ctx.stack.includes(ref.name)) {
          throw new Error(
            `MCP: type '${ref.name}' is recursive (${[...ctx.stack, ref.name].join(' -> ')}). The tool ` +
              'schemas are inlined, so this needs a $defs strategy rather than a deeper inline.',
          )
        }
        return namedSchema(findType(ir, ref.name), ir, {
          ...ctx,
          stack: [...ctx.stack, ref.name],
        })
      }
      case 'unknown':
      default:
        // Deliberately no `type`: "any JSON value" is the honest description, and asserting a type
        // here would have a model refuse to send the one the server wants.
        return {}
    }
  })()
  if (!ref.nullable) return schema
  // `null` is a VALUE the server accepts here, not an absent field — the two are different facts
  // on this surface (absent means "leave it alone"), so the schema has to admit both without
  // collapsing them.
  return { anyOf: [schema, { type: 'null' }] }
}

/** A JSON Schema for a NAMED IR type (object / enum / union). */
function namedSchema(type, ir, ctx) {
  const output = ctx.mode === OUTPUT
  if (type.kind === 'enum') {
    // Same reasoning as the OPEN vocabulary above, arrived at from the other direction: every
    // response enum is open OVER TIME, because a member added to `/api/v1` is an additive change
    // that older copies of this package must keep working through.
    return output
      ? {
          type: 'string',
          description: `One of: ${type.values.join(', ')}. A newer deployment may report a member not in this list.`,
        }
      : { type: 'string', enum: type.values }
  }
  if (type.kind === 'union') {
    const described = type.discriminator
      ? `Discriminated by \`${type.discriminator.property}\` (${type.discriminator.values.join(' | ')}).`
      : undefined
    if (output) {
      // A closed `anyOf` is the one assertion a new variant breaks outright, and this surface adds
      // decision kinds. The discriminator and its known values are stated as prose instead, which
      // is what a model reads anyway and what no future variant can invalidate.
      //
      // Not even `type` survives. Every union reaching a response today has object variants only,
      // so `type: 'object'` would be honest about the spec as it stands and would be the same class
      // of assertion as the `anyOf` it replaced: a future union with a string or array variant (the
      // IR resolves each `oneOf` branch generically, so nothing stops one) would have its honest
      // answer rejected by an older copy of this package. The whole point of this mode is that a
      // schema on the way out asserts only what additivity cannot turn against it.
      const schema = {}
      if (described) {
        schema.description = `${described} A newer deployment may report a variant not in this list.`
      }
      return schema
    }
    const schema = { anyOf: type.variants.map((variant) => jsonSchema(variant, ir, ctx)) }
    if (described) schema.description = described
    return schema
  }
  const properties = {}
  const required = []
  for (const field of type.fields) {
    const rendered = jsonSchema(field.type, ir, ctx)
    // Field docs and constraints are folded on the way IN only. On the way out a `maxLength` is a
    // rejection waiting for the first value that outgrew it, and the prose would triple the tool
    // list every host sends a model for a paragraph the API guide already carries.
    properties[field.wireName] = output ? rendered : withFieldNotes(rendered, field)
    if (field.required) required.push(field.wireName)
  }
  const schema = { type: 'object', properties }
  // `required` is stated on requests only: on a response it turns "an older deployment does not
  // send this field yet" into a client-side protocol error, where the honest answer is an absent
  // field the caller can see is absent.
  if (!output && required.length > 0) schema.required = required
  return schema
}

/** Fold a field's doc + constraints onto its schema, so the tool carries what the spec knows. */
function withFieldNotes(schema, field) {
  const out = { ...schema }
  const notes = [field.doc, schema.description].filter(Boolean)
  if (field.nullable && field.required) {
    notes.push('Always present in a response; `null` when the server has no value for it.')
  }
  if (notes.length > 0) out.description = notes.join(' ')
  const { minimum, maximum, minLength, maxLength } = field.constraints ?? {}
  if (minLength !== undefined) out.minLength = minLength
  if (maxLength !== undefined) out.maxLength = maxLength
  if (minimum !== undefined) out.minimum = minimum
  if (maximum !== undefined) out.maximum = maximum
  return out
}

/**
 * The tool's input schema: path and query parameters at the top level, the request body under
 * `body`.
 *
 * The mixed shape is chosen rather than either pure alternative. Fully nesting (`{ path, query,
 * body }`) would mirror the SDK call exactly but makes a model wrap every id in an object for no
 * reason it can see. Fully flattening would read best of all, right up until a body field and a
 * query parameter share a name and one silently wins — and the surface has both `status` filters
 * and `status` fields. Ids and filters are unambiguous at the top level; the body keeps its own
 * namespace, which is also what makes its schema a verbatim copy of the spec's.
 */
function inputSchema(operation, ir) {
  const properties = {}
  const required = []
  for (const param of operation.pathParams) {
    properties[param.wireName] = {
      type: 'string',
      description: param.doc || `Path parameter \`${param.wireName}\`.`,
    }
    required.push(param.wireName)
  }
  for (const param of operation.queryParams) {
    if (properties[param.wireName]) {
      throw new Error(
        `MCP: operation '${operation.id}' has a query parameter '${param.wireName}' that collides ` +
          'with a path parameter of the same name. One of them would be silently dropped.',
      )
    }
    properties[param.wireName] = withFieldNotes(
      jsonSchema(param.type, ir, { mode: INPUT, stack: [] }),
      param,
    )
    if (param.required) required.push(param.wireName)
  }
  if (operation.body) {
    if (properties.body) {
      throw new Error(`MCP: operation '${operation.id}' has a parameter named 'body'.`)
    }
    properties.body = {
      ...jsonSchema(operation.body, ir, { mode: INPUT, stack: [] }),
      description: 'The request body.',
    }
    // A body is required whenever the operation declares one: the spec's request bodies on this
    // surface are all required, and `{}` is a legitimate body (every field optional) rather than
    // an absent one, so leaving it out would send no body at all.
    required.push('body')
  }
  const schema = { type: 'object', properties, additionalProperties: false }
  if (required.length > 0) schema.required = required
  return schema
}

/**
 * The tool's OUTPUT schema, or null when the operation has no JSON object to describe.
 *
 * Two operations have nothing here for good reasons: a `204` answers with no body at all, and a
 * non-object JSON result could not be an `outputSchema` even if one existed, because the protocol's
 * `structuredContent` is an object. Everything else on this surface answers with an envelope.
 *
 * Declaring one is a COMMITMENT, not a hint: a caller's MCP client refuses a successful result that
 * carries no `structuredContent` for a tool that declares a schema, and validates the content it
 * does get. That is why the schema is rendered in {@link OUTPUT} mode, and why the facade's result
 * renderer refuses an over-cap result outright instead of truncating it: a truncated object cannot
 * satisfy a schema it has just been cut in half.
 */
function outputSchema(operation, ir) {
  if (!operation.result) return null
  const schema = jsonSchema(operation.result, ir, { mode: OUTPUT, stack: [] })
  return schema.type === 'object' && schema.properties ? schema : null
}

/**
 * The SDK call this tool forwards to, as a TS expression over `client` and `args`.
 *
 * The body arrives as `unknown` (the host sends whatever the model composed, and the JSON Schema
 * is what constrains it), so reaching the SDK's typed parameter needs an assertion. It is spelled
 * as a lookup INTO the SDK's own signature rather than as `never`: `never` satisfies any
 * parameter type at all, so it would keep compiling if the SDK's body parameter became something
 * this facade no longer supplies, whereas this says exactly what is being claimed and is derived
 * from the one declaration rather than restating it.
 */
function invocation(operation) {
  const bodyType = `Parameters<CatFactoryClient[${lit(operation.group)}][${lit(operation.method)}]>[${operation.pathParams.length}]`
  const args = [
    ...operation.pathParams.map((param) => `str(args, ${lit(param.wireName)})`),
    operation.body ? `args.body as ${bodyType}` : null,
    operation.queryParams.length > 0
      ? `pick(args, QUERY_${snake(toolName(operation)).toUpperCase()})`
      : null,
  ].filter(Boolean)
  return `client.${operation.group}.${operation.method}(${args.join(', ')})`
}

/** The tool's description: the spec's own prose, plus what it maps to. */
function description(operation) {
  const lines = [operation.summary, operation.description]
    .filter(Boolean)
    .map((line) => String(line).trim())
  lines.push(`Calls \`${operation.httpMethod} ${operation.path}\` (operation \`${operation.id}\`).`)
  // Deduplicate: many operations have a summary that is the first sentence of the description.
  return [...new Set(lines)].join('\n\n')
}

function emitTool(operation, ir) {
  const queryConst =
    operation.queryParams.length > 0
      ? `const QUERY_${snake(toolName(operation)).toUpperCase()} = [${operation.queryParams
          .map((param) => lit(param.wireName))
          .join(', ')}] as const\n`
      : ''
  const output = outputSchema(operation, ir)
  const hints = MCP_TOOL_HINTS[operation.id]
  const tool =
    `  {\n` +
    `    name: ${lit(toolName(operation))},\n` +
    `    title: ${lit(operation.summary)},\n` +
    `    group: ${lit(operation.group)},\n` +
    `    operationId: ${lit(operation.id)},\n` +
    // A GET changes nothing on the deployment, which is the one annotation a host uses to decide
    // whether a call needs a human's confirmation. The two hints `readOnlyHint` cannot express
    // come from MCP_TOOL_HINTS, for the operations where the consequence is real money.
    `    readOnly: ${operation.httpMethod === 'GET'},\n` +
    (hints ? `    hints: ${JSON.stringify(hints)},\n` : '') +
    `    description: ${lit(description(operation))},\n` +
    `    inputSchema: ${JSON.stringify(inputSchema(operation, ir))},\n` +
    (output ? `    outputSchema: ${JSON.stringify(output)},\n` : '') +
    `    invoke: (client, args) => ${invocation(operation)},\n` +
    `  },\n`
  return { queryConst, tool }
}

/** Fail on a streaming operation nobody has classified (rule 1 in the header). */
function assertStreamsClassified(placed) {
  for (const operation of placed) {
    if (operation.stream && !MCP_OMITTED_OPERATIONS[operation.id]) {
      throw new Error(
        `MCP: operation '${operation.id}' streams (${operation.httpMethod} ${operation.path}), and a ` +
          'tool call has no streaming channel. Name it in MCP_OMITTED_OPERATIONS ' +
          '(scripts/sdk/surface.mjs) with the reason, or give the facade a way to serve it.',
      )
    }
  }
  const ids = new Set(placed.map((operation) => operation.id))
  for (const id of Object.keys(MCP_OMITTED_OPERATIONS)) {
    if (!ids.has(id)) {
      throw new Error(`MCP: MCP_OMITTED_OPERATIONS names '${id}', which the spec no longer has.`)
    }
  }
}

/** Fail on a hint entry the spec cannot honour (stale operation, an omitted one, or a read). */
function assertHintsAddressable(placed) {
  const byId = new Map(placed.map((operation) => [operation.id, operation]))
  for (const id of Object.keys(MCP_TOOL_HINTS)) {
    const operation = byId.get(id)
    if (!operation) {
      throw new Error(`MCP: MCP_TOOL_HINTS names '${id}', which the spec no longer has.`)
    }
    if (MCP_OMITTED_OPERATIONS[id]) {
      throw new Error(
        `MCP: MCP_TOOL_HINTS names '${id}', which MCP_OMITTED_OPERATIONS withholds. A hint on a ` +
          'tool that is never emitted is dead configuration; drop one of the two entries.',
      )
    }
    if (operation.httpMethod === 'GET') {
      throw new Error(
        `MCP: MCP_TOOL_HINTS names '${id}', a GET. A read changes nothing, so neither ` +
          '`destructiveHint` nor `idempotentHint` says anything about it. Drop the entry.',
      )
    }
  }
}

function emitTools(ir, placed) {
  assertStreamsClassified(placed)
  assertHintsAddressable(placed)
  const exposed = GROUPS.flatMap((group) => groupOperations(placed, group)).filter(
    (operation) => !MCP_OMITTED_OPERATIONS[operation.id],
  )
  const emitted = exposed.map((operation) => emitTool(operation, ir))
  const omitted = placed
    .filter((operation) => MCP_OMITTED_OPERATIONS[operation.id])
    .map(
      (operation) =>
        `  {\n` +
        `    operationId: ${lit(operation.id)},\n` +
        `    route: ${lit(`${operation.httpMethod} ${operation.path}`)},\n` +
        `    sdkCall: ${lit(`client.${operation.group}.${operation.method}()`)},\n` +
        `    reason: ${lit(MCP_OMITTED_OPERATIONS[operation.id])},\n` +
        `  },\n`,
    )

  return `${BANNER}
// The tool table: one entry per \`/api/v1\` operation the facade exposes, surface version ${ir.info.version}.
//
// Each entry is the JSON Schema a model reads plus a thunk onto \`@cat-factory/sdk\`. Nothing here
// decides retry, auth, error mapping or encoding — the SDK does, and the server module beside this
// one turns a result or an error into MCP content. That split is why a contract change regenerates
// this file and touches no behaviour.

import type { CatFactoryClient } from '@cat-factory/sdk'

/** One exposed operation, as an MCP tool. */
export interface CatFactoryTool {
  /** The name a host lists and a model calls, \`<group>_<method>\`. */
  name: string
  /** One-line label from the spec's \`summary\`. */
  title: string
  /** The SDK resource group it belongs to, so a deployment can expose a subset. */
  group: string
  /** The spec's \`operationId\`, for correlating a tool call with a deployment's logs. */
  operationId: string
  /** Whether the call changes nothing (a GET). Hosts use it to decide what needs confirming. */
  readOnly: boolean
  /**
   * The annotations the HTTP method cannot supply, present only where the consequence is real
   * money or a merged pull request. Absent means the protocol's own cautious defaults apply
   * (\`destructiveHint\` true, \`idempotentHint\` false), which is never worse than the truth.
   */
  hints?: { destructive: boolean; idempotent: boolean }
  description: string
  inputSchema: {
    type: 'object'
    properties: Record<string, unknown>
    required?: readonly string[]
    additionalProperties: false
  }
  /**
   * The shape of a successful result, absent when the operation answers with no body.
   *
   * Rendered permissively ON PURPOSE: no \`required\`, no \`enum\`, no closed \`anyOf\`, no length or
   * range bounds, and for a union not even \`type\`. A caller's MCP client VALIDATES a result against
   * this, and \`/api/v1\` is additive forever, so every one of those would be a way for an older copy
   * of this package to reject a newer deployment's honest answer. What is left is the field names and
   * their types, plus the known members of a vocabulary named in prose.
   */
  outputSchema?: {
    type: 'object'
    properties: Record<string, unknown>
  }
  /** Forward the validated arguments to the SDK. */
  invoke: (client: CatFactoryClient, args: Record<string, unknown>) => Promise<unknown>
}

/**
 * An operation the facade deliberately does NOT expose, and why.
 *
 * Reported rather than merely absent: a caller comparing the tool list against the published API
 * would otherwise have to guess whether a missing operation is an omission, an oversight, or a
 * version skew. The server exposes this list through its instructions for the same reason.
 */
export interface CatFactoryOmittedOperation {
  operationId: string
  /** The route it would have called. */
  route: string
  /** The equivalent call on the TypeScript SDK, which CAN serve it. */
  sdkCall: string
  reason: string
}

/** Read a required string argument, failing with the parameter's own name. */
function str(args: Record<string, unknown>, name: string): string {
  const value = args[name]
  if (typeof value !== 'string' || value.length === 0) {
    throw new TypeError(\`\${name} is required and must be a non-empty string\`)
  }
  return value
}

/**
 * The subset of \`args\` that belongs in the query string.
 *
 * Picked by NAME rather than by taking everything left over: the input schema lifts path and query
 * parameters to the same level, so "whatever is not a path parameter" would forward a model's
 * typo as a query parameter the deployment then ignores, and the caller would see a filter that
 * silently did nothing.
 */
function pick(
  args: Record<string, unknown>,
  names: readonly string[],
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const name of names) {
    if (args[name] !== undefined) out[name] = args[name]
  }
  return out
}

${emitted
  .map((entry) => entry.queryConst)
  .filter(Boolean)
  .join('')}
/** Every \`/api/v1\` operation this facade exposes as a tool, in resource-group order. */
export const CAT_FACTORY_TOOLS: readonly CatFactoryTool[] = [
${emitted.map((entry) => entry.tool).join('')}]

/** The operations this facade does not expose, each with its reason. */
export const CAT_FACTORY_OMITTED_OPERATIONS: readonly CatFactoryOmittedOperation[] = [
${omitted.join('')}]

/** One line per resource group, for the server's instructions. */
export const CAT_FACTORY_TOOL_GROUPS: Readonly<Record<string, string>> = {
${GROUPS.map((group) => `  ${lit(group)}: ${lit(GROUP_DOCS[group])},`).join('\n')}
}
`
}

/** Every generated file for the MCP facade, keyed by path within `sdk/mcp/`. */
export function emit(ir, placed) {
  return {
    'src/tools.generated.ts': emitTools(ir, placed),
  }
}
