// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

// The resource services: one type per resource group, each a thin shell over the hand-written
// transport in client.go. Nothing here decides retry, auth, error mapping or stream framing.

package catfactory

import (
	"context"
	"fmt"
	"iter"
)

// DebugGetAgentContextQuery holds the query parameters for DebugService.GetAgentContext.
type DebugGetAgentContextQuery struct {
	// BodyChars zero value means "not sent".
	BodyChars *int
	// BodyOffset zero value means "not sent".
	BodyOffset *int
}

func (q *DebugGetAgentContextQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.BodyChars != nil {
		out["bodyChars"] = fmt.Sprintf("%v", *q.BodyChars)
	}
	if q.BodyOffset != nil {
		out["bodyOffset"] = fmt.Sprintf("%v", *q.BodyOffset)
	}
	return out
}

// DebugGetLlmCallQuery holds the query parameters for DebugService.GetLlmCall.
type DebugGetLlmCallQuery struct {
	// BodyChars zero value means "not sent".
	BodyChars *int
	// BodyOffset zero value means "not sent".
	BodyOffset *int
	// View zero value means "not sent".
	View *GetDebugLlmCallView
}

func (q *DebugGetLlmCallQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.BodyChars != nil {
		out["bodyChars"] = fmt.Sprintf("%v", *q.BodyChars)
	}
	if q.BodyOffset != nil {
		out["bodyOffset"] = fmt.Sprintf("%v", *q.BodyOffset)
	}
	if q.View != nil {
		out["view"] = fmt.Sprintf("%v", *q.View)
	}
	return out
}

// DebugListAgentContextQuery holds the query parameters for DebugService.ListAgentContext.
type DebugListAgentContextQuery struct {
	// StepIndex zero value means "not sent".
	StepIndex *int
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
}

func (q *DebugListAgentContextQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.StepIndex != nil {
		out["stepIndex"] = fmt.Sprintf("%v", *q.StepIndex)
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	return out
}

// DebugListLlmCallsQuery holds the query parameters for DebugService.ListLlmCalls.
type DebugListLlmCallsQuery struct {
	// AgentKind zero value means "not sent".
	AgentKind *string
	// Phase zero value means "not sent".
	Phase *string
	// Outcome zero value means "not sent".
	Outcome *LlmCallOutcome
	// Contains zero value means "not sent".
	Contains *string
	// Order zero value means "not sent".
	Order *ListDebugLlmCallsOrder
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
	// BodyChars zero value means "not sent".
	BodyChars *int
}

func (q *DebugListLlmCallsQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.AgentKind != nil {
		out["agentKind"] = fmt.Sprintf("%v", *q.AgentKind)
	}
	if q.Phase != nil {
		out["phase"] = fmt.Sprintf("%v", *q.Phase)
	}
	if q.Outcome != nil {
		out["outcome"] = fmt.Sprintf("%v", *q.Outcome)
	}
	if q.Contains != nil {
		out["contains"] = fmt.Sprintf("%v", *q.Contains)
	}
	if q.Order != nil {
		out["order"] = fmt.Sprintf("%v", *q.Order)
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	if q.BodyChars != nil {
		out["bodyChars"] = fmt.Sprintf("%v", *q.BodyChars)
	}
	return out
}

// DebugListLogsQuery holds the query parameters for DebugService.ListLogs.
type DebugListLogsQuery struct {
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
}

func (q *DebugListLogsQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	return out
}

// DebugListRunsQuery holds the query parameters for DebugService.ListRuns.
type DebugListRunsQuery struct {
	// Status zero value means "not sent".
	Status *RunStatus
	// Since zero value means "not sent".
	Since *int
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
}

func (q *DebugListRunsQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.Status != nil {
		out["status"] = fmt.Sprintf("%v", *q.Status)
	}
	if q.Since != nil {
		out["since"] = fmt.Sprintf("%v", *q.Since)
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	return out
}

// DebugListSearchQueriesQuery holds the query parameters for DebugService.ListSearchQueries.
type DebugListSearchQueriesQuery struct {
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
}

func (q *DebugListSearchQueriesQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	return out
}

// JobsListQuery holds the query parameters for JobsService.List.
type JobsListQuery struct {
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
	// Status zero value means "not sent".
	Status *PublicJobStatus
	// Since zero value means "not sent".
	Since *int
}

func (q *JobsListQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	if q.Status != nil {
		out["status"] = fmt.Sprintf("%v", *q.Status)
	}
	if q.Since != nil {
		out["since"] = fmt.Sprintf("%v", *q.Since)
	}
	return out
}

// TasksListByServiceQuery holds the query parameters for TasksService.ListByService.
type TasksListByServiceQuery struct {
	// Limit zero value means "not sent".
	Limit *int
	// Cursor zero value means "not sent".
	Cursor *string
	// Status zero value means "not sent".
	Status *TaskStatus
}

func (q *TasksListByServiceQuery) values() map[string]string {
	out := map[string]string{}
	if q == nil {
		return out
	}
	if q.Limit != nil {
		out["limit"] = fmt.Sprintf("%v", *q.Limit)
	}
	if q.Cursor != nil {
		out["cursor"] = fmt.Sprintf("%v", *q.Cursor)
	}
	if q.Status != nil {
		out["status"] = fmt.Sprintf("%v", *q.Status)
	}
	return out
}

// ListDebugAgentContextResponseItem is the element type of ListDebugAgentContextResponse.Snapshots.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListDebugAgentContextResponseItem = DebugAgentContextSummary

// ListDebugLlmCallsResponseItem is the element type of ListDebugLlmCallsResponse.Calls.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListDebugLlmCallsResponseItem = DebugLlmCall

// ListDebugLogsResponseItem is the element type of ListDebugLogsResponse.Entries.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListDebugLogsResponseItem = DebugInfraLogEntry

// ListDebugRunsResponseItem is the element type of ListDebugRunsResponse.Runs.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListDebugRunsResponseItem = DebugRunSummary

// ListDebugSearchQueriesResponseItem is the element type of ListDebugSearchQueriesResponse.Queries.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListDebugSearchQueriesResponseItem = DebugSearchQuery

// ListPublicJobsResponseItem is the element type of ListPublicJobsResponse.Jobs.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type ListPublicJobsResponseItem = PublicJob

// PublicTaskListItem is the element type of PublicTaskList.Tasks.
// An alias rather than a second declaration, so the pager cannot drift from the list it pages
// over.
type PublicTaskListItem = PublicTask

// JobsService headless jobs (a public, inline pipeline run against a brief): start, poll or stream one.
type JobsService struct {
	client *Client
}

// Cancel cancel a job
// Stop a headless job run, freeing its concurrency slot. Idempotent — an already-finished job is
// returned as-is. Use this to abandon a run parked on a decision you do not intend to answer.
// POST /api/v1/jobs/{id}/cancel (operation cancelPublicJob).
func (s *JobsService) Cancel(ctx context.Context, id string) (*PublicJob, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/jobs/%s/cancel", pathEscape(id)),
	}
	var out PublicJob
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create start a headless job
// Start a public, inline pipeline headlessly against a supplied brief. Returns a job id to poll
// or stream. Nothing is pushed to GitHub.
// POST /api/v1/jobs (operation createPublicJob).
func (s *JobsService) Create(ctx context.Context, body CreatePublicJob) (*PublicJobAccepted, error) {
	req := requestSpec{
		Method: "POST",
		Path:   "/api/v1/jobs",
		Body:   body,
	}
	var out PublicJobAccepted
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get get a job
// Poll a headless job started through this surface: its status and, once finished, its result.
// GET /api/v1/jobs/{id} (operation getPublicJob).
func (s *JobsService) Get(ctx context.Context, id string) (*PublicJob, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/jobs/%s", pathEscape(id)),
	}
	var out PublicJob
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List list the workspace's jobs
// List the headless runs THIS surface created, newest first and keyset-paginated. Scoped to
// internal-anchored runs exactly like the single-job read, so an external key can never enumerate
// the workspace’s ordinary board runs.
// GET /api/v1/jobs (operation listPublicJobs).
func (s *JobsService) List(ctx context.Context, query *JobsListQuery) (*ListPublicJobsResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/jobs",
		Query:  query.values(),
	}
	var out ListPublicJobsResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAll iterates every jobs across every page of List.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *JobsService) ListAll(ctx context.Context, query *JobsListQuery) iter.Seq2[ListPublicJobsResponseItem, error] {
	return func(yield func(ListPublicJobsResponseItem, error) bool) {
		var page JobsListQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.List(ctx, &page)
			if err != nil {
				var zero ListPublicJobsResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Jobs {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListPublicJobsResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// Stream stream a job (SSE)
// Server-sent events for a headless job run: `progress` frames until a terminal
// `done`/`error`/`stopped`/`timeout` event. Authenticated by the API key header.
// GET /api/v1/jobs/{id}/events (operation streamPublicJobEvents).
func (s *JobsService) Stream(ctx context.Context, id string) (*EventStream, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/jobs/%s/events", pathEscape(id)),
	}
	return s.client.stream(ctx, req)
}

// ServicesService the workspace's board services — the frames tasks are created under.
type ServicesService struct {
	client *Client
}

// List list the workspace's services
// List the board service frames in the key’s workspace, so a caller can discover the serviceId to
// create/list tasks under.
// GET /api/v1/services (operation listPublicServices).
func (s *ServicesService) List(ctx context.Context) (*PublicServiceList, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/services",
	}
	var out PublicServiceList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// TasksService a board task's whole lifecycle: create, edit, start, stop, retry, watch, delete.
type TasksService struct {
	client *Client
}

// Create create a task under a service
// Create a task inside a service frame the key’s workspace owns. The task starts in the `planned`
// state; start it with the start endpoint.
// POST /api/v1/services/{serviceId}/tasks (operation createPublicTask).
func (s *TasksService) Create(ctx context.Context, serviceID string, body CreatePublicTask) (*PublicTask, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/services/%s/tasks", pathEscape(serviceID)),
		Body:   body,
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete delete a task
// Delete a task and its run history. Destructive, so it sits at the top of the scope ladder:
// requires an `admin`-scoped key.
// DELETE /api/v1/tasks/{taskId} (operation deletePublicTask).
func (s *TasksService) Delete(ctx context.Context, taskID string) error {
	req := requestSpec{
		Method: "DELETE",
		Path:   fmt.Sprintf("/api/v1/tasks/%s", pathEscape(taskID)),
	}
	return s.client.requestNoContent(ctx, req)
}

// Get get a task's status
// Read a task’s current lifecycle status, run progress, run id, and PR URL (once one exists).
// GET /api/v1/tasks/{taskId} (operation getPublicTask).
func (s *TasksService) Get(ctx context.Context, taskID string) (*PublicTask, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/tasks/%s", pathEscape(taskID)),
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRun get a task's run (rich projection)
// Read a task’s run in detail: per-step status/progress/subtasks, the failure kind and message,
// and the PR (url + branch).
// GET /api/v1/tasks/{taskId}/run (operation getPublicRun).
func (s *TasksService) GetRun(ctx context.Context, taskID string) (*PublicRun, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/tasks/%s/run", pathEscape(taskID)),
	}
	var out PublicRun
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListByService list a service's tasks
// List every task under a service (the whole subtree — tasks directly under the frame and under
// its modules).
// GET /api/v1/services/{serviceId}/tasks (operation listPublicServiceTasks).
func (s *TasksService) ListByService(ctx context.Context, serviceID string, query *TasksListByServiceQuery) (*PublicTaskList, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/services/%s/tasks", pathEscape(serviceID)),
		Query:  query.values(),
	}
	var out PublicTaskList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListByServiceAll iterates every tasks across every page of ListByService.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *TasksService) ListByServiceAll(ctx context.Context, serviceID string, query *TasksListByServiceQuery) iter.Seq2[PublicTaskListItem, error] {
	return func(yield func(PublicTaskListItem, error) bool) {
		var page TasksListByServiceQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListByService(ctx, serviceID, &page)
			if err != nil {
				var zero PublicTaskListItem
				yield(zero, err)
				return
			}
			for _, item := range result.Tasks {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero PublicTaskListItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// Retry retry a task's failed run
// Retry a task’s failed run. A task on an individual-usage model cannot be retried through the
// API (no headless personal-credential unlock).
// POST /api/v1/tasks/{taskId}/retry (operation retryPublicTask).
func (s *TasksService) Retry(ctx context.Context, taskID string) (*PublicTask, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/tasks/%s/retry", pathEscape(taskID)),
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Start start (run) a task
// Start a task’s pipeline. Uses the request’s pipelineId, else the task’s pinned pipeline. A
// pipeline that can park on a human decision requires a `decide`-scope key. A task on an
// individual-usage model cannot be started through the API (no headless personal-credential
// unlock).
// POST /api/v1/tasks/{taskId}/start (operation startPublicTask).
func (s *TasksService) Start(ctx context.Context, taskID string, body StartPublicTask) (*PublicTask, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/tasks/%s/start", pathEscape(taskID)),
		Body:   body,
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Stop stop a task's run
// Stop a task’s in-flight run. Records a `cancelled` terminal state, leaving the run retryable.
// POST /api/v1/tasks/{taskId}/stop (operation stopPublicTask).
func (s *TasksService) Stop(ctx context.Context, taskID string) (*PublicTask, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/tasks/%s/stop", pathEscape(taskID)),
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Stream stream a task run (SSE)
// Server-sent events for a board task run: `progress` frames (the rich run projection) until a
// terminal `done`/`error` event, or a `timeout` when the connection cap is reached. Authenticated
// by the API key header.
// GET /api/v1/tasks/{taskId}/events (operation streamPublicTaskRun).
func (s *TasksService) Stream(ctx context.Context, taskID string) (*EventStream, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/tasks/%s/events", pathEscape(taskID)),
	}
	return s.client.stream(ctx, req)
}

// Update edit a task's title/description
// Edit a task’s human-authored fields (title/description) before it runs. Both fields are
// optional.
// PATCH /api/v1/tasks/{taskId} (operation updatePublicTask).
func (s *TasksService) Update(ctx context.Context, taskID string, body UpdatePublicTask) (*PublicTask, error) {
	req := requestSpec{
		Method: "PATCH",
		Path:   fmt.Sprintf("/api/v1/tasks/%s", pathEscape(taskID)),
		Body:   body,
	}
	var out PublicTask
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// PipelinesService the pipelines a task can be started with, and whether each is headless-startable.
type PipelinesService struct {
	client *Client
}

// List list the workspace's pipelines
// List the pipelines in the key’s workspace — id/name/steps plus whether each is public and safe
// to run headlessly — so a caller can pick a pipelineId to start a task with.
// GET /api/v1/pipelines (operation listPublicPipelines).
func (s *PipelinesService) List(ctx context.Context) (*PublicPipelineList, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/pipelines",
	}
	var out PublicPipelineList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// NotificationsService the workspace's human-actionable inbox: list, act on, or dismiss a run tail.
type NotificationsService struct {
	client *Client
}

// Act act on a notification
// Run a notification’s typed side-effect and resolve it: merge the PR (merge_review /
// pipeline_complete) or retry the run (ci_failed / test_failed). Performs a real GitHub merge, so
// it requires an admin-scoped key. Only these automated-action types are actionable through the
// API — a notification that parks a run on an interactive human decision cannot be acted on
// headlessly (dismiss it instead). A card that would retry a run on an individual-usage model
// likewise cannot be acted on through the API.
// POST /api/v1/notifications/{id}/act (operation actPublicNotification).
func (s *NotificationsService) Act(ctx context.Context, id string) (*Notification, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/notifications/%s/act", pathEscape(id)),
	}
	var out Notification
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Dismiss dismiss a notification
// Dismiss a notification without acting on it.
// POST /api/v1/notifications/{id}/dismiss (operation dismissPublicNotification).
func (s *NotificationsService) Dismiss(ctx context.Context, id string) (*Notification, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/notifications/%s/dismiss", pathEscape(id)),
	}
	var out Notification
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List list the workspace's open notifications
// List the open, human-actionable notifications in the key’s workspace (merge reviews,
// pipeline-complete confirmations, CI/test failures, and informational cards).
// GET /api/v1/notifications (operation listPublicNotifications).
func (s *NotificationsService) List(ctx context.Context) (*PublicNotificationList, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/notifications",
	}
	var out PublicNotificationList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// UsageService the billing period's metered budget position and the per-model breakdown behind it.
type UsageService struct {
	client *Client
}

// Get read the workspace's usage for the current period
// Read this billing period’s METERED spend against the workspace budget (including whether it is
// exceeded, which pauses runs) plus the per-(billing, vendor, provider, model) token breakdown
// behind it. Costs on `subscription` rows are illustrative — a flat-rate plan bills nothing per
// token — so branch on `billing` before summing. Workspace-scoped: the account- and user-tier
// budgets are not reachable through this surface.
// GET /api/v1/usage (operation getPublicUsage).
func (s *UsageService) Get(ctx context.Context) (*PublicUsage, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/usage",
	}
	var out PublicUsage
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DecisionsService a parked run's human decisions — requirement findings, forks and judge verdicts.
type DecisionsService struct {
	client *Client
}

// ChooseFork choose an implementation approach
// Pick one of the proposed implementation forks (by id) or submit your own approach. The Coder
// then runs with the choice folded in as a binding directive. Requires a `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/fork/choose (operation choosePublicRunFork).
func (s *DecisionsService) ChooseFork(ctx context.Context, runID string, body PublicChooseFork) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/fork/choose", pathEscape(runID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Incorporate incorporate the answers
// Fold the recorded answers into one standardized requirements document. Asynchronous — the run
// re-reviews in the background, so the response shows the review `incorporating`. Requires a
// `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/requirements/incorporate (operation
// incorporatePublicRunRequirements).
func (s *DecisionsService) Incorporate(ctx context.Context, runID string, body PublicIncorporate) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/incorporate", pathEscape(runID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List list a run's parked decisions
// Read what a run is currently asking a human: requirement-review findings (with the stable item
// ids a reply addresses) and any implementation-fork choice. `parked` is true while the run is
// blocked awaiting one of them.
// GET /api/v1/runs/{runId}/decisions (operation listPublicRunDecisions).
func (s *DecisionsService) List(ctx context.Context, runID string) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions", pathEscape(runID)),
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Proceed proceed with the current requirements
// Settle the requirements phase and advance the parked run (used when nothing is outstanding).
// Requires a `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/requirements/proceed (operation
// proceedPublicRunRequirements).
func (s *DecisionsService) Proceed(ctx context.Context, runID string) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/proceed", pathEscape(runID)),
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ReplyToFinding answer a review finding
// Record an answer to one reviewer finding. Returns the run's updated decision list. Requires a
// `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}/reply (operation
// replyPublicRunFinding).
func (s *DecisionsService) ReplyToFinding(ctx context.Context, runID string, itemID string, body PublicReplyFinding) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/findings/%s/reply", pathEscape(runID), pathEscape(itemID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ReReview re-review the incorporated document
// Run one more reviewer pass over the incorporated document. On convergence the parked run
// advances. Requires a `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/requirements/re-review (operation
// reReviewPublicRunRequirements).
func (s *DecisionsService) ReReview(ctx context.Context, runID string) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/re-review", pathEscape(runID)),
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveExceeded resolve a review at its iteration cap
// Pick how a review that exhausted its reviewer-pass budget proceeds: one more round, proceed
// with the last incorporated document, or stop and reset the task. Requires a `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/requirements/resolve-exceeded (operation
// resolvePublicRunRequirementsExceeded).
func (s *DecisionsService) ResolveExceeded(ctx context.Context, runID string, body PublicResolveExceeded) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/resolve-exceeded", pathEscape(runID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveJudge resolve a parked judge verdict
// Settle a run parked on a judge verdict: proceed anyway, bounce the producing step for rework,
// or stop the run. Requires a `decide`-scope key.
// POST /api/v1/runs/{runId}/decisions/judge/resolve (operation resolvePublicRunJudge).
func (s *DecisionsService) ResolveJudge(ctx context.Context, runID string, body PublicResolveJudge) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "POST",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/judge/resolve", pathEscape(runID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SetFindingStatus dismiss or reopen a finding
// Dismiss a finding as not applicable, or reopen one dismissed by mistake. Requires a
// `decide`-scope key.
// PATCH /api/v1/runs/{runId}/decisions/requirements/findings/{itemId} (operation
// setPublicRunFindingStatus).
func (s *DecisionsService) SetFindingStatus(ctx context.Context, runID string, itemID string, body PublicSetFindingStatus) (*PublicDecisionList, error) {
	req := requestSpec{
		Method: "PATCH",
		Path:   fmt.Sprintf("/api/v1/runs/%s/decisions/requirements/findings/%s", pathEscape(runID), pathEscape(itemID)),
		Body:   body,
	}
	var out PublicDecisionList
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DebugService a run's recorded telemetry: LLM calls, the context each agent was given, infra logs.
type DebugService struct {
	client *Client
}

// GetAgentContext get one agent-context snapshot
// The complete context one dispatch was PROVIDED: system and user prompts, the folded standards
// fragments, and the injected `.cat-context/*` files an agent reads through tools (which
// therefore appear in no proxy telemetry). Windowed by `bodyOffset`/`bodyChars`.
// GET /api/v1/debug/agent-context/{snapshotId} (operation getDebugAgentContext).
func (s *DebugService) GetAgentContext(ctx context.Context, snapshotID string, query *DebugGetAgentContextQuery) (*DebugAgentContextSnapshot, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/agent-context/%s", pathEscape(snapshotID)),
		Query:  query.values(),
	}
	var out DebugAgentContextSnapshot
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLlmCall get one LLM call
// One recorded model call with its budgeted prompt delta, response and reasoning.
// `bodyOffset`/`bodyChars` window the bodies, so an arbitrarily long transcript is readable in
// bounded pages.
// GET /api/v1/debug/llm-calls/{callId} (operation getDebugLlmCall).
func (s *DebugService) GetLlmCall(ctx context.Context, callID string, query *DebugGetLlmCallQuery) (*DebugLlmCall, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/llm-calls/%s", pathEscape(callID)),
		Query:  query.values(),
	}
	var out DebugLlmCall
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRun get a run's diagnostic map
// One run’s diagnostic overview: its steps, which telemetry sinks this deployment retains (and
// how much each holds), the LLM cost/latency rollups, and the derived signals worth looking at
// first.
// GET /api/v1/debug/runs/{runId} (operation getDebugRun).
func (s *DebugService) GetRun(ctx context.Context, runID string) (*DebugRunOverview, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/runs/%s", pathEscape(runID)),
	}
	var out DebugRunOverview
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAgentContext list a run's agent-context dispatches
// Every dispatch whose provided context was captured, with SIZES only (no bodies) so the list
// stays bounded. Read one in full through the snapshot endpoint.
// GET /api/v1/debug/runs/{runId}/agent-context (operation listDebugAgentContext).
func (s *DebugService) ListAgentContext(ctx context.Context, runID string, query *DebugListAgentContextQuery) (*ListDebugAgentContextResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/runs/%s/agent-context", pathEscape(runID)),
		Query:  query.values(),
	}
	var out ListDebugAgentContextResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAgentContextAll iterates every snapshots across every page of ListAgentContext.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *DebugService) ListAgentContextAll(ctx context.Context, runID string, query *DebugListAgentContextQuery) iter.Seq2[ListDebugAgentContextResponseItem, error] {
	return func(yield func(ListDebugAgentContextResponseItem, error) bool) {
		var page DebugListAgentContextQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListAgentContext(ctx, runID, &page)
			if err != nil {
				var zero ListDebugAgentContextResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Snapshots {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListDebugAgentContextResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// ListLlmCalls list a run's LLM calls
// The model calls a run made, keyset-paginated and filterable by agent kind, phase, outcome or a
// substring of the bodies. Bodies are returned only when `bodyChars` asks for them.
// GET /api/v1/debug/runs/{runId}/llm-calls (operation listDebugLlmCalls).
func (s *DebugService) ListLlmCalls(ctx context.Context, runID string, query *DebugListLlmCallsQuery) (*ListDebugLlmCallsResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/runs/%s/llm-calls", pathEscape(runID)),
		Query:  query.values(),
	}
	var out ListDebugLlmCallsResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLlmCallsAll iterates every calls across every page of ListLlmCalls.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *DebugService) ListLlmCallsAll(ctx context.Context, runID string, query *DebugListLlmCallsQuery) iter.Seq2[ListDebugLlmCallsResponseItem, error] {
	return func(yield func(ListDebugLlmCallsResponseItem, error) bool) {
		var page DebugListLlmCallsQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListLlmCalls(ctx, runID, &page)
			if err != nil {
				var zero ListDebugLlmCallsResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Calls {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListDebugLlmCallsResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// ListLogs list a run's infrastructure log
// The run’s provisioning event log — how its environment, runner pool and containers came up, or
// why they did not.
// GET /api/v1/debug/runs/{runId}/logs (operation listDebugLogs).
func (s *DebugService) ListLogs(ctx context.Context, runID string, query *DebugListLogsQuery) (*ListDebugLogsResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/runs/%s/logs", pathEscape(runID)),
		Query:  query.values(),
	}
	var out ListDebugLogsResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLogsAll iterates every entries across every page of ListLogs.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *DebugService) ListLogsAll(ctx context.Context, runID string, query *DebugListLogsQuery) iter.Seq2[ListDebugLogsResponseItem, error] {
	return func(yield func(ListDebugLogsResponseItem, error) bool) {
		var page DebugListLogsQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListLogs(ctx, runID, &page)
			if err != nil {
				var zero ListDebugLogsResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Entries {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListDebugLogsResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// ListRuns list the workspace's runs
// The triage entry point: the workspace’s runs, newest first and keyset-paginated, with an
// optional status and `since` filter.
// GET /api/v1/debug/runs (operation listDebugRuns).
func (s *DebugService) ListRuns(ctx context.Context, query *DebugListRunsQuery) (*ListDebugRunsResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   "/api/v1/debug/runs",
		Query:  query.values(),
	}
	var out ListDebugRunsResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRunsAll iterates every runs across every page of ListRuns.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *DebugService) ListRunsAll(ctx context.Context, query *DebugListRunsQuery) iter.Seq2[ListDebugRunsResponseItem, error] {
	return func(yield func(ListDebugRunsResponseItem, error) bool) {
		var page DebugListRunsQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListRuns(ctx, &page)
			if err != nil {
				var zero ListDebugRunsResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Runs {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListDebugRunsResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}

// ListSearchQueries list a run's web searches
// The web searches the run’s agents actually performed, keyset-paginated. Retained only when the
// deployment records agent context.
// GET /api/v1/debug/runs/{runId}/search-queries (operation listDebugSearchQueries).
func (s *DebugService) ListSearchQueries(ctx context.Context, runID string, query *DebugListSearchQueriesQuery) (*ListDebugSearchQueriesResponse, error) {
	req := requestSpec{
		Method: "GET",
		Path:   fmt.Sprintf("/api/v1/debug/runs/%s/search-queries", pathEscape(runID)),
		Query:  query.values(),
	}
	var out ListDebugSearchQueriesResponse
	if err := s.client.request(ctx, req, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSearchQueriesAll iterates every queries across every page of ListSearchQueries.
// Follows nextCursor until the server reports no further page. Yields (item, nil) per item and,
// on a failure mid-iteration, one final (zero, err) — so a partial walk is never mistaken for a
// complete one.
func (s *DebugService) ListSearchQueriesAll(ctx context.Context, runID string, query *DebugListSearchQueriesQuery) iter.Seq2[ListDebugSearchQueriesResponseItem, error] {
	return func(yield func(ListDebugSearchQueriesResponseItem, error) bool) {
		var page DebugListSearchQueriesQuery
		if query != nil {
			page = *query
		}
		for {
			result, err := s.ListSearchQueries(ctx, runID, &page)
			if err != nil {
				var zero ListDebugSearchQueriesResponseItem
				yield(zero, err)
				return
			}
			for _, item := range result.Queries {
				if !yield(item, nil) {
					return
				}
			}
			if result.NextCursor == nil || *result.NextCursor == "" {
				return
			}
			if page.Cursor != nil && *page.Cursor == *result.NextCursor {
				var zero ListDebugSearchQueriesResponseItem
				yield(zero, ErrRepeatedCursor)
				return
			}
			page.Cursor = result.NextCursor
		}
	}
}
