// The domain works directly with the wire entity types defined once in
// @cat-factory/contracts. Re-exported here so the rest of the core imports its
// vocabulary from a single place (`../domain/types`) rather than reaching into
// the contracts package everywhere.
export type {
  AgentKind,
  AgentState,
  Block,
  BlockLevel,
  BlockStatus,
  BlockType,
  Decision,
  ExecutionInstance,
  ExecutionStatus,
  Pipeline,
  PipelineStep,
  Position,
  PullRequestRef,
  SpendStatus,
  StepSubtasks,
  TestTarget,
  Workspace,
  WorkspaceSnapshot,
  // Account tenancy shapes.
  Account,
  AccountType,
  AccountRole,
  AccountMember,
  CreateAccountInput,
  AddMemberInput,
  // GitHub integration projections + I/O shapes.
  GitHubBranch,
  GitHubCheckRun,
  GitHubCommit,
  GitHubConnection,
  GitHubInstallationOption,
  GitHubAvailableRepo,
  GitHubIssue,
  GitHubIssueState,
  GitHubPullRequest,
  GitHubPullRequestState,
  GitHubRepo,
  CommitFilesInput,
  LinkReposInput,
  OpenPullRequestInput,
  MergePullRequestInput,
  // Document-source integration projections + planning shapes.
  DocumentSourceKind,
  DocumentSourceDescriptor,
  CredentialField,
  DocumentConnection,
  SourceDocument,
  DocumentBoardPlan,
  PlanFrame,
  PlanModule,
  PlanTask,
  // Task-source integration projections + I/O shapes.
  TaskSourceKind,
  TaskSourceDescriptor,
  TaskConnection,
  TaskComment,
  SourceTask,
  // Ephemeral environment provider shapes.
  EnvironmentSecretRef,
  EnvironmentAuthScheme,
  EnvironmentHttpMethod,
  EnvironmentRequestTemplate,
  EnvironmentStatus,
  EnvironmentAccessScheme,
  EnvironmentAccessMapping,
  EnvironmentResponseMapping,
  EnvironmentManifest,
  EnvironmentAccessHandle,
  EnvironmentHandle,
  EnvironmentConnection,
  // Self-hosted runner-pool ("bring your own infra") shapes.
  RunnerPoolSecretRef,
  RunnerPoolAuthScheme,
  RunnerPoolRequestTemplate,
  RunnerJobState,
  RunnerPoolResponseMapping,
  RunnerPoolManifest,
  RunnerPoolConnection,
  // Repo-bootstrap shapes.
  ReferenceArchitecture,
  CreateReferenceArchitectureInput,
  UpdateReferenceArchitectureInput,
  BootstrapStatus,
  BootstrapFailure,
  BootstrapFailureKind,
  BootstrapJob,
  BootstrapRepoInput,
  // Board-scan (repository decomposition) shapes.
  BlueprintFeature,
  BlueprintModule,
  BlueprintService,
  BlueprintSource,
  RepoBlueprint,
  ScanRepoInput,
  ScanRepoResult,
  BoardScanSpawnResult,
} from '@cat-factory/contracts'
