// The domain works directly with the wire entity types defined once in
// @cat-factory/contracts. Re-exported here so the rest of the core imports its
// vocabulary from a single place (`../domain/types`) rather than reaching into
// the contracts package everywhere.
export type {
  AgentKind,
  AgentState,
  Block,
  BlockLevel,
  BlockStatus,
  BlockType,
  Decision,
  ExecutionInstance,
  ExecutionStatus,
  Pipeline,
  PipelineStep,
  Position,
  PullRequestRef,
  SpendStatus,
  TestTarget,
  Workspace,
  WorkspaceSnapshot,
  // GitHub integration projections + I/O shapes.
  GitHubBranch,
  GitHubCheckRun,
  GitHubCommit,
  GitHubConnection,
  GitHubIssue,
  GitHubIssueState,
  GitHubPullRequest,
  GitHubPullRequestState,
  GitHubRepo,
  CommitFilesInput,
  OpenPullRequestInput,
  MergePullRequestInput,
  // Confluence integration projections + planning shapes.
  ConfluenceConnection,
  ConfluenceDocument,
  ConfluenceBoardPlan,
  PlanFrame,
  PlanModule,
  PlanTask,
  // Ephemeral environment provider shapes.
  EnvironmentSecretRef,
  EnvironmentAuthScheme,
  EnvironmentHttpMethod,
  EnvironmentRequestTemplate,
  EnvironmentStatus,
  EnvironmentAccessScheme,
  EnvironmentAccessMapping,
  EnvironmentResponseMapping,
  EnvironmentManifest,
  EnvironmentAccessHandle,
  EnvironmentHandle,
  EnvironmentConnection,
  // Repo-bootstrap shapes.
  ReferenceArchitecture,
  CreateReferenceArchitectureInput,
  UpdateReferenceArchitectureInput,
  BootstrapStatus,
  BootstrapJob,
  BootstrapRepoInput,
  // Board-scan (repository decomposition) shapes.
  BlueprintFeature,
  BlueprintModule,
  BlueprintService,
  BlueprintSource,
  RepoBlueprint,
  ScanRepoInput,
  ScanRepoResult,
  BoardScanSpawnResult,
} from '@cat-factory/contracts'
