// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1} wire model.
 * @param ingressName May be absent entirely. Length 1..unbounded.
 * @param scheme May be absent entirely.
 * @param source the {@code source} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1(
    /** May be absent entirely. Length 1..unbounded. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("ingressName") @Nullable String ingressName,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("scheme") @Nullable ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant0Scheme scheme,

    @JsonProperty("source") String source
) implements ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrl {

    /** A new builder for {@link ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link
     * ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String ingressName;
        private @Nullable ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant0Scheme scheme;
        private @Nullable String source;

        /** Set {@code ingressName}. */
        public Builder ingressName(@Nullable String ingressName) {
            this.ingressName = ingressName;
            return this;
        }

        /** Set {@code scheme}. */
        public Builder scheme(@Nullable ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant0Scheme scheme) {
            this.scheme = scheme;
            return this;
        }

        /** Set {@code source}. */
        public Builder source(@Nullable String source) {
            this.source = source;
            return this;
        }

        /** Build the {@link ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1}. */
        public ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1 build() {
            return new ConnectPublicEnvironmentRequestConnectionVariant0KubernetesUrlVariant1(ingressName, scheme, source);
        }
    }
}
