// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ConnectPublicEnvironmentRequest} wire model.
 * @param connection the {@code connection} field.
 * @param secrets the {@code secrets} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ConnectPublicEnvironmentRequest(
    @JsonProperty("connection") ConnectPublicEnvironmentRequestConnection connection,

    @JsonProperty("secrets") Map<String, String> secrets
) {

    /** A new builder for {@link ConnectPublicEnvironmentRequest}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ConnectPublicEnvironmentRequest}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable ConnectPublicEnvironmentRequestConnection connection;
        private @Nullable Map<String, String> secrets;

        /** Set {@code connection}. */
        public Builder connection(@Nullable ConnectPublicEnvironmentRequestConnection connection) {
            this.connection = connection;
            return this;
        }

        /** Set {@code secrets}. */
        public Builder secrets(@Nullable Map<String, String> secrets) {
            this.secrets = secrets;
            return this;
        }

        /** Build the {@link ConnectPublicEnvironmentRequest}. */
        public ConnectPublicEnvironmentRequest build() {
            return new ConnectPublicEnvironmentRequest(connection, secrets);
        }
    }
}
