// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ConnectPublicEnvironmentResponse} wire model.
 * @param apiServerUrl the {@code apiServerUrl} field.
 * @param engine the {@code engine} field.
 * @param label the {@code label} field.
 * @param provisionType the {@code provisionType} field.
 * @param secretKeys the {@code secretKeys} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ConnectPublicEnvironmentResponse(
    @JsonProperty("apiServerUrl") String apiServerUrl,

    @JsonProperty("engine") String engine,

    @JsonProperty("label") String label,

    @JsonProperty("provisionType") String provisionType,

    @JsonProperty("secretKeys") List<String> secretKeys
) {

    /** A new builder for {@link ConnectPublicEnvironmentResponse}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ConnectPublicEnvironmentResponse}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String apiServerUrl;
        private @Nullable String engine;
        private @Nullable String label;
        private @Nullable String provisionType;
        private @Nullable List<String> secretKeys;

        /** Set {@code apiServerUrl}. */
        public Builder apiServerUrl(@Nullable String apiServerUrl) {
            this.apiServerUrl = apiServerUrl;
            return this;
        }

        /** Set {@code engine}. */
        public Builder engine(@Nullable String engine) {
            this.engine = engine;
            return this;
        }

        /** Set {@code label}. */
        public Builder label(@Nullable String label) {
            this.label = label;
            return this;
        }

        /** Set {@code provisionType}. */
        public Builder provisionType(@Nullable String provisionType) {
            this.provisionType = provisionType;
            return this;
        }

        /** Set {@code secretKeys}. */
        public Builder secretKeys(@Nullable List<String> secretKeys) {
            this.secretKeys = secretKeys;
            return this;
        }

        /** Build the {@link ConnectPublicEnvironmentResponse}. */
        public ConnectPublicEnvironmentResponse build() {
            return new ConnectPublicEnvironmentResponse(apiServerUrl, engine, label, provisionType, secretKeys);
        }
    }
}
