// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code CreatePublicServiceRequest} wire model.
 * @param description May be absent entirely. Length 0..2000.
 * @param repo May be absent entirely.
 * @param title May be absent entirely. Length 1..200.
 * @param type May be absent entirely.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record CreatePublicServiceRequest(
    /** May be absent entirely. Length 0..2000. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("description") @Nullable String description,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("repo") @Nullable CreatePublicServiceRequestRepo repo,

    /** May be absent entirely. Length 1..200. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("title") @Nullable String title,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("type") @Nullable StartPublicRepoBootstrapRequestType type
) {

    /** A new builder for {@link CreatePublicServiceRequest}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link CreatePublicServiceRequest}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String description;
        private @Nullable CreatePublicServiceRequestRepo repo;
        private @Nullable String title;
        private @Nullable StartPublicRepoBootstrapRequestType type;

        /** Set {@code description}. */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /** Set {@code repo}. */
        public Builder repo(@Nullable CreatePublicServiceRequestRepo repo) {
            this.repo = repo;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Set {@code type}. */
        public Builder type(@Nullable StartPublicRepoBootstrapRequestType type) {
            this.type = type;
            return this;
        }

        /** Build the {@link CreatePublicServiceRequest}. */
        public CreatePublicServiceRequest build() {
            return new CreatePublicServiceRequest(description, repo, title, type);
        }
    }
}
