// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DebugToolCall} wire model.
 * @param args the {@code args} field.
 * @param name the {@code name} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DebugToolCall(
    @JsonProperty("args") DebugText args,

    @JsonProperty("name") String name
) {

    /** A new builder for {@link DebugToolCall}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DebugToolCall}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable DebugText args;
        private @Nullable String name;

        /** Set {@code args}. */
        public Builder args(@Nullable DebugText args) {
            this.args = args;
            return this;
        }

        /** Set {@code name}. */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /** Build the {@link DebugToolCall}. */
        public DebugToolCall build() {
            return new DebugToolCall(args, name);
        }
    }
}
