// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DebugStepToolServers} wire model.
 * @param agentKind the {@code agentKind} field.
 * @param unavailable the {@code unavailable} field.
 * @param wired the {@code wired} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DebugStepToolServers(
    @JsonProperty("agentKind") String agentKind,

    @JsonProperty("unavailable") List<DebugUnavailableToolServer> unavailable,

    @JsonProperty("wired") List<DebugWiredToolServer> wired
) {

    /** A new builder for {@link DebugStepToolServers}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DebugStepToolServers}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String agentKind;
        private @Nullable List<DebugUnavailableToolServer> unavailable;
        private @Nullable List<DebugWiredToolServer> wired;

        /** Set {@code agentKind}. */
        public Builder agentKind(@Nullable String agentKind) {
            this.agentKind = agentKind;
            return this;
        }

        /** Set {@code unavailable}. */
        public Builder unavailable(@Nullable List<DebugUnavailableToolServer> unavailable) {
            this.unavailable = unavailable;
            return this;
        }

        /** Set {@code wired}. */
        public Builder wired(@Nullable List<DebugWiredToolServer> wired) {
            this.wired = wired;
            return this;
        }

        /** Build the {@link DebugStepToolServers}. */
        public DebugStepToolServers build() {
            return new DebugStepToolServers(agentKind, unavailable, wired);
        }
    }
}
