// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DebugAgentContextSnapshot} wire model.
 * @param agentKind the {@code agentKind} field.
 * @param contextFiles the {@code contextFiles} field.
 * @param createdAt the {@code createdAt} field.
 * @param extras the {@code extras} field.
 * @param fragments the {@code fragments} field.
 * @param harness Always present; {@code null} when the server has no value for it.
 * @param model Always present; {@code null} when the server has no value for it.
 * @param runId the {@code runId} field.
 * @param snapshotId the {@code snapshotId} field.
 * @param stepIndex the {@code stepIndex} field.
 * @param systemPrompt the {@code systemPrompt} field.
 * @param userPrompt the {@code userPrompt} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DebugAgentContextSnapshot(
    @JsonProperty("agentKind") String agentKind,

    @JsonProperty("contextFiles") List<DebugContextFile> contextFiles,

    @JsonProperty("createdAt") Double createdAt,

    @JsonProperty("extras") Map<String, Object> extras,

    @JsonProperty("fragments") List<DebugContextFragment> fragments,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("harness") @Nullable String harness,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("model") @Nullable String model,

    @JsonProperty("runId") String runId,

    @JsonProperty("snapshotId") String snapshotId,

    @JsonProperty("stepIndex") Double stepIndex,

    @JsonProperty("systemPrompt") DebugText systemPrompt,

    @JsonProperty("userPrompt") DebugText userPrompt
) {

    /** A new builder for {@link DebugAgentContextSnapshot}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DebugAgentContextSnapshot}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String agentKind;
        private @Nullable List<DebugContextFile> contextFiles;
        private @Nullable Double createdAt;
        private @Nullable Map<String, Object> extras;
        private @Nullable List<DebugContextFragment> fragments;
        private @Nullable String harness;
        private @Nullable String model;
        private @Nullable String runId;
        private @Nullable String snapshotId;
        private @Nullable Double stepIndex;
        private @Nullable DebugText systemPrompt;
        private @Nullable DebugText userPrompt;

        /** Set {@code agentKind}. */
        public Builder agentKind(@Nullable String agentKind) {
            this.agentKind = agentKind;
            return this;
        }

        /** Set {@code contextFiles}. */
        public Builder contextFiles(@Nullable List<DebugContextFile> contextFiles) {
            this.contextFiles = contextFiles;
            return this;
        }

        /** Set {@code createdAt}. */
        public Builder createdAt(@Nullable Double createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /** Set {@code extras}. */
        public Builder extras(@Nullable Map<String, Object> extras) {
            this.extras = extras;
            return this;
        }

        /** Set {@code fragments}. */
        public Builder fragments(@Nullable List<DebugContextFragment> fragments) {
            this.fragments = fragments;
            return this;
        }

        /** Set {@code harness}. */
        public Builder harness(@Nullable String harness) {
            this.harness = harness;
            return this;
        }

        /** Set {@code model}. */
        public Builder model(@Nullable String model) {
            this.model = model;
            return this;
        }

        /** Set {@code runId}. */
        public Builder runId(@Nullable String runId) {
            this.runId = runId;
            return this;
        }

        /** Set {@code snapshotId}. */
        public Builder snapshotId(@Nullable String snapshotId) {
            this.snapshotId = snapshotId;
            return this;
        }

        /** Set {@code stepIndex}. */
        public Builder stepIndex(@Nullable Double stepIndex) {
            this.stepIndex = stepIndex;
            return this;
        }

        /** Set {@code systemPrompt}. */
        public Builder systemPrompt(@Nullable DebugText systemPrompt) {
            this.systemPrompt = systemPrompt;
            return this;
        }

        /** Set {@code userPrompt}. */
        public Builder userPrompt(@Nullable DebugText userPrompt) {
            this.userPrompt = userPrompt;
            return this;
        }

        /** Build the {@link DebugAgentContextSnapshot}. */
        public DebugAgentContextSnapshot build() {
            return new DebugAgentContextSnapshot(agentKind, contextFiles, createdAt, extras, fragments, harness, model, runId, snapshotId, stepIndex, systemPrompt, userPrompt);
        }
    }
}
