// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DebugToolCallTotals} wire model.
 * @param calls the {@code calls} field.
 * @param failureRate Always present; {@code null} when the server has no value for it.
 * @param failures the {@code failures} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DebugToolCallTotals(
    @JsonProperty("calls") Double calls,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("failureRate") @Nullable Double failureRate,

    @JsonProperty("failures") Double failures
) {

    /** A new builder for {@link DebugToolCallTotals}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DebugToolCallTotals}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double calls;
        private @Nullable Double failureRate;
        private @Nullable Double failures;

        /** Set {@code calls}. */
        public Builder calls(@Nullable Double calls) {
            this.calls = calls;
            return this;
        }

        /** Set {@code failureRate}. */
        public Builder failureRate(@Nullable Double failureRate) {
            this.failureRate = failureRate;
            return this;
        }

        /** Set {@code failures}. */
        public Builder failures(@Nullable Double failures) {
            this.failures = failures;
            return this;
        }

        /** Build the {@link DebugToolCallTotals}. */
        public DebugToolCallTotals build() {
            return new DebugToolCallTotals(calls, failureRate, failures);
        }
    }
}
