// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DirectoryRepo} wire model.
 * @param defaultBranch Always present; {@code null} when the server has no value for it.
 * @param monorepo the {@code monorepo} field.
 * @param name the {@code name} field.
 * @param owner the {@code owner} field.
 * @param isPrivate the {@code private} field.
 * @param provider the {@code provider} field.
 * @param repoId the {@code repoId} field.
 * @param workspaceId the {@code workspaceId} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DirectoryRepo(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("defaultBranch") @Nullable String defaultBranch,

    @JsonProperty("monorepo") Boolean monorepo,

    @JsonProperty("name") String name,

    @JsonProperty("owner") String owner,

    @JsonProperty("private") Boolean isPrivate,

    @JsonProperty("provider") PrReportRunProvider provider,

    @JsonProperty("repoId") Double repoId,

    @JsonProperty("workspaceId") String workspaceId
) {

    /** A new builder for {@link DirectoryRepo}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DirectoryRepo}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String defaultBranch;
        private @Nullable Boolean monorepo;
        private @Nullable String name;
        private @Nullable String owner;
        private @Nullable Boolean isPrivate;
        private @Nullable PrReportRunProvider provider;
        private @Nullable Double repoId;
        private @Nullable String workspaceId;

        /** Set {@code defaultBranch}. */
        public Builder defaultBranch(@Nullable String defaultBranch) {
            this.defaultBranch = defaultBranch;
            return this;
        }

        /** Set {@code monorepo}. */
        public Builder monorepo(@Nullable Boolean monorepo) {
            this.monorepo = monorepo;
            return this;
        }

        /** Set {@code name}. */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /** Set {@code owner}. */
        public Builder owner(@Nullable String owner) {
            this.owner = owner;
            return this;
        }

        /** Set {@code private}. */
        public Builder isPrivate(@Nullable Boolean isPrivate) {
            this.isPrivate = isPrivate;
            return this;
        }

        /** Set {@code provider}. */
        public Builder provider(@Nullable PrReportRunProvider provider) {
            this.provider = provider;
            return this;
        }

        /** Set {@code repoId}. */
        public Builder repoId(@Nullable Double repoId) {
            this.repoId = repoId;
            return this;
        }

        /** Set {@code workspaceId}. */
        public Builder workspaceId(@Nullable String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /** Build the {@link DirectoryRepo}. */
        public DirectoryRepo build() {
            return new DirectoryRepo(defaultBranch, monorepo, name, owner, isPrivate, provider, repoId, workspaceId);
        }
    }
}
