// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DirectoryAccountMembershipPage} wire model.
 * @param asOfSeq the {@code asOfSeq} field.
 * @param items the {@code items} field.
 * @param nextCursor Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DirectoryAccountMembershipPage(
    @JsonProperty("asOfSeq") Double asOfSeq,

    @JsonProperty("items") List<DirectoryAccountMembership> items,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("nextCursor") @Nullable String nextCursor
) {

    /** A new builder for {@link DirectoryAccountMembershipPage}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DirectoryAccountMembershipPage}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double asOfSeq;
        private @Nullable List<DirectoryAccountMembership> items;
        private @Nullable String nextCursor;

        /** Set {@code asOfSeq}. */
        public Builder asOfSeq(@Nullable Double asOfSeq) {
            this.asOfSeq = asOfSeq;
            return this;
        }

        /** Set {@code items}. */
        public Builder items(@Nullable List<DirectoryAccountMembership> items) {
            this.items = items;
            return this;
        }

        /** Set {@code nextCursor}. */
        public Builder nextCursor(@Nullable String nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        /** Build the {@link DirectoryAccountMembershipPage}. */
        public DirectoryAccountMembershipPage build() {
            return new DirectoryAccountMembershipPage(asOfSeq, items, nextCursor);
        }
    }
}
