// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DirectoryChangeVariant2} wire model.
 * @param at the {@code at} field.
 * @param entity Always present; {@code null} when the server has no value for it.
 * @param entityId the {@code entityId} field.
 * @param entityType the {@code entityType} field.
 * @param seq the {@code seq} field.
 * @param workspaceId Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DirectoryChangeVariant2(
    @JsonProperty("at") Double at,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("entity") @Nullable DirectoryAccountMembership entity,

    @JsonProperty("entityId") String entityId,

    @JsonProperty("entityType") String entityType,

    @JsonProperty("seq") Double seq,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("workspaceId") @Nullable String workspaceId
) implements DirectoryChange {

    /** A new builder for {@link DirectoryChangeVariant2}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DirectoryChangeVariant2}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double at;
        private @Nullable DirectoryAccountMembership entity;
        private @Nullable String entityId;
        private @Nullable String entityType;
        private @Nullable Double seq;
        private @Nullable String workspaceId;

        /** Set {@code at}. */
        public Builder at(@Nullable Double at) {
            this.at = at;
            return this;
        }

        /** Set {@code entity}. */
        public Builder entity(@Nullable DirectoryAccountMembership entity) {
            this.entity = entity;
            return this;
        }

        /** Set {@code entityId}. */
        public Builder entityId(@Nullable String entityId) {
            this.entityId = entityId;
            return this;
        }

        /** Set {@code entityType}. */
        public Builder entityType(@Nullable String entityType) {
            this.entityType = entityType;
            return this;
        }

        /** Set {@code seq}. */
        public Builder seq(@Nullable Double seq) {
            this.seq = seq;
            return this;
        }

        /** Set {@code workspaceId}. */
        public Builder workspaceId(@Nullable String workspaceId) {
            this.workspaceId = workspaceId;
            return this;
        }

        /** Build the {@link DirectoryChangeVariant2}. */
        public DirectoryChangeVariant2 build() {
            return new DirectoryChangeVariant2(at, entity, entityId, entityType, seq, workspaceId);
        }
    }
}
