// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code DirectoryChangePage} wire model.
 * @param changes the {@code changes} field.
 * @param headSeq the {@code headSeq} field.
 * @param nextAfter the {@code nextAfter} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DirectoryChangePage(
    @JsonProperty("changes") List<DirectoryChange> changes,

    @JsonProperty("headSeq") Double headSeq,

    @JsonProperty("nextAfter") Double nextAfter
) {

    /** A new builder for {@link DirectoryChangePage}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link DirectoryChangePage}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<DirectoryChange> changes;
        private @Nullable Double headSeq;
        private @Nullable Double nextAfter;

        /** Set {@code changes}. */
        public Builder changes(@Nullable List<DirectoryChange> changes) {
            this.changes = changes;
            return this;
        }

        /** Set {@code headSeq}. */
        public Builder headSeq(@Nullable Double headSeq) {
            this.headSeq = headSeq;
            return this;
        }

        /** Set {@code nextAfter}. */
        public Builder nextAfter(@Nullable Double nextAfter) {
            this.nextAfter = nextAfter;
            return this;
        }

        /** Build the {@link DirectoryChangePage}. */
        public DirectoryChangePage build() {
            return new DirectoryChangePage(changes, headSeq, nextAfter);
        }
    }
}
