// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseSourcesVariant1Source} wire model.
 * @param freshness Always present; {@code null} when the server has no value for it.
 * @param movedDuringRun the {@code movedDuringRun} field.
 * @param origin the {@code origin} field.
 * @param title the {@code title} field.
 * @param url Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseSourcesVariant1Source(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("freshness") @Nullable DocumentFreshness freshness,

    @JsonProperty("movedDuringRun") Boolean movedDuringRun,

    @JsonProperty("origin") DocumentOrigin origin,

    @JsonProperty("title") String title,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("url") @Nullable String url
) {

    /** A new builder for {@link GetPublicRunOutcomeResponseSourcesVariant1Source}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseSourcesVariant1Source}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable DocumentFreshness freshness;
        private @Nullable Boolean movedDuringRun;
        private @Nullable DocumentOrigin origin;
        private @Nullable String title;
        private @Nullable String url;

        /** Set {@code freshness}. */
        public Builder freshness(@Nullable DocumentFreshness freshness) {
            this.freshness = freshness;
            return this;
        }

        /** Set {@code movedDuringRun}. */
        public Builder movedDuringRun(@Nullable Boolean movedDuringRun) {
            this.movedDuringRun = movedDuringRun;
            return this;
        }

        /** Set {@code origin}. */
        public Builder origin(@Nullable DocumentOrigin origin) {
            this.origin = origin;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Set {@code url}. */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseSourcesVariant1Source}. */
        public GetPublicRunOutcomeResponseSourcesVariant1Source build() {
            return new GetPublicRunOutcomeResponseSourcesVariant1Source(freshness, movedDuringRun, origin, title, url);
        }
    }
}
