// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseRequirementsVariant1Entry} wire model.
 * @param detail Always present; {@code null} when the server has no value for it.
 * @param id the {@code id} field.
 * @param regression the {@code regression} field.
 * @param state Always present; {@code null} when the server has no value for it.
 * @param title Always present; {@code null} when the server has no value for it.
 * @param verdict the {@code verdict} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseRequirementsVariant1Entry(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("detail") @Nullable String detail,

    @JsonProperty("id") String id,

    @JsonProperty("regression") Boolean regression,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("state") @Nullable PrReportRequirementsEntryState state,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("title") @Nullable String title,

    @JsonProperty("verdict") PrReportRequirementsEntryVerdict verdict
) {

    /** A new builder for {@link GetPublicRunOutcomeResponseRequirementsVariant1Entry}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseRequirementsVariant1Entry}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String detail;
        private @Nullable String id;
        private @Nullable Boolean regression;
        private @Nullable PrReportRequirementsEntryState state;
        private @Nullable String title;
        private @Nullable PrReportRequirementsEntryVerdict verdict;

        /** Set {@code detail}. */
        public Builder detail(@Nullable String detail) {
            this.detail = detail;
            return this;
        }

        /** Set {@code id}. */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /** Set {@code regression}. */
        public Builder regression(@Nullable Boolean regression) {
            this.regression = regression;
            return this;
        }

        /** Set {@code state}. */
        public Builder state(@Nullable PrReportRequirementsEntryState state) {
            this.state = state;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Set {@code verdict}. */
        public Builder verdict(@Nullable PrReportRequirementsEntryVerdict verdict) {
            this.verdict = verdict;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseRequirementsVariant1Entry}. */
        public GetPublicRunOutcomeResponseRequirementsVariant1Entry build() {
            return new GetPublicRunOutcomeResponseRequirementsVariant1Entry(detail, id, regression, state, title, verdict);
        }
    }
}
