// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicTrackerWritebackResponse} wire model.
 * @param updatedAt Always present; {@code null} when the server has no value for it.
 * @param writeback the {@code writeback} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicTrackerWritebackResponse(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("updatedAt") @Nullable Double updatedAt,

    @JsonProperty("writeback") GetPublicTrackerWritebackResponseWriteback writeback
) {

    /** A new builder for {@link GetPublicTrackerWritebackResponse}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicTrackerWritebackResponse}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double updatedAt;
        private @Nullable GetPublicTrackerWritebackResponseWriteback writeback;

        /** Set {@code updatedAt}. */
        public Builder updatedAt(@Nullable Double updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /** Set {@code writeback}. */
        public Builder writeback(@Nullable GetPublicTrackerWritebackResponseWriteback writeback) {
            this.writeback = writeback;
            return this;
        }

        /** Build the {@link GetPublicTrackerWritebackResponse}. */
        public GetPublicTrackerWritebackResponse build() {
            return new GetPublicTrackerWritebackResponse(updatedAt, writeback);
        }
    }
}
