// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseEnvironmentsVariant1Entry} wire model.
 * @param detail Always present; {@code null} when the server has no value for it.
 * @param detailKind Always present; {@code null} when the server has no value for it.
 * @param environmentId Always present; {@code null} when the server has no value for it.
 * @param expiresAt Always present; {@code null} when the server has no value for it.
 * @param frameId Always present; {@code null} when the server has no value for it.
 * @param origin the {@code origin} field.
 * @param retained the {@code retained} field.
 * @param state the {@code state} field.
 * @param url Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseEnvironmentsVariant1Entry(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("detail") @Nullable String detail,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("detailKind") @Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryDetailKind detailKind,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("environmentId") @Nullable String environmentId,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("expiresAt") @Nullable Double expiresAt,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("frameId") @Nullable String frameId,

    @JsonProperty("origin") GetPublicRunOutcomeResponseEnvironmentsVariant1EntryOrigin origin,

    @JsonProperty("retained") Boolean retained,

    @JsonProperty("state") GetPublicRunOutcomeResponseEnvironmentsVariant1EntryState state,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("url") @Nullable String url
) {

    /** A new builder for {@link GetPublicRunOutcomeResponseEnvironmentsVariant1Entry}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseEnvironmentsVariant1Entry}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String detail;
        private @Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryDetailKind detailKind;
        private @Nullable String environmentId;
        private @Nullable Double expiresAt;
        private @Nullable String frameId;
        private @Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryOrigin origin;
        private @Nullable Boolean retained;
        private @Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryState state;
        private @Nullable String url;

        /** Set {@code detail}. */
        public Builder detail(@Nullable String detail) {
            this.detail = detail;
            return this;
        }

        /** Set {@code detailKind}. */
        public Builder detailKind(@Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryDetailKind detailKind) {
            this.detailKind = detailKind;
            return this;
        }

        /** Set {@code environmentId}. */
        public Builder environmentId(@Nullable String environmentId) {
            this.environmentId = environmentId;
            return this;
        }

        /** Set {@code expiresAt}. */
        public Builder expiresAt(@Nullable Double expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /** Set {@code frameId}. */
        public Builder frameId(@Nullable String frameId) {
            this.frameId = frameId;
            return this;
        }

        /** Set {@code origin}. */
        public Builder origin(@Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryOrigin origin) {
            this.origin = origin;
            return this;
        }

        /** Set {@code retained}. */
        public Builder retained(@Nullable Boolean retained) {
            this.retained = retained;
            return this;
        }

        /** Set {@code state}. */
        public Builder state(@Nullable GetPublicRunOutcomeResponseEnvironmentsVariant1EntryState state) {
            this.state = state;
            return this;
        }

        /** Set {@code url}. */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseEnvironmentsVariant1Entry}. */
        public GetPublicRunOutcomeResponseEnvironmentsVariant1Entry build() {
            return new GetPublicRunOutcomeResponseEnvironmentsVariant1Entry(detail, detailKind, environmentId, expiresAt, frameId, origin, retained, state, url);
        }
    }
}
