// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseCheck} wire model.
 * @param kind the {@code kind} field.
 * @param reproduction Always present; {@code null} when the server has no value for it.
 * @param state the {@code state} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseCheck(
    @JsonProperty("kind") GetPublicRunOutcomeResponseCheckKind kind,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("reproduction") @Nullable PrReportReproductionVerdict reproduction,

    @JsonProperty("state") GetPublicRunOutcomeResponseCheckState state
) {

    /** A new builder for {@link GetPublicRunOutcomeResponseCheck}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseCheck}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable GetPublicRunOutcomeResponseCheckKind kind;
        private @Nullable PrReportReproductionVerdict reproduction;
        private @Nullable GetPublicRunOutcomeResponseCheckState state;

        /** Set {@code kind}. */
        public Builder kind(@Nullable GetPublicRunOutcomeResponseCheckKind kind) {
            this.kind = kind;
            return this;
        }

        /** Set {@code reproduction}. */
        public Builder reproduction(@Nullable PrReportReproductionVerdict reproduction) {
            this.reproduction = reproduction;
            return this;
        }

        /** Set {@code state}. */
        public Builder state(@Nullable GetPublicRunOutcomeResponseCheckState state) {
            this.state = state;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseCheck}. */
        public GetPublicRunOutcomeResponseCheck build() {
            return new GetPublicRunOutcomeResponseCheck(kind, reproduction, state);
        }
    }
}
