// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseTestsVariant1} wire model.
 * @param abortReason Always present; {@code null} when the server has no value for it.
 * @param areas the {@code areas} field.
 * @param concerns the {@code concerns} field.
 * @param environment Always present; {@code null} when the server has no value for it.
 * @param failed the {@code failed} field.
 * @param passed the {@code passed} field.
 * @param skipped the {@code skipped} field.
 * @param status the {@code status} field.
 * @param summary Always present; {@code null} when the server has no value for it.
 * @param verdict the {@code verdict} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseTestsVariant1(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("abortReason") @Nullable String abortReason,

    @JsonProperty("areas") List<String> areas,

    @JsonProperty("concerns") List<GetPublicRunOutcomeResponseTestsVariant1Concern> concerns,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("environment") @Nullable PrReportEnvironmentsEvidenceRanAgainst environment,

    @JsonProperty("failed") Double failed,

    @JsonProperty("passed") Double passed,

    @JsonProperty("skipped") Double skipped,

    @JsonProperty("status") String status,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("summary") @Nullable String summary,

    @JsonProperty("verdict") GetPublicRunOutcomeResponseTestsVariant1Verdict verdict
) implements GetPublicRunOutcomeResponseTests {

    /** A new builder for {@link GetPublicRunOutcomeResponseTestsVariant1}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseTestsVariant1}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String abortReason;
        private @Nullable List<String> areas;
        private @Nullable List<GetPublicRunOutcomeResponseTestsVariant1Concern> concerns;
        private @Nullable PrReportEnvironmentsEvidenceRanAgainst environment;
        private @Nullable Double failed;
        private @Nullable Double passed;
        private @Nullable Double skipped;
        private @Nullable String status;
        private @Nullable String summary;
        private @Nullable GetPublicRunOutcomeResponseTestsVariant1Verdict verdict;

        /** Set {@code abortReason}. */
        public Builder abortReason(@Nullable String abortReason) {
            this.abortReason = abortReason;
            return this;
        }

        /** Set {@code areas}. */
        public Builder areas(@Nullable List<String> areas) {
            this.areas = areas;
            return this;
        }

        /** Set {@code concerns}. */
        public Builder concerns(@Nullable List<GetPublicRunOutcomeResponseTestsVariant1Concern> concerns) {
            this.concerns = concerns;
            return this;
        }

        /** Set {@code environment}. */
        public Builder environment(@Nullable PrReportEnvironmentsEvidenceRanAgainst environment) {
            this.environment = environment;
            return this;
        }

        /** Set {@code failed}. */
        public Builder failed(@Nullable Double failed) {
            this.failed = failed;
            return this;
        }

        /** Set {@code passed}. */
        public Builder passed(@Nullable Double passed) {
            this.passed = passed;
            return this;
        }

        /** Set {@code skipped}. */
        public Builder skipped(@Nullable Double skipped) {
            this.skipped = skipped;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable String status) {
            this.status = status;
            return this;
        }

        /** Set {@code summary}. */
        public Builder summary(@Nullable String summary) {
            this.summary = summary;
            return this;
        }

        /** Set {@code verdict}. */
        public Builder verdict(@Nullable GetPublicRunOutcomeResponseTestsVariant1Verdict verdict) {
            this.verdict = verdict;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseTestsVariant1}. */
        public GetPublicRunOutcomeResponseTestsVariant1 build() {
            return new GetPublicRunOutcomeResponseTestsVariant1(abortReason, areas, concerns, environment, failed, passed, skipped, status, summary, verdict);
        }
    }
}
