// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GetPublicRunOutcomeResponseVisualsVariant1} wire model.
 * @param phase Always present; {@code null} when the server has no value for it.
 * @param source the {@code source} field.
 * @param status the {@code status} field.
 * @param views the {@code views} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GetPublicRunOutcomeResponseVisualsVariant1(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("phase") @Nullable PublicVisualConfirmDecisionPhase phase,

    @JsonProperty("source") GetPublicRunOutcomeResponseVisualsVariant1Source source,

    @JsonProperty("status") String status,

    @JsonProperty("views") List<GetPublicRunOutcomeResponseVisualsVariant1View> views
) implements GetPublicRunOutcomeResponseVisuals {

    /** A new builder for {@link GetPublicRunOutcomeResponseVisualsVariant1}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GetPublicRunOutcomeResponseVisualsVariant1}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable PublicVisualConfirmDecisionPhase phase;
        private @Nullable GetPublicRunOutcomeResponseVisualsVariant1Source source;
        private @Nullable String status;
        private @Nullable List<GetPublicRunOutcomeResponseVisualsVariant1View> views;

        /** Set {@code phase}. */
        public Builder phase(@Nullable PublicVisualConfirmDecisionPhase phase) {
            this.phase = phase;
            return this;
        }

        /** Set {@code source}. */
        public Builder source(@Nullable GetPublicRunOutcomeResponseVisualsVariant1Source source) {
            this.source = source;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable String status) {
            this.status = status;
            return this;
        }

        /** Set {@code views}. */
        public Builder views(@Nullable List<GetPublicRunOutcomeResponseVisualsVariant1View> views) {
            this.views = views;
            return this;
        }

        /** Build the {@link GetPublicRunOutcomeResponseVisualsVariant1}. */
        public GetPublicRunOutcomeResponseVisualsVariant1 build() {
            return new GetPublicRunOutcomeResponseVisualsVariant1(phase, source, status, views);
        }
    }
}
