// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code GuidedReviewPostResult} wire model.
 * @param drafts the {@code drafts} field.
 * @param failed Range 0..unbounded.
 * @param posted Range 0..unbounded.
 * @param skipped the {@code skipped} field.
 * @param summary the {@code summary} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record GuidedReviewPostResult(
    @JsonProperty("drafts") List<GuidedReviewCommentDraft> drafts,

    /** Range 0..unbounded. */
    @JsonProperty("failed") Integer failed,

    /** Range 0..unbounded. */
    @JsonProperty("posted") Integer posted,

    @JsonProperty("skipped") List<String> skipped,

    @JsonProperty("summary") GuidedReviewPostResultSummary summary
) {

    /** A new builder for {@link GuidedReviewPostResult}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link GuidedReviewPostResult}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<GuidedReviewCommentDraft> drafts;
        private @Nullable Integer failed;
        private @Nullable Integer posted;
        private @Nullable List<String> skipped;
        private @Nullable GuidedReviewPostResultSummary summary;

        /** Set {@code drafts}. */
        public Builder drafts(@Nullable List<GuidedReviewCommentDraft> drafts) {
            this.drafts = drafts;
            return this;
        }

        /** Set {@code failed}. */
        public Builder failed(@Nullable Integer failed) {
            this.failed = failed;
            return this;
        }

        /** Set {@code posted}. */
        public Builder posted(@Nullable Integer posted) {
            this.posted = posted;
            return this;
        }

        /** Set {@code skipped}. */
        public Builder skipped(@Nullable List<String> skipped) {
            this.skipped = skipped;
            return this;
        }

        /** Set {@code summary}. */
        public Builder summary(@Nullable GuidedReviewPostResultSummary summary) {
            this.summary = summary;
            return this;
        }

        /** Build the {@link GuidedReviewPostResult}. */
        public GuidedReviewPostResult build() {
            return new GuidedReviewPostResult(drafts, failed, posted, skipped, summary);
        }
    }
}
