// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code InvokePublicUseCaseResponseUsage} wire model.
 * @param inputTokens the {@code inputTokens} field.
 * @param outputTokens the {@code outputTokens} field.
 * @param totalTokens the {@code totalTokens} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record InvokePublicUseCaseResponseUsage(
    @JsonProperty("inputTokens") Double inputTokens,

    @JsonProperty("outputTokens") Double outputTokens,

    @JsonProperty("totalTokens") Double totalTokens
) {

    /** A new builder for {@link InvokePublicUseCaseResponseUsage}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link InvokePublicUseCaseResponseUsage}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double inputTokens;
        private @Nullable Double outputTokens;
        private @Nullable Double totalTokens;

        /** Set {@code inputTokens}. */
        public Builder inputTokens(@Nullable Double inputTokens) {
            this.inputTokens = inputTokens;
            return this;
        }

        /** Set {@code outputTokens}. */
        public Builder outputTokens(@Nullable Double outputTokens) {
            this.outputTokens = outputTokens;
            return this;
        }

        /** Set {@code totalTokens}. */
        public Builder totalTokens(@Nullable Double totalTokens) {
            this.totalTokens = totalTokens;
            return this;
        }

        /** Build the {@link InvokePublicUseCaseResponseUsage}. */
        public InvokePublicUseCaseResponseUsage build() {
            return new InvokePublicUseCaseResponseUsage(inputTokens, outputTokens, totalTokens);
        }
    }
}
