// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for {@code kaizen().listEntries()}.
 * Every parameter is optional; a null one is not sent at all.
 */
public record KaizenListEntriesQuery(
    /** Null means "not sent". */
    @Nullable Integer limit,

    /** Null means "not sent". */
    @Nullable String cursor,

    /** Null means "not sent". */
    @Nullable ListPublicKaizenEntriesAcknowledged acknowledged,

    /** Null means "not sent". */
    @Nullable PublicKaizenEntryStatus status,

    /** Null means "not sent". */
    @Nullable String agentKind,

    /** Null means "not sent". */
    @Nullable Integer since
) {

    /** An empty parameter set. */
    public static KaizenListEntriesQuery none() {
        return builder().build();
    }

    /** A new builder for {@link KaizenListEntriesQuery}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Render to the wire query map, omitting every unset parameter. */
    public Map<String, String> toQuery() {
        Map<String, String> out = new LinkedHashMap<>();
        if (limit != null) {
            out.put("limit", String.valueOf(limit));
        }
        if (cursor != null) {
            out.put("cursor", String.valueOf(cursor));
        }
        if (acknowledged != null) {
            out.put("acknowledged", String.valueOf(acknowledged));
        }
        if (status != null) {
            out.put("status", String.valueOf(status));
        }
        if (agentKind != null) {
            out.put("agentKind", String.valueOf(agentKind));
        }
        if (since != null) {
            out.put("since", String.valueOf(since));
        }
        return out;
    }

    /** Fluent builder for {@link KaizenListEntriesQuery}. */
    public static final class Builder {
        private @Nullable Integer limit;
        private @Nullable String cursor;
        private @Nullable ListPublicKaizenEntriesAcknowledged acknowledged;
        private @Nullable PublicKaizenEntryStatus status;
        private @Nullable String agentKind;
        private @Nullable Integer since;

        /** Set {@code limit}. */
        public Builder limit(@Nullable Integer limit) {
            this.limit = limit;
            return this;
        }

        /** Set {@code cursor}. */
        public Builder cursor(@Nullable String cursor) {
            this.cursor = cursor;
            return this;
        }

        /** Set {@code acknowledged}. */
        public Builder acknowledged(@Nullable ListPublicKaizenEntriesAcknowledged acknowledged) {
            this.acknowledged = acknowledged;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable PublicKaizenEntryStatus status) {
            this.status = status;
            return this;
        }

        /** Set {@code agentKind}. */
        public Builder agentKind(@Nullable String agentKind) {
            this.agentKind = agentKind;
            return this;
        }

        /** Set {@code since}. */
        public Builder since(@Nullable Integer since) {
            this.since = since;
            return this;
        }

        /** Build the {@link KaizenListEntriesQuery}. */
        public KaizenListEntriesQuery build() {
            return new KaizenListEntriesQuery(limit, cursor, acknowledged, status, agentKind, since);
        }
    }
}
