// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ListPublicTaskTypesResponseTaskTypeFieldShowWhen} wire model.
 * @param equals May be absent entirely.
 * @param includes May be absent entirely.
 * @param key Length 1..unbounded.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListPublicTaskTypesResponseTaskTypeFieldShowWhen(
    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("equals") @Nullable ListPublicTaskTypesResponseTaskTypeFieldShowWhenEquals equals,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("includes") @Nullable String includes,

    /** Length 1..unbounded. */
    @JsonProperty("key") String key
) {

    /** A new builder for {@link ListPublicTaskTypesResponseTaskTypeFieldShowWhen}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ListPublicTaskTypesResponseTaskTypeFieldShowWhen}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable ListPublicTaskTypesResponseTaskTypeFieldShowWhenEquals equals;
        private @Nullable String includes;
        private @Nullable String key;

        /** Set {@code equals}. */
        public Builder equals(@Nullable ListPublicTaskTypesResponseTaskTypeFieldShowWhenEquals equals) {
            this.equals = equals;
            return this;
        }

        /** Set {@code includes}. */
        public Builder includes(@Nullable String includes) {
            this.includes = includes;
            return this;
        }

        /** Set {@code key}. */
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }

        /** Build the {@link ListPublicTaskTypesResponseTaskTypeFieldShowWhen}. */
        public ListPublicTaskTypesResponseTaskTypeFieldShowWhen build() {
            return new ListPublicTaskTypesResponseTaskTypeFieldShowWhen(equals, includes, key);
        }
    }
}
