// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ListPublicMergeClassRollupsResponseRollup} wire model.
 * @param autoMerged the {@code autoMerged} field.
 * @param changeClass the {@code changeClass} field.
 * @param effort the {@code effort} field.
 * @param externalMerged the {@code externalMerged} field.
 * @param humanMerged the {@code humanMerged} field.
 * @param merged the {@code merged} field.
 * @param pendingReview the {@code pendingReview} field.
 * @param rejected the {@code rejected} field.
 * @param total the {@code total} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListPublicMergeClassRollupsResponseRollup(
    @JsonProperty("autoMerged") Double autoMerged,

    @JsonProperty("changeClass") NotificationPayloadChangeClass changeClass,

    @JsonProperty("effort") ListPublicMergeClassRollupsResponseRollupEffort effort,

    @JsonProperty("externalMerged") Double externalMerged,

    @JsonProperty("humanMerged") Double humanMerged,

    @JsonProperty("merged") Double merged,

    @JsonProperty("pendingReview") Double pendingReview,

    @JsonProperty("rejected") Double rejected,

    @JsonProperty("total") Double total
) {

    /** A new builder for {@link ListPublicMergeClassRollupsResponseRollup}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ListPublicMergeClassRollupsResponseRollup}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double autoMerged;
        private @Nullable NotificationPayloadChangeClass changeClass;
        private @Nullable ListPublicMergeClassRollupsResponseRollupEffort effort;
        private @Nullable Double externalMerged;
        private @Nullable Double humanMerged;
        private @Nullable Double merged;
        private @Nullable Double pendingReview;
        private @Nullable Double rejected;
        private @Nullable Double total;

        /** Set {@code autoMerged}. */
        public Builder autoMerged(@Nullable Double autoMerged) {
            this.autoMerged = autoMerged;
            return this;
        }

        /** Set {@code changeClass}. */
        public Builder changeClass(@Nullable NotificationPayloadChangeClass changeClass) {
            this.changeClass = changeClass;
            return this;
        }

        /** Set {@code effort}. */
        public Builder effort(@Nullable ListPublicMergeClassRollupsResponseRollupEffort effort) {
            this.effort = effort;
            return this;
        }

        /** Set {@code externalMerged}. */
        public Builder externalMerged(@Nullable Double externalMerged) {
            this.externalMerged = externalMerged;
            return this;
        }

        /** Set {@code humanMerged}. */
        public Builder humanMerged(@Nullable Double humanMerged) {
            this.humanMerged = humanMerged;
            return this;
        }

        /** Set {@code merged}. */
        public Builder merged(@Nullable Double merged) {
            this.merged = merged;
            return this;
        }

        /** Set {@code pendingReview}. */
        public Builder pendingReview(@Nullable Double pendingReview) {
            this.pendingReview = pendingReview;
            return this;
        }

        /** Set {@code rejected}. */
        public Builder rejected(@Nullable Double rejected) {
            this.rejected = rejected;
            return this;
        }

        /** Set {@code total}. */
        public Builder total(@Nullable Double total) {
            this.total = total;
            return this;
        }

        /** Build the {@link ListPublicMergeClassRollupsResponseRollup}. */
        public ListPublicMergeClassRollupsResponseRollup build() {
            return new ListPublicMergeClassRollupsResponseRollup(autoMerged, changeClass, effort, externalMerged, humanMerged, merged, pendingReview, rejected, total);
        }
    }
}
