// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ListPublicModelPresetsResponse} wire model.
 * @param presets the {@code presets} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListPublicModelPresetsResponse(
    @JsonProperty("presets") List<ListPublicModelPresetsResponsePreset> presets
) {

    /** A new builder for {@link ListPublicModelPresetsResponse}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ListPublicModelPresetsResponse}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<ListPublicModelPresetsResponsePreset> presets;

        /** Set {@code presets}. */
        public Builder presets(@Nullable List<ListPublicModelPresetsResponsePreset> presets) {
            this.presets = presets;
            return this;
        }

        /** Build the {@link ListPublicModelPresetsResponse}. */
        public ListPublicModelPresetsResponse build() {
            return new ListPublicModelPresetsResponse(presets);
        }
    }
}
