// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ListPublicWiredModelsResponse} wire model.
 * @param excludesUserScopedModels the {@code excludesUserScopedModels} field.
 * @param models the {@code models} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListPublicWiredModelsResponse(
    @JsonProperty("excludesUserScopedModels") Boolean excludesUserScopedModels,

    @JsonProperty("models") List<ListPublicWiredModelsResponseModel> models
) {

    /** A new builder for {@link ListPublicWiredModelsResponse}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ListPublicWiredModelsResponse}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Boolean excludesUserScopedModels;
        private @Nullable List<ListPublicWiredModelsResponseModel> models;

        /** Set {@code excludesUserScopedModels}. */
        public Builder excludesUserScopedModels(@Nullable Boolean excludesUserScopedModels) {
            this.excludesUserScopedModels = excludesUserScopedModels;
            return this;
        }

        /** Set {@code models}. */
        public Builder models(@Nullable List<ListPublicWiredModelsResponseModel> models) {
            this.models = models;
            return this;
        }

        /** Build the {@link ListPublicWiredModelsResponse}. */
        public ListPublicWiredModelsResponse build() {
            return new ListPublicWiredModelsResponse(excludesUserScopedModels, models);
        }
    }
}
