// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code ListDebugLogsResponse} wire model.
 * @param entries the {@code entries} field.
 * @param nextCursor Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ListDebugLogsResponse(
    @JsonProperty("entries") List<DebugInfraLogEntry> entries,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("nextCursor") @Nullable String nextCursor
) {

    /** A new builder for {@link ListDebugLogsResponse}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link ListDebugLogsResponse}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<DebugInfraLogEntry> entries;
        private @Nullable String nextCursor;

        /** Set {@code entries}. */
        public Builder entries(@Nullable List<DebugInfraLogEntry> entries) {
            this.entries = entries;
            return this;
        }

        /** Set {@code nextCursor}. */
        public Builder nextCursor(@Nullable String nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        /** Build the {@link ListDebugLogsResponse}. */
        public ListDebugLogsResponse build() {
            return new ListDebugLogsResponse(entries, nextCursor);
        }
    }
}
