// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jspecify.annotations.Nullable;

/**
 * The {@code NotificationPayloadPlatformAlert} vocabulary.
 * Decoding an unrecognised value yields {@link #UNRECOGNIZED} rather than throwing, and {@link
 * #wireValue()} still returns what the server actually sent. This surface is additive, so refusing
 * a value the server legitimately added would break a caller on a release it was never told about.
 */
public enum NotificationPayloadPlatformAlert {
    FAILURE_RATE_HIGH("failure_rate_high"),
    DURATION_P99_HIGH("duration_p99_high"),
    BACKLOG_HIGH("backlog_high"),
    THROUGHPUT_STALLED("throughput_stalled"),
    FAILURE_KIND_DOMINANT("failure_kind_dominant"),
    FAILURE_KIND_RATE_HIGH("failure_kind_rate_high"),
    SWEEP_DEGRADED("sweep_degraded"),

    /**
     * A value this SDK release does not know.
     *
     * <p>Deliberately NOT named {@code UNKNOWN}: several of these vocabularies carry a real
     * wire value {@code unknown} (a run whose failure kind could not be determined), and
     * "the server said unknown" and "this SDK has not heard of what the server said" are
     * different facts that must not collapse onto one constant.
     */
    UNRECOGNIZED("");

    private final String wire;

    NotificationPayloadPlatformAlert(String wire) {
        this.wire = wire;
    }

    /** The value as carried on the wire. */
    @JsonValue
    public String wireValue() {
        return wire;
    }

    /** Decode from the wire, tolerating a value this release does not know. */
    @JsonCreator
    public static NotificationPayloadPlatformAlert fromWire(@Nullable String wire) {
        for (NotificationPayloadPlatformAlert candidate : values()) {
            if (candidate.wire.equals(wire)) {
                return candidate;
            }
        }
        return UNRECOGNIZED;
    }
}
