// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PlatformAlertWebhookDeliveryAlertCondition} wire model.
 * @param kind May be absent entirely.
 * @param reason the {@code reason} field.
 * @param threshold the {@code threshold} field.
 * @param value the {@code value} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PlatformAlertWebhookDeliveryAlertCondition(
    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("kind") @Nullable String kind,

    @JsonProperty("reason") String reason,

    @JsonProperty("threshold") Double threshold,

    @JsonProperty("value") Double value
) {

    /** A new builder for {@link PlatformAlertWebhookDeliveryAlertCondition}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PlatformAlertWebhookDeliveryAlertCondition}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String kind;
        private @Nullable String reason;
        private @Nullable Double threshold;
        private @Nullable Double value;

        /** Set {@code kind}. */
        public Builder kind(@Nullable String kind) {
            this.kind = kind;
            return this;
        }

        /** Set {@code reason}. */
        public Builder reason(@Nullable String reason) {
            this.reason = reason;
            return this;
        }

        /** Set {@code threshold}. */
        public Builder threshold(@Nullable Double threshold) {
            this.threshold = threshold;
            return this;
        }

        /** Set {@code value}. */
        public Builder value(@Nullable Double value) {
            this.value = value;
            return this;
        }

        /** Build the {@link PlatformAlertWebhookDeliveryAlertCondition}. */
        public PlatformAlertWebhookDeliveryAlertCondition build() {
            return new PlatformAlertWebhookDeliveryAlertCondition(kind, reason, threshold, value);
        }
    }
}
