// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PrReportEnvironmentsEvidenceScreenshot} wire model.
 * @param artifactId the {@code artifactId} field.
 * @param hasReference the {@code hasReference} field.
 * @param url Always present; {@code null} when the server has no value for it.
 * @param view the {@code view} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PrReportEnvironmentsEvidenceScreenshot(
    @JsonProperty("artifactId") String artifactId,

    @JsonProperty("hasReference") Boolean hasReference,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("url") @Nullable String url,

    @JsonProperty("view") String view
) {

    /** A new builder for {@link PrReportEnvironmentsEvidenceScreenshot}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PrReportEnvironmentsEvidenceScreenshot}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String artifactId;
        private @Nullable Boolean hasReference;
        private @Nullable String url;
        private @Nullable String view;

        /** Set {@code artifactId}. */
        public Builder artifactId(@Nullable String artifactId) {
            this.artifactId = artifactId;
            return this;
        }

        /** Set {@code hasReference}. */
        public Builder hasReference(@Nullable Boolean hasReference) {
            this.hasReference = hasReference;
            return this;
        }

        /** Set {@code url}. */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /** Set {@code view}. */
        public Builder view(@Nullable String view) {
            this.view = view;
            return this;
        }

        /** Build the {@link PrReportEnvironmentsEvidenceScreenshot}. */
        public PrReportEnvironmentsEvidenceScreenshot build() {
            return new PrReportEnvironmentsEvidenceScreenshot(artifactId, hasReference, url, view);
        }
    }
}
