// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PrReportContext} wire model.
 * @param documents the {@code documents} field.
 * @param note May be absent entirely.
 * @param status the {@code status} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PrReportContext(
    @JsonProperty("documents") List<PrReportContextDocument> documents,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("note") @Nullable String note,

    @JsonProperty("status") PrReportCiStatus status
) {

    /** A new builder for {@link PrReportContext}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PrReportContext}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<PrReportContextDocument> documents;
        private @Nullable String note;
        private @Nullable PrReportCiStatus status;

        /** Set {@code documents}. */
        public Builder documents(@Nullable List<PrReportContextDocument> documents) {
            this.documents = documents;
            return this;
        }

        /** Set {@code note}. */
        public Builder note(@Nullable String note) {
            this.note = note;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable PrReportCiStatus status) {
            this.status = status;
            return this;
        }

        /** Build the {@link PrReportContext}. */
        public PrReportContext build() {
            return new PrReportContext(documents, note, status);
        }
    }
}
