// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PrVerificationReportFollowUpsDroppedBudget} wire model.
 * @param loops the {@code loops} field.
 * @param maxLoops the {@code maxLoops} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PrVerificationReportFollowUpsDroppedBudget(
    @JsonProperty("loops") Double loops,

    @JsonProperty("maxLoops") Double maxLoops
) {

    /** A new builder for {@link PrVerificationReportFollowUpsDroppedBudget}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PrVerificationReportFollowUpsDroppedBudget}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double loops;
        private @Nullable Double maxLoops;

        /** Set {@code loops}. */
        public Builder loops(@Nullable Double loops) {
            this.loops = loops;
            return this;
        }

        /** Set {@code maxLoops}. */
        public Builder maxLoops(@Nullable Double maxLoops) {
            this.maxLoops = maxLoops;
            return this;
        }

        /** Build the {@link PrVerificationReportFollowUpsDroppedBudget}. */
        public PrVerificationReportFollowUpsDroppedBudget build() {
            return new PrVerificationReportFollowUpsDroppedBudget(loops, maxLoops);
        }
    }
}
