// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicPrReviewDecisionSlice} wire model.
 * @param id the {@code id} field.
 * @param paths the {@code paths} field.
 * @param rationale the {@code rationale} field.
 * @param title the {@code title} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicPrReviewDecisionSlice(
    @JsonProperty("id") String id,

    @JsonProperty("paths") List<String> paths,

    @JsonProperty("rationale") String rationale,

    @JsonProperty("title") String title
) {

    /** A new builder for {@link PublicPrReviewDecisionSlice}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicPrReviewDecisionSlice}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String id;
        private @Nullable List<String> paths;
        private @Nullable String rationale;
        private @Nullable String title;

        /** Set {@code id}. */
        public Builder id(@Nullable String id) {
            this.id = id;
            return this;
        }

        /** Set {@code paths}. */
        public Builder paths(@Nullable List<String> paths) {
            this.paths = paths;
            return this;
        }

        /** Set {@code rationale}. */
        public Builder rationale(@Nullable String rationale) {
            this.rationale = rationale;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Build the {@link PublicPrReviewDecisionSlice}. */
        public PublicPrReviewDecisionSlice build() {
            return new PublicPrReviewDecisionSlice(id, paths, rationale, title);
        }
    }
}
