// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicBugFishingSpawn} wire model.
 * @param executionId Always present; {@code null} when the server has no value for it.
 * @param failureReason Always present; {@code null} when the server has no value for it.
 * @param pipelineId the {@code pipelineId} field.
 * @param requestedAt the {@code requestedAt} field.
 * @param status the {@code status} field.
 * @param taskId the {@code taskId} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicBugFishingSpawn(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("executionId") @Nullable String executionId,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("failureReason") @Nullable String failureReason,

    @JsonProperty("pipelineId") String pipelineId,

    @JsonProperty("requestedAt") Double requestedAt,

    @JsonProperty("status") PublicBugFishingSpawnStatus status,

    @JsonProperty("taskId") String taskId
) {

    /** A new builder for {@link PublicBugFishingSpawn}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicBugFishingSpawn}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String executionId;
        private @Nullable String failureReason;
        private @Nullable String pipelineId;
        private @Nullable Double requestedAt;
        private @Nullable PublicBugFishingSpawnStatus status;
        private @Nullable String taskId;

        /** Set {@code executionId}. */
        public Builder executionId(@Nullable String executionId) {
            this.executionId = executionId;
            return this;
        }

        /** Set {@code failureReason}. */
        public Builder failureReason(@Nullable String failureReason) {
            this.failureReason = failureReason;
            return this;
        }

        /** Set {@code pipelineId}. */
        public Builder pipelineId(@Nullable String pipelineId) {
            this.pipelineId = pipelineId;
            return this;
        }

        /** Set {@code requestedAt}. */
        public Builder requestedAt(@Nullable Double requestedAt) {
            this.requestedAt = requestedAt;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable PublicBugFishingSpawnStatus status) {
            this.status = status;
            return this;
        }

        /** Set {@code taskId}. */
        public Builder taskId(@Nullable String taskId) {
            this.taskId = taskId;
            return this;
        }

        /** Build the {@link PublicBugFishingSpawn}. */
        public PublicBugFishingSpawn build() {
            return new PublicBugFishingSpawn(executionId, failureReason, pipelineId, requestedAt, status, taskId);
        }
    }
}
