// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicNotificationWebhook} wire model.
 * @param webhook Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicNotificationWebhook(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("webhook") @Nullable NotificationWebhook webhook
) {

    /** A new builder for {@link PublicNotificationWebhook}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicNotificationWebhook}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable NotificationWebhook webhook;

        /** Set {@code webhook}. */
        public Builder webhook(@Nullable NotificationWebhook webhook) {
            this.webhook = webhook;
            return this;
        }

        /** Build the {@link PublicNotificationWebhook}. */
        public PublicNotificationWebhook build() {
            return new PublicNotificationWebhook(webhook);
        }
    }
}
