// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicHumanTestEnvironment} wire model.
 * @param expiresAt Always present; {@code null} when the server has no value for it.
 * @param status the {@code status} field.
 * @param url Always present; {@code null} when the server has no value for it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicHumanTestEnvironment(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("expiresAt") @Nullable Double expiresAt,

    @JsonProperty("status") PublicHumanTestEnvironmentStatus status,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("url") @Nullable String url
) {

    /** A new builder for {@link PublicHumanTestEnvironment}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicHumanTestEnvironment}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Double expiresAt;
        private @Nullable PublicHumanTestEnvironmentStatus status;
        private @Nullable String url;

        /** Set {@code expiresAt}. */
        public Builder expiresAt(@Nullable Double expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable PublicHumanTestEnvironmentStatus status) {
            this.status = status;
            return this;
        }

        /** Set {@code url}. */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /** Build the {@link PublicHumanTestEnvironment}. */
        public PublicHumanTestEnvironment build() {
            return new PublicHumanTestEnvironment(expiresAt, status, url);
        }
    }
}
