// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicApproveStep} wire model.
 * @param proposal May be absent entirely. Length 0..50000.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicApproveStep(
    /** May be absent entirely. Length 0..50000. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("proposal") @Nullable String proposal
) {

    /** A new builder for {@link PublicApproveStep}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicApproveStep}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String proposal;

        /** Set {@code proposal}. */
        public Builder proposal(@Nullable String proposal) {
            this.proposal = proposal;
            return this;
        }

        /** Build the {@link PublicApproveStep}. */
        public PublicApproveStep build() {
            return new PublicApproveStep(proposal);
        }
    }
}
