// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicInputGateDecisionIssueField} wire model.
 * @param key Length 1..200.
 * @param label Length 1..200.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicInputGateDecisionIssueField(
    /** Length 1..200. */
    @JsonProperty("key") String key,

    /** Length 1..200. */
    @JsonProperty("label") String label
) {

    /** A new builder for {@link PublicInputGateDecisionIssueField}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicInputGateDecisionIssueField}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String key;
        private @Nullable String label;

        /** Set {@code key}. */
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }

        /** Set {@code label}. */
        public Builder label(@Nullable String label) {
            this.label = label;
            return this;
        }

        /** Build the {@link PublicInputGateDecisionIssueField}. */
        public PublicInputGateDecisionIssueField build() {
            return new PublicInputGateDecisionIssueField(key, label);
        }
    }
}
