// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicVisualConfirmDecisionPair} wire model.
 * @param actualArtifactId May be absent entirely.
 * @param referenceArtifactId May be absent entirely.
 * @param view the {@code view} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicVisualConfirmDecisionPair(
    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("actualArtifactId") @Nullable String actualArtifactId,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("referenceArtifactId") @Nullable String referenceArtifactId,

    @JsonProperty("view") String view
) {

    /** A new builder for {@link PublicVisualConfirmDecisionPair}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicVisualConfirmDecisionPair}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String actualArtifactId;
        private @Nullable String referenceArtifactId;
        private @Nullable String view;

        /** Set {@code actualArtifactId}. */
        public Builder actualArtifactId(@Nullable String actualArtifactId) {
            this.actualArtifactId = actualArtifactId;
            return this;
        }

        /** Set {@code referenceArtifactId}. */
        public Builder referenceArtifactId(@Nullable String referenceArtifactId) {
            this.referenceArtifactId = referenceArtifactId;
            return this;
        }

        /** Set {@code view}. */
        public Builder view(@Nullable String view) {
            this.view = view;
            return this;
        }

        /** Build the {@link PublicVisualConfirmDecisionPair}. */
        public PublicVisualConfirmDecisionPair build() {
            return new PublicVisualConfirmDecisionPair(actualArtifactId, referenceArtifactId, view);
        }
    }
}
