// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicKaizenEntryTask} wire model.
 * @param serviceId Always present; {@code null} when the server has no value for it.
 * @param serviceTitle Always present; {@code null} when the server has no value for it.
 * @param status the {@code status} field.
 * @param title the {@code title} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicKaizenEntryTask(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("serviceId") @Nullable String serviceId,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("serviceTitle") @Nullable String serviceTitle,

    @JsonProperty("status") TaskStatus status,

    @JsonProperty("title") String title
) {

    /** A new builder for {@link PublicKaizenEntryTask}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicKaizenEntryTask}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String serviceId;
        private @Nullable String serviceTitle;
        private @Nullable TaskStatus status;
        private @Nullable String title;

        /** Set {@code serviceId}. */
        public Builder serviceId(@Nullable String serviceId) {
            this.serviceId = serviceId;
            return this;
        }

        /** Set {@code serviceTitle}. */
        public Builder serviceTitle(@Nullable String serviceTitle) {
            this.serviceTitle = serviceTitle;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable TaskStatus status) {
            this.status = status;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Build the {@link PublicKaizenEntryTask}. */
        public PublicKaizenEntryTask build() {
            return new PublicKaizenEntryTask(serviceId, serviceTitle, status, title);
        }
    }
}
