// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicInterviewDecision} wire model.
 * @param kind the {@code kind} field.
 * @param maxRounds the {@code maxRounds} field.
 * @param questions the {@code questions} field.
 * @param round the {@code round} field.
 * @param stepKind the {@code stepKind} field.
 * @param taskId the {@code taskId} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicInterviewDecision(
    @JsonProperty("kind") String kind,

    @JsonProperty("maxRounds") Double maxRounds,

    @JsonProperty("questions") List<PublicInterviewQuestion> questions,

    @JsonProperty("round") Double round,

    @JsonProperty("stepKind") String stepKind,

    @JsonProperty("taskId") String taskId
) implements PublicDecision {

    /** A new builder for {@link PublicInterviewDecision}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicInterviewDecision}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String kind;
        private @Nullable Double maxRounds;
        private @Nullable List<PublicInterviewQuestion> questions;
        private @Nullable Double round;
        private @Nullable String stepKind;
        private @Nullable String taskId;

        /** Set {@code kind}. */
        public Builder kind(@Nullable String kind) {
            this.kind = kind;
            return this;
        }

        /** Set {@code maxRounds}. */
        public Builder maxRounds(@Nullable Double maxRounds) {
            this.maxRounds = maxRounds;
            return this;
        }

        /** Set {@code questions}. */
        public Builder questions(@Nullable List<PublicInterviewQuestion> questions) {
            this.questions = questions;
            return this;
        }

        /** Set {@code round}. */
        public Builder round(@Nullable Double round) {
            this.round = round;
            return this;
        }

        /** Set {@code stepKind}. */
        public Builder stepKind(@Nullable String stepKind) {
            this.stepKind = stepKind;
            return this;
        }

        /** Set {@code taskId}. */
        public Builder taskId(@Nullable String taskId) {
            this.taskId = taskId;
            return this;
        }

        /** Build the {@link PublicInterviewDecision}. */
        public PublicInterviewDecision build() {
            return new PublicInterviewDecision(kind, maxRounds, questions, round, stepKind, taskId);
        }
    }
}
