// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicApprovalGateDecisionBlockingFinding} wire model.
 * @param anchorId Always present; {@code null} when the server has no value for it.
 * @param body the {@code body} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicApprovalGateDecisionBlockingFinding(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("anchorId") @Nullable String anchorId,

    @JsonProperty("body") String body
) {

    /** A new builder for {@link PublicApprovalGateDecisionBlockingFinding}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicApprovalGateDecisionBlockingFinding}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String anchorId;
        private @Nullable String body;

        /** Set {@code anchorId}. */
        public Builder anchorId(@Nullable String anchorId) {
            this.anchorId = anchorId;
            return this;
        }

        /** Set {@code body}. */
        public Builder body(@Nullable String body) {
            this.body = body;
            return this;
        }

        /** Build the {@link PublicApprovalGateDecisionBlockingFinding}. */
        public PublicApprovalGateDecisionBlockingFinding build() {
            return new PublicApprovalGateDecisionBlockingFinding(anchorId, body);
        }
    }
}
