// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicNotificationWebhookList} wire model.
 * @param webhooks the {@code webhooks} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicNotificationWebhookList(
    @JsonProperty("webhooks") List<NotificationWebhook> webhooks
) {

    /** A new builder for {@link PublicNotificationWebhookList}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicNotificationWebhookList}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable List<NotificationWebhook> webhooks;

        /** Set {@code webhooks}. */
        public Builder webhooks(@Nullable List<NotificationWebhook> webhooks) {
            this.webhooks = webhooks;
            return this;
        }

        /** Build the {@link PublicNotificationWebhookList}. */
        public PublicNotificationWebhookList build() {
            return new PublicNotificationWebhookList(webhooks);
        }
    }
}
