// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code PublicBugFishingPhase} wire model.
 * @param failureReason Always present; {@code null} when the server has no value for it.
 * @param filesRead Always present; {@code null} when the server has no value for it.
 * @param goal the {@code goal} field.
 * @param manifestFiles Always present; {@code null} when the server has no value for it.
 * @param phaseId the {@code phaseId} field.
 * @param settledAt Always present; {@code null} when the server has no value for it.
 * @param status the {@code status} field.
 * @param summary Always present; {@code null} when the server has no value for it.
 * @param territoryId Always present; {@code null} when the server has no value for it.
 * @param territoryLabel Always present; {@code null} when the server has no value for it.
 * @param title the {@code title} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record PublicBugFishingPhase(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("failureReason") @Nullable String failureReason,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("filesRead") @Nullable Double filesRead,

    @JsonProperty("goal") String goal,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("manifestFiles") @Nullable Double manifestFiles,

    @JsonProperty("phaseId") String phaseId,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("settledAt") @Nullable Double settledAt,

    @JsonProperty("status") PublicBugFishingPhaseStatus status,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("summary") @Nullable String summary,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("territoryId") @Nullable String territoryId,

    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("territoryLabel") @Nullable String territoryLabel,

    @JsonProperty("title") String title
) {

    /** A new builder for {@link PublicBugFishingPhase}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link PublicBugFishingPhase}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String failureReason;
        private @Nullable Double filesRead;
        private @Nullable String goal;
        private @Nullable Double manifestFiles;
        private @Nullable String phaseId;
        private @Nullable Double settledAt;
        private @Nullable PublicBugFishingPhaseStatus status;
        private @Nullable String summary;
        private @Nullable String territoryId;
        private @Nullable String territoryLabel;
        private @Nullable String title;

        /** Set {@code failureReason}. */
        public Builder failureReason(@Nullable String failureReason) {
            this.failureReason = failureReason;
            return this;
        }

        /** Set {@code filesRead}. */
        public Builder filesRead(@Nullable Double filesRead) {
            this.filesRead = filesRead;
            return this;
        }

        /** Set {@code goal}. */
        public Builder goal(@Nullable String goal) {
            this.goal = goal;
            return this;
        }

        /** Set {@code manifestFiles}. */
        public Builder manifestFiles(@Nullable Double manifestFiles) {
            this.manifestFiles = manifestFiles;
            return this;
        }

        /** Set {@code phaseId}. */
        public Builder phaseId(@Nullable String phaseId) {
            this.phaseId = phaseId;
            return this;
        }

        /** Set {@code settledAt}. */
        public Builder settledAt(@Nullable Double settledAt) {
            this.settledAt = settledAt;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable PublicBugFishingPhaseStatus status) {
            this.status = status;
            return this;
        }

        /** Set {@code summary}. */
        public Builder summary(@Nullable String summary) {
            this.summary = summary;
            return this;
        }

        /** Set {@code territoryId}. */
        public Builder territoryId(@Nullable String territoryId) {
            this.territoryId = territoryId;
            return this;
        }

        /** Set {@code territoryLabel}. */
        public Builder territoryLabel(@Nullable String territoryLabel) {
            this.territoryLabel = territoryLabel;
            return this;
        }

        /** Set {@code title}. */
        public Builder title(@Nullable String title) {
            this.title = title;
            return this;
        }

        /** Build the {@link PublicBugFishingPhase}. */
        public PublicBugFishingPhase build() {
            return new PublicBugFishingPhase(failureReason, filesRead, goal, manifestFiles, phaseId, settledAt, status, summary, territoryId, territoryLabel, title);
        }
    }
}
