// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for {@code repos().getFile()}.
 * A null parameter is not sent at all; the ones marked required above must be set, or the
 * deployment refuses the call.
 */
public record ReposGetFileQuery(
    /** Required: null is refused by the deployment with a 400 naming this parameter. */
    @Nullable String path,

    /** Null means "not sent". */
    @Nullable String ref
) {

    /**
     * The required parameters, with every optional one unset.
     * There is deliberately no empty factory on this record: the deployment refuses a call that
     * omits any parameter above, so an empty parameter set has no use that is not a bug.
     */
    public static ReposGetFileQuery of(String path) {
        return builder().path(path).build();
    }

    /** A new builder for {@link ReposGetFileQuery}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Render to the wire query map, omitting every unset parameter. */
    public Map<String, String> toQuery() {
        Map<String, String> out = new LinkedHashMap<>();
        if (path != null) {
            out.put("path", String.valueOf(path));
        }
        if (ref != null) {
            out.put("ref", String.valueOf(ref));
        }
        return out;
    }

    /** Fluent builder for {@link ReposGetFileQuery}. */
    public static final class Builder {
        private @Nullable String path;
        private @Nullable String ref;

        /** Set {@code path}. */
        public Builder path(@Nullable String path) {
            this.path = path;
            return this;
        }

        /** Set {@code ref}. */
        public Builder ref(@Nullable String ref) {
            this.ref = ref;
            return this;
        }

        /** Build the {@link ReposGetFileQuery}. */
        public ReposGetFileQuery build() {
            return new ReposGetFileQuery(path, ref);
        }
    }
}
