// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code RunPullRequest} wire model.
 * @param branch Always present; {@code null} when the server has no value for it.
 * @param url the {@code url} field.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record RunPullRequest(
    /** Always present; {@code null} when the server has no value for it. */
    @JsonProperty("branch") @Nullable String branch,

    @JsonProperty("url") String url
) {

    /** A new builder for {@link RunPullRequest}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link RunPullRequest}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String branch;
        private @Nullable String url;

        /** Set {@code branch}. */
        public Builder branch(@Nullable String branch) {
            this.branch = branch;
            return this;
        }

        /** Set {@code url}. */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /** Build the {@link RunPullRequest}. */
        public RunPullRequest build() {
            return new RunPullRequest(branch, url);
        }
    }
}
