// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code StartPublicRepoBootstrapRequest} wire model.
 * @param description May be absent entirely. Length 0..2000.
 * @param instructions May be absent entirely. Length 0..8000.
 * @param isPrivate May be absent entirely.
 * @param referenceArchitectureId May be absent entirely. Length 1..unbounded.
 * @param repoName Length 1..100.
 * @param type May be absent entirely.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record StartPublicRepoBootstrapRequest(
    /** May be absent entirely. Length 0..2000. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("description") @Nullable String description,

    /** May be absent entirely. Length 0..8000. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("instructions") @Nullable String instructions,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("private") @Nullable Boolean isPrivate,

    /** May be absent entirely. Length 1..unbounded. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("referenceArchitectureId") @Nullable String referenceArchitectureId,

    /** Length 1..100. */
    @JsonProperty("repoName") String repoName,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("type") @Nullable StartPublicRepoBootstrapRequestType type
) {

    /** A new builder for {@link StartPublicRepoBootstrapRequest}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link StartPublicRepoBootstrapRequest}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable String description;
        private @Nullable String instructions;
        private @Nullable Boolean isPrivate;
        private @Nullable String referenceArchitectureId;
        private @Nullable String repoName;
        private @Nullable StartPublicRepoBootstrapRequestType type;

        /** Set {@code description}. */
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        /** Set {@code instructions}. */
        public Builder instructions(@Nullable String instructions) {
            this.instructions = instructions;
            return this;
        }

        /** Set {@code private}. */
        public Builder isPrivate(@Nullable Boolean isPrivate) {
            this.isPrivate = isPrivate;
            return this;
        }

        /** Set {@code referenceArchitectureId}. */
        public Builder referenceArchitectureId(@Nullable String referenceArchitectureId) {
            this.referenceArchitectureId = referenceArchitectureId;
            return this;
        }

        /** Set {@code repoName}. */
        public Builder repoName(@Nullable String repoName) {
            this.repoName = repoName;
            return this;
        }

        /** Set {@code type}. */
        public Builder type(@Nullable StartPublicRepoBootstrapRequestType type) {
            this.type = type;
            return this;
        }

        /** Build the {@link StartPublicRepoBootstrapRequest}. */
        public StartPublicRepoBootstrapRequest build() {
            return new StartPublicRepoBootstrapRequest(description, instructions, isPrivate, referenceArchitectureId, repoName, type);
        }
    }
}
