// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for {@code tasks().stream()}.
 * Every parameter is optional; a null one is not sent at all.
 */
public record TasksStreamQuery(
    /** Set to `true` to add `decision-state` frames carrying the whole decision list for the run (the same payload `GET /api/v1/runs/{runId}/decisions` serves), pushed whenever it changes. This is how a chunked operation reports progress: a PR deep review slice count, a bug-fishing angle landing and a challenge verdict all move the decision list without moving the run, so they produce no `progress` frame. A value other than `true`, `false`, `1` or `0` is refused with `422 validation` (`details.reason: "invalid_query_parameter"`) rather than read as off. Null means "not sent". */
    @Nullable PublicStreamDecisionChannel decisions
) {

    /** An empty parameter set. */
    public static TasksStreamQuery none() {
        return builder().build();
    }

    /** A new builder for {@link TasksStreamQuery}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Render to the wire query map, omitting every unset parameter. */
    public Map<String, String> toQuery() {
        Map<String, String> out = new LinkedHashMap<>();
        if (decisions != null) {
            out.put("decisions", String.valueOf(decisions));
        }
        return out;
    }

    /** Fluent builder for {@link TasksStreamQuery}. */
    public static final class Builder {
        private @Nullable PublicStreamDecisionChannel decisions;

        /** Set {@code decisions}. */
        public Builder decisions(@Nullable PublicStreamDecisionChannel decisions) {
            this.decisions = decisions;
            return this;
        }

        /** Build the {@link TasksStreamQuery}. */
        public TasksStreamQuery build() {
            return new TasksStreamQuery(decisions);
        }
    }
}
