// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for {@code tasks().listByService()}.
 * Every parameter is optional; a null one is not sent at all.
 */
public record TasksListByServiceQuery(
    /** Null means "not sent". */
    @Nullable Integer limit,

    /** Null means "not sent". */
    @Nullable String cursor,

    /** Null means "not sent". */
    @Nullable TaskStatus status
) {

    /** An empty parameter set. */
    public static TasksListByServiceQuery none() {
        return builder().build();
    }

    /** A new builder for {@link TasksListByServiceQuery}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Render to the wire query map, omitting every unset parameter. */
    public Map<String, String> toQuery() {
        Map<String, String> out = new LinkedHashMap<>();
        if (limit != null) {
            out.put("limit", String.valueOf(limit));
        }
        if (cursor != null) {
            out.put("cursor", String.valueOf(cursor));
        }
        if (status != null) {
            out.put("status", String.valueOf(status));
        }
        return out;
    }

    /** Fluent builder for {@link TasksListByServiceQuery}. */
    public static final class Builder {
        private @Nullable Integer limit;
        private @Nullable String cursor;
        private @Nullable TaskStatus status;

        /** Set {@code limit}. */
        public Builder limit(@Nullable Integer limit) {
            this.limit = limit;
            return this;
        }

        /** Set {@code cursor}. */
        public Builder cursor(@Nullable String cursor) {
            this.cursor = cursor;
            return this;
        }

        /** Set {@code status}. */
        public Builder status(@Nullable TaskStatus status) {
            this.status = status;
            return this;
        }

        /** Build the {@link TasksListByServiceQuery}. */
        public TasksListByServiceQuery build() {
            return new TasksListByServiceQuery(limit, cursor, status);
        }
    }
}
