// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The {@code UpdatePublicTrackerWritebackRequestWriteback} wire model.
 * @param commentOnPrOpen May be absent entirely.
 * @param questionsOnPark May be absent entirely.
 * @param resolveOnMerge May be absent entirely.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record UpdatePublicTrackerWritebackRequestWriteback(
    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("commentOnPrOpen") @Nullable Boolean commentOnPrOpen,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("questionsOnPark") @Nullable Boolean questionsOnPark,

    /** May be absent entirely. */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("resolveOnMerge") @Nullable Boolean resolveOnMerge
) {

    /** A new builder for {@link UpdatePublicTrackerWritebackRequestWriteback}. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for {@link UpdatePublicTrackerWritebackRequestWriteback}.
     * Every setter is nullable so a caller supplies only what it means to send. Java has no
     * default arguments and Kotlin cannot synthesise them for a Java constructor, so this is the
     * shape that reads naturally from both languages.
     */
    public static final class Builder {
        private @Nullable Boolean commentOnPrOpen;
        private @Nullable Boolean questionsOnPark;
        private @Nullable Boolean resolveOnMerge;

        /** Set {@code commentOnPrOpen}. */
        public Builder commentOnPrOpen(@Nullable Boolean commentOnPrOpen) {
            this.commentOnPrOpen = commentOnPrOpen;
            return this;
        }

        /** Set {@code questionsOnPark}. */
        public Builder questionsOnPark(@Nullable Boolean questionsOnPark) {
            this.questionsOnPark = questionsOnPark;
            return this;
        }

        /** Set {@code resolveOnMerge}. */
        public Builder resolveOnMerge(@Nullable Boolean resolveOnMerge) {
            this.resolveOnMerge = resolveOnMerge;
            return this;
        }

        /** Build the {@link UpdatePublicTrackerWritebackRequestWriteback}. */
        public UpdatePublicTrackerWritebackRequestWriteback build() {
            return new UpdatePublicTrackerWritebackRequestWriteback(commentOnPrOpen, questionsOnPark, resolveOnMerge);
        }
    }
}
