// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.model;

import java.util.LinkedHashMap;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Query parameters for {@code usage().spend()}.
 * A null parameter is not sent at all; the ones marked required above must be set, or the
 * deployment refuses the call.
 */
public record UsageSpendQuery(
    /** Required: null is refused by the deployment with a 400 naming this parameter. */
    @Nullable PublicSpendDimension dimension,

    /** Null means "not sent". */
    @Nullable PublicSpendWindow window,

    /** Null means "not sent". */
    @Nullable Integer limit
) {

    /**
     * The required parameters, with every optional one unset.
     * There is deliberately no empty factory on this record: the deployment refuses a call that
     * omits any parameter above, so an empty parameter set has no use that is not a bug.
     */
    public static UsageSpendQuery of(PublicSpendDimension dimension) {
        return builder().dimension(dimension).build();
    }

    /** A new builder for {@link UsageSpendQuery}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Render to the wire query map, omitting every unset parameter. */
    public Map<String, String> toQuery() {
        Map<String, String> out = new LinkedHashMap<>();
        if (dimension != null) {
            out.put("dimension", String.valueOf(dimension));
        }
        if (window != null) {
            out.put("window", String.valueOf(window));
        }
        if (limit != null) {
            out.put("limit", String.valueOf(limit));
        }
        return out;
    }

    /** Fluent builder for {@link UsageSpendQuery}. */
    public static final class Builder {
        private @Nullable PublicSpendDimension dimension;
        private @Nullable PublicSpendWindow window;
        private @Nullable Integer limit;

        /** Set {@code dimension}. */
        public Builder dimension(@Nullable PublicSpendDimension dimension) {
            this.dimension = dimension;
            return this;
        }

        /** Set {@code window}. */
        public Builder window(@Nullable PublicSpendWindow window) {
            this.window = window;
            return this;
        }

        /** Set {@code limit}. */
        public Builder limit(@Nullable Integer limit) {
            this.limit = limit;
            return this;
        }

        /** Build the {@link UsageSpendQuery}. */
        public UsageSpendQuery build() {
            return new UsageSpendQuery(dimension, window, limit);
        }
    }
}
