import { nativeModelSummary } from './execution.js'
import {
  CONTAINER_RUNTIMES,
  type ContainerRuntime,
  type ExecutionMode,
  HARNESS_IMAGE_EXAMPLE,
  HARNESS_IMAGE_GUIDANCE,
  NATIVE_HARNESSES,
  type NativeHarness,
} from './templates.js'
import { patEnvVar, providerLabel, type VcsProvider } from './vcs.js'

/** One line of an `.env` file: a key/value pair with an optional leading comment block. */
export interface EnvEntry {
  key: string
  value: string
  /** Comment lines rendered (each prefixed with `# `) immediately above the entry. */
  comment?: string[]
}

/**
 * Render a list of {@link EnvEntry} into `.env` file text. Comments are emitted above their
 * entry; entries are separated by a blank line for readability. The output always ends with a
 * trailing newline.
 */
export function renderEnvFile(entries: EnvEntry[]): string {
  const blocks = entries.map((entry) => {
    const comment = (entry.comment ?? []).map((line) => `# ${line}`)
    return [...comment, `${entry.key}=${entry.value}`].join('\n')
  })
  return `${blocks.join('\n\n')}\n`
}

/** Inputs that flow into the local-backend `.env`. */
export interface LocalEnvInput {
  databaseUrl: string
  authSessionSecret: string
  encryptionKey: string
  /** Shared HMAC secret between the backend and the executor-harness (`HARNESS_SHARED_SECRET`). */
  harnessSharedSecret: string
  /**
   * An explicit harness-image pin. Normally UNSET — `LOCAL_HARNESS_IMAGE` is then written
   * commented-out so the backend runs its matched version; a value here is written active
   * because the developer deliberately chose to lock to it (e.g. testing/hotfix).
   */
  harnessImage?: string
  port: number
  corsAllowedOrigins: string
  provider: VcsProvider
  /** Container runtime that spawns agent jobs (`LOCAL_CONTAINER_RUNTIME`). */
  containerRuntime: ContainerRuntime
  /** How agent jobs execute: a Docker container pool (default) or native host agents. */
  executionMode?: ExecutionMode
  /** Native mode only: the subscription harnesses to run as host processes. */
  nativeHarnesses?: NativeHarness[]
  /** Native mode only: the executor-harness server entry path (`LOCAL_HARNESS_ENTRY`). */
  harnessEntry?: string
  /** The pasted PAT, or empty/undefined to leave the var present-but-blank. */
  token?: string
}

/** Build the local-mode backend `.env` (`@cat-factory/local-server`). */
export function buildLocalEnv(input: LocalEnvInput): string {
  const tokenVar = patEnvVar(input.provider)
  const label = providerLabel(input.provider)
  const entries: EnvEntry[] = [
    {
      comment: [
        'Local-mode backend (@cat-factory/local-server). Generated by the cat-factory CLI.',
        'This file is gitignored — it holds secrets. Keep the generated values STABLE.',
        'Postgres connection string (matches the bundled docker-compose.yml).',
      ],
      key: 'DATABASE_URL',
      value: input.databaseUrl,
    },
    {
      comment: ['HTTP listen port for the backend API.'],
      key: 'PORT',
      value: String(input.port),
    },
    {
      comment: ["Allowed CORS origin(s) — the frontend SPA's dev origin."],
      key: 'CORS_ALLOWED_ORIGINS',
      value: input.corsAllowedOrigins,
    },
    {
      comment: [
        'Signs the session JWT (>= 32 chars). Regenerating forces a re-login — keep it stable.',
      ],
      key: 'AUTH_SESSION_SECRET',
      value: input.authSessionSecret,
    },
    {
      comment: [
        'Master key sealing every credential at rest (base64, >= 32 decoded bytes).',
        'Regenerating ORPHANS every encrypted credential — keep it stable.',
      ],
      key: 'ENCRYPTION_KEY',
      value: input.encryptionKey,
    },
    {
      comment: [
        'Shared HMAC secret signing traffic between the backend and the executor-harness',
        '(>= 16 chars). Required to boot; keep it stable.',
      ],
      key: 'HARNESS_SHARED_SECRET',
      value: input.harnessSharedSecret,
    },
    {
      comment: [
        `${label} personal access token. Agent containers clone/push/open PRs with it.`,
        'Minted by the CLI with the right scopes pre-selected; paste-replace to rotate.',
      ],
      key: tokenVar,
      value: input.token ?? '',
    },
    // Unset by default: written commented-out so the backend runs its matched version. Only an
    // explicit --harness-image pin makes this active (see HARNESS_IMAGE_GUIDANCE).
    {
      comment: [...HARNESS_IMAGE_GUIDANCE],
      key: input.harnessImage ? 'LOCAL_HARNESS_IMAGE' : '# LOCAL_HARNESS_IMAGE',
      value: input.harnessImage ?? HARNESS_IMAGE_EXAMPLE,
    },
    {
      comment: [`Container runtime used to spawn agent jobs: ${CONTAINER_RUNTIMES.join(' | ')}.`],
      key: 'LOCAL_CONTAINER_RUNTIME',
      value: input.containerRuntime,
    },
    ...reachabilityEntries(input.containerRuntime),
    ...executionModeEntries(input),
    ...deployRunnerEntries(),
    ...commonOptionalEntries(input.provider),
    {
      comment: [
        'At least one model provider must be configured or no model is selectable.',
        'Cloudflare Workers AI over REST is the simplest: set both, then uncomment.',
        'See the README for minting a token + finding your account id.',
      ],
      key: '# CLOUDFLARE_ACCOUNT_ID',
      value: '',
    },
    { key: '# CLOUDFLARE_API_TOKEN', value: '' },
    {
      comment: ['Or a direct vendor key (combinable with the above):'],
      key: '# ANTHROPIC_API_KEY',
      value: '',
    },
    { key: '# OPENAI_API_KEY', value: '' },
  ]
  return renderEnvFile(entries)
}

/**
 * Execution-mode entries: PREWARMED DOCKER POOL (default) or NATIVE host agents. In pool
 * mode the native knobs are written commented (advertising the alternative) plus a pointer
 * to the UI-configured warm pool with recommended sizing. In native mode `LOCAL_NATIVE_AGENTS`
 * is written active, annotated with the models that actually run natively (every other step
 * still runs in a container, so LOCAL_HARNESS_IMAGE stays needed); `LOCAL_HARNESS_ENTRY` is
 * written only when an explicit path was given, else left commented (it defaults to the
 * bundled `@cat-factory/executor-harness`).
 */
function executionModeEntries(input: LocalEnvInput): EnvEntry[] {
  if (input.executionMode === 'native') {
    const harnesses = input.nativeHarnesses?.length ? input.nativeHarnesses : [...NATIVE_HARNESSES]
    return [
      {
        comment: [
          'Execution mode: NATIVE host agents (chosen). A step whose model maps to a native',
          'vendor runs as a HOST PROCESS driving your OWN installed CLI (ambient login) — no',
          'container, no leased credential, NO sandbox (full host access + your subscription).',
          `Runs natively: ${nativeModelSummary(harnesses)}.`,
          'Every OTHER step (Cloudflare/proxy models, and GLM/Kimi/DeepSeek which reuse the',
          'claude-code harness against their own endpoint) still runs in a container, so',
          'LOCAL_HARNESS_IMAGE above is still required. The named CLIs must already be',
          'installed and logged in on this host.',
        ],
        key: 'LOCAL_NATIVE_AGENTS',
        value: harnesses.join(','),
      },
      input.harnessEntry
        ? {
            comment: [
              'Executor-harness server entry (custom, from --harness-entry). Optional in general:',
              'it defaults to the bundled @cat-factory/executor-harness; set here because you',
              'passed an explicit path.',
            ],
            key: 'LOCAL_HARNESS_ENTRY',
            value: input.harnessEntry,
          }
        : {
            comment: [
              'Optional: the executor-harness server entry run as the host process. Defaults to',
              'the bundled @cat-factory/executor-harness (ships with local-server), so native mode',
              'works out of the box. Uncomment only to point at a custom or source-checkout build.',
            ],
            key: '# LOCAL_HARNESS_ENTRY',
            value: '',
          },
    ]
  }
  return [
    {
      comment: [
        'Execution mode: PREWARMED DOCKER POOL (chosen). Agent jobs run in per-run containers',
        'from LOCAL_HARNESS_IMAGE above via LOCAL_CONTAINER_RUNTIME. Warm-pool sizing (keep N',
        'containers ready so runs start fast) lives in the DB, edited in the UI under',
        'Integrations > "Local mode". Off by default (cold-start per run); recommended to start:',
        'size 3, pre-warm 1, idle timeout 10m.',
        '',
        'To switch to NATIVE host agents instead (your own installed claude/codex CLI — no',
        'container, no leased credential), set LOCAL_NATIVE_AGENTS (e.g. claude-code,codex). The',
        'harness server entry defaults to the bundled @cat-factory/executor-harness, so no other',
        'setting is needed. Only Claude/ChatGPT models go native; every other model still uses',
        'the container path above.',
      ],
      key: '# LOCAL_NATIVE_AGENTS',
      value: '',
    },
    { key: '# LOCAL_HARNESS_ENTRY', value: '' },
  ]
}

/**
 * The Kubernetes test-environment DEPLOY RUNNER, all commented out (deploy is unused by default).
 * A Kubernetes-backed test environment (local k3s/k3d/kind, configured in the UI or via
 * `cat-factory k3s`) needs a deploy runner to render + apply its manifests; the UI connection says
 * WHERE to deploy, these say WHAT runs it. There is NO default MODE, and none is written active —
 * but `container` mode now works with no other variable (the deploy-harness image resolves
 * automatically, like the executor image), so enabling deploy is a one-line uncomment. We document
 * both modes and steer to `container`. Mirrors `deploy/local/.env.example`.
 */
function deployRunnerEntries(): EnvEntry[] {
  return [
    {
      comment: [
        'Kubernetes test environments — the DEPLOY RUNNER (optional, unused by default). A test',
        'environment backed by Kubernetes (local k3s/k3d/kind, set up in the UI under Integrations >',
        '"Test environments" or with `cat-factory k3s`) needs a deploy runner to render + apply its',
        'manifests with kubectl/kustomize/helm — WITHOUT one, standing it up fails with "no deploy',
        'runner wired". That connection says WHERE to deploy; these say WHAT runs the deploy. Pick a',
        'mode explicitly (no default). Leave unset (the common case) if you do not stand Kubernetes',
        'test environments up.',
        '  container — RECOMMENDED, works out of the box: the deploy-harness IMAGE runs one container',
        '              per job on LOCAL_CONTAINER_RUNTIME. The image is resolved automatically to the',
        '              version this backend supports — no other variable needed. Just uncomment this.',
        '  native    — a HOST PROCESS using your OWN installed kubectl/kustomize/helm (no Docker);',
        '              requires LOCAL_DEPLOY_HARNESS_ENTRY (boot FAILS if set without it). Runs with',
        '              your full cluster + file access.',
      ],
      key: '# LOCAL_DEPLOY_RUNTIME',
      value: 'container',
    },
    {
      comment: [
        'Required only when LOCAL_DEPLOY_RUNTIME=native (the deploy-harness server entry).',
      ],
      key: '# LOCAL_DEPLOY_HARNESS_ENTRY',
      value: '',
    },
    {
      comment: [
        'Escape hatch only: pin a custom/older deploy-harness image or a private-registry mirror.',
        'Leave unset to use the backend-matched default (recommended).',
      ],
      key: '# LOCAL_DEPLOY_IMAGE',
      value: 'ghcr.io/kibertoad/cat-factory-deploy:<version>',
    },
  ]
}

/**
 * Commonly-useful optional settings, all commented out so a developer can toggle them in place
 * instead of hunting the docs. NOTE: these are shown with the value you'd set to change the
 * behaviour, which is NOT always the default — the auth pair below is on by default in local
 * mode, but tracing/Slack/consensus are opt-in (off) and image-refresh is on by default. Each
 * comment states the actual default. Mirrors the opt-in knobs in `deploy/local/.env.example`.
 */
function commonOptionalEntries(provider: VcsProvider): EnvEntry[] {
  const entries: EnvEntry[] = [
    {
      comment: [
        'Email/password sign-in + open signup. Both are ON by default in local mode (the values',
        'shown are the defaults) — uncomment and set to false to require an invite / disable it.',
      ],
      key: '# AUTH_PASSWORD_ENABLED',
      value: 'true',
    },
    { key: '# AUTH_OPEN_SIGNUP', value: 'true' },
    {
      comment: [
        'Boot-time harness image refresh (pull the backend-matched image on start). ON by',
        'default; the value shown DISABLES it — uncomment when offline or you manage the image',
        'yourself.',
      ],
      key: '# LOCAL_HARNESS_IMAGE_REFRESH',
      value: 'off',
    },
    {
      comment: [
        'Stream every LLM call to Langfuse. OFF by default; the value shown ENABLES it (also',
        'needs both keys below).',
      ],
      key: '# LANGFUSE_ENABLED',
      value: 'true',
    },
    { key: '# LANGFUSE_PUBLIC_KEY', value: '' },
    { key: '# LANGFUSE_SECRET_KEY', value: '' },
    {
      comment: [
        'Export every LLM call (traces + metrics) to an OpenTelemetry OTLP/HTTP backend',
        '(Grafana, Honeycomb, an OTel Collector, …). OFF by default; the value shown ENABLES',
        'it (also needs the endpoint below). Composes alongside Langfuse.',
      ],
      key: '# OTEL_ENABLED',
      value: 'true',
    },
    { key: '# OTEL_EXPORTER_OTLP_ENDPOINT', value: 'http://localhost:4318' },
    {
      comment: ['Optional OTLP auth headers: comma-separated key=value pairs.'],
      key: '# OTEL_EXPORTER_OTLP_HEADERS',
      value: '',
    },
    { key: '# OTEL_SERVICE_NAME', value: 'cat-factory' },
    {
      comment: [
        'Post board notifications to Slack (connect the workspace in the UI). OFF by default;',
        'the value shown ENABLES it.',
      ],
      key: '# SLACK_ENABLED',
      value: 'true',
    },
    {
      comment: [
        'Multi-model consensus (specialist panel / debate / ranked voting) on eligible steps.',
        'OFF by default; the value shown ENABLES it.',
      ],
      key: '# CONSENSUS_ENABLED',
      value: 'true',
    },
  ]
  if (provider === 'gitlab') {
    entries.push({
      comment: [
        'Self-managed GitLab only: point at your instance API (e.g. https://gitlab.example.com/api/v4).',
      ],
      key: '# GITLAB_API_BASE',
      value: '',
    })
  }
  return entries
}

/**
 * Container→host reachability + security hints, commented out (sensible defaults apply). Agent
 * job containers reach this service's LLM proxy over the network, and how they address the host
 * differs per runtime — surfacing the knobs here (rather than only in the upstream docs) means a
 * developer who hits "proxy unreachable from the container" has the fix in the file they already
 * have open. Mirrors the relevant slice of `deploy/local/.env.example`.
 */
function reachabilityEntries(runtime: ContainerRuntime): EnvEntry[] {
  const entries: EnvEntry[] = [
    {
      comment: [
        'Container -> host reachability (defaults apply; uncomment only if the agent container',
        "can't reach this service's LLM proxy). The harness reaches the host at a per-runtime",
        'alias: host.docker.internal (docker/podman/orbstack), host.lima.internal (colima), the',
        'vmnet gateway (apple). On Colima/Apple this is often unreachable — set it to your LAN IP.',
      ],
      key: '# LOCAL_HARNESS_HOST_ALIAS',
      value: '',
    },
  ]
  if (runtime === 'docker' || runtime === 'podman') {
    entries.push({
      comment: [
        'Native Linux Docker only: add --add-host=<alias>:host-gateway so the container can',
        'resolve the host (needed on Linux; harmless on Docker Desktop/OrbStack).',
      ],
      key: '# LOCAL_DOCKER_ADD_HOST_GATEWAY',
      value: 'true',
    })
  }
  entries.push({
    comment: [
      'SECURITY: with the dev gate open the server binds all interfaces so job containers can',
      'reach the proxy. To lock it down, bind to loopback (works on Docker Desktop; NOT native',
      'Linux Docker, where containers need the bridge gateway) or close the gate.',
      'HOST=127.0.0.1',
    ],
    key: '# AUTH_DEV_OPEN',
    value: 'false',
  })
  return entries
}

/** Inputs that flow into the frontend `.env`. */
export interface FrontendEnvInput {
  apiBase: string
}

/** Build the frontend SPA `.env` (`@cat-factory/app` consumer). */
export function buildFrontendEnv(input: FrontendEnvInput): string {
  return renderEnvFile([
    {
      comment: [
        'Frontend SPA (extends @cat-factory/app). Generated by `cat-factory init`.',
        'Base URL of the backend API. Baked in at build time (the SPA is ssr: false).',
      ],
      key: 'NUXT_PUBLIC_API_BASE',
      value: input.apiBase,
    },
  ])
}
