import { CONTAINER_RUNTIMES, type ContainerRuntime } from './templates.js'
import { patEnvVar, providerLabel, type VcsProvider } from './vcs.js'

/** One line of an `.env` file: a key/value pair with an optional leading comment block. */
export interface EnvEntry {
  key: string
  value: string
  /** Comment lines rendered (each prefixed with `# `) immediately above the entry. */
  comment?: string[]
}

/**
 * Render a list of {@link EnvEntry} into `.env` file text. Comments are emitted above their
 * entry; entries are separated by a blank line for readability. The output always ends with a
 * trailing newline.
 */
export function renderEnvFile(entries: EnvEntry[]): string {
  const blocks = entries.map((entry) => {
    const comment = (entry.comment ?? []).map((line) => `# ${line}`)
    return [...comment, `${entry.key}=${entry.value}`].join('\n')
  })
  return `${blocks.join('\n\n')}\n`
}

/** Inputs that flow into the local-backend `.env`. */
export interface LocalEnvInput {
  databaseUrl: string
  authSessionSecret: string
  encryptionKey: string
  harnessImage: string
  port: number
  corsAllowedOrigins: string
  provider: VcsProvider
  /** Container runtime that spawns agent jobs (`LOCAL_CONTAINER_RUNTIME`). */
  containerRuntime: ContainerRuntime
  /** The pasted PAT, or empty/undefined to leave the var present-but-blank. */
  token?: string
}

/** Build the local-mode backend `.env` (`@cat-factory/local-server`). */
export function buildLocalEnv(input: LocalEnvInput): string {
  const tokenVar = patEnvVar(input.provider)
  const label = providerLabel(input.provider)
  const entries: EnvEntry[] = [
    {
      comment: [
        'Local-mode backend (@cat-factory/local-server). Generated by `cat-factory init`.',
        'This file is gitignored — it holds secrets. Keep the generated values STABLE.',
        'Postgres connection string (matches the bundled docker-compose.yml).',
      ],
      key: 'DATABASE_URL',
      value: input.databaseUrl,
    },
    {
      comment: ['HTTP listen port for the backend API.'],
      key: 'PORT',
      value: String(input.port),
    },
    {
      comment: ["Allowed CORS origin(s) — the frontend SPA's dev origin."],
      key: 'CORS_ALLOWED_ORIGINS',
      value: input.corsAllowedOrigins,
    },
    {
      comment: [
        'Signs the session JWT (>= 32 chars). Regenerating forces a re-login — keep it stable.',
      ],
      key: 'AUTH_SESSION_SECRET',
      value: input.authSessionSecret,
    },
    {
      comment: [
        'Master key sealing every credential at rest (base64, >= 32 decoded bytes).',
        'Regenerating ORPHANS every encrypted credential — keep it stable.',
      ],
      key: 'ENCRYPTION_KEY',
      value: input.encryptionKey,
    },
    {
      comment: [
        `${label} personal access token. Agent containers clone/push/open PRs with it.`,
        'Minted by the CLI with the right scopes pre-selected; paste-replace to rotate.',
      ],
      key: tokenVar,
      value: input.token ?? '',
    },
    {
      comment: [
        'The executor-harness image agent jobs run as per-run containers.',
        'Pull it first: docker pull ghcr.io/kibertoad/cat-factory-executor:latest',
      ],
      key: 'LOCAL_HARNESS_IMAGE',
      value: input.harnessImage,
    },
    {
      comment: [`Container runtime used to spawn agent jobs: ${CONTAINER_RUNTIMES.join(' | ')}.`],
      key: 'LOCAL_CONTAINER_RUNTIME',
      value: input.containerRuntime,
    },
    ...reachabilityEntries(input.containerRuntime),
    {
      comment: [
        'At least one model provider must be configured or no model is selectable.',
        'Cloudflare Workers AI over REST is the simplest: set both, then uncomment.',
        'See the README for minting a token + finding your account id.',
      ],
      key: '# CLOUDFLARE_ACCOUNT_ID',
      value: '',
    },
    { key: '# CLOUDFLARE_API_TOKEN', value: '' },
    {
      comment: ['Or a direct vendor key (combinable with the above):'],
      key: '# ANTHROPIC_API_KEY',
      value: '',
    },
    { key: '# OPENAI_API_KEY', value: '' },
  ]
  return renderEnvFile(entries)
}

/**
 * Container→host reachability + security hints, commented out (sensible defaults apply). Agent
 * job containers reach this service's LLM proxy over the network, and how they address the host
 * differs per runtime — surfacing the knobs here (rather than only in the upstream docs) means a
 * developer who hits "proxy unreachable from the container" has the fix in the file they already
 * have open. Mirrors the relevant slice of `deploy/local/.env.example`.
 */
function reachabilityEntries(runtime: ContainerRuntime): EnvEntry[] {
  const entries: EnvEntry[] = [
    {
      comment: [
        'Container -> host reachability (defaults apply; uncomment only if the agent container',
        "can't reach this service's LLM proxy). The harness reaches the host at a per-runtime",
        'alias: host.docker.internal (docker/podman/orbstack), host.lima.internal (colima), the',
        'vmnet gateway (apple). On Colima/Apple this is often unreachable — set it to your LAN IP.',
      ],
      key: '# LOCAL_HARNESS_HOST_ALIAS',
      value: '',
    },
  ]
  if (runtime === 'docker' || runtime === 'podman') {
    entries.push({
      comment: [
        'Native Linux Docker only: add --add-host=<alias>:host-gateway so the container can',
        'resolve the host (needed on Linux; harmless on Docker Desktop/OrbStack).',
      ],
      key: '# LOCAL_DOCKER_ADD_HOST_GATEWAY',
      value: 'true',
    })
  }
  entries.push({
    comment: [
      'SECURITY: with the dev gate open the server binds all interfaces so job containers can',
      'reach the proxy. To lock it down, bind to loopback (works on Docker Desktop; NOT native',
      'Linux Docker, where containers need the bridge gateway) or close the gate.',
      'HOST=127.0.0.1',
    ],
    key: '# AUTH_DEV_OPEN',
    value: 'false',
  })
  return entries
}

/** Inputs that flow into the frontend `.env`. */
export interface FrontendEnvInput {
  apiBase: string
}

/** Build the frontend SPA `.env` (`@cat-factory/app` consumer). */
export function buildFrontendEnv(input: FrontendEnvInput): string {
  return renderEnvFile([
    {
      comment: [
        'Frontend SPA (extends @cat-factory/app). Generated by `cat-factory init`.',
        'Base URL of the backend API. Baked in at build time (the SPA is ssr: false).',
      ],
      key: 'NUXT_PUBLIC_API_BASE',
      value: input.apiBase,
    },
  ])
}
