// The domain works directly with the wire entity types defined once in
// @cat-factory/contracts. Re-exported here so the rest of the core imports its
// vocabulary from a single place (`../domain/types`) rather than reaching into
// the contracts package everywhere.
export type {
  AgentKind,
  AgentState,
  AgentFailure,
  AgentFailureKind,
  AgentRunKind,
  Block,
  BlockLevel,
  BlockStatus,
  BlockType,
  TaskType,
  CreateTaskType,
  TaskTypeFields,
  DocKind,
  Decision,
  ExecutionInstance,
  ExecutionStatus,
  Pipeline,
  PipelineStep,
  Position,
  PromptFragment,
  PullRequestRef,
  SpendStatus,
  StepApproval,
  StepReviewComment,
  StepSubtasks,
  Workspace,
  WorkspaceSnapshot,
  // Prompt-fragment library shapes (ADR 0006).
  FragmentOwnerKind,
  FragmentTier,
  CreatePromptFragmentInput,
  CreateDocumentFragmentInput,
  UpdatePromptFragmentInput,
  FragmentSource,
  LinkFragmentSourceInput,
  FragmentSyncResult,
  FragmentSourceStatus,
  ResolvedFragment,
  ResolvedFragmentCatalog,
  // Account tenancy shapes.
  Account,
  AccountType,
  AccountRole,
  AccountMember,
  CreateAccountInput,
  AddMemberInput,
  // In-org shared services (account-owned services + per-workspace mounts).
  Service,
  WorkspaceMount,
  MountServiceInput,
  UpdateMountInput,
  // GitHub integration projections + I/O shapes.
  GitHubBranch,
  GitHubCheckRun,
  GitHubCommit,
  GitHubConnection,
  GitHubInstallationOption,
  GitHubAvailableRepo,
  GitHubIssue,
  GitHubIssueState,
  GitHubPullRequest,
  GitHubPullRequestState,
  GitHubRepo,
  RepoTreeEntry,
  SetRepoMonorepoInput,
  CommitFilesInput,
  LinkReposInput,
  OpenPullRequestInput,
  MergePullRequestInput,
  // Shared provider self-description + connection-test shapes.
  ProviderConfigFieldType,
  ProviderConfigField,
  ProviderDescriptor,
  ConnectionTestResult,
  // Per-user secret (generic, kind-discriminated) shapes.
  UserSecretKind,
  UserSecretStatus,
  StoreUserSecretInput,
  TestUserSecretInput,
  UserSecretDescriptor,
  // Document-source integration projections + planning shapes.
  DocumentSourceKind,
  DocumentSourceDescriptor,
  CredentialField,
  DocumentConnection,
  SourceDocument,
  DocumentSearchResult,
  DocumentBoardPlan,
  PlanFrame,
  PlanModule,
  PlanTask,
  // Task-source integration projections + I/O shapes.
  TaskSourceKind,
  TaskSourceDescriptor,
  TaskSourceState,
  TaskSourceDiagnostic,
  TaskSourceDiagnosticStatus,
  TaskConnection,
  TaskComment,
  TaskDependencyLink,
  SourceTask,
  TaskSearchResult,
  // Ephemeral environment provider shapes.
  EnvironmentSecretRef,
  EnvironmentAuthScheme,
  EnvironmentHttpMethod,
  EnvironmentRequestTemplate,
  EnvironmentStatus,
  EnvironmentAccessScheme,
  EnvironmentAccessMapping,
  EnvironmentResponseMapping,
  EnvironmentManifest,
  EnvironmentAccessHandle,
  EnvironmentHandle,
  EnvironmentConnection,
  TestEnvironmentConnectionInput,
  ValidateEnvironmentRepoInput,
  BootstrapEnvironmentRepoInput,
  BootstrapRepoResult,
  // Unified provisioning event-log shapes.
  ProvisioningSubsystem,
  ProvisioningOperation,
  ProvisioningOutcome,
  ProvisioningLogEntry,
  // Self-hosted runner-pool ("bring your own infra") shapes.
  RunnerPoolSecretRef,
  RunnerPoolAuthScheme,
  RunnerPoolRequestTemplate,
  RunnerJobState,
  RunnerPoolResponseMapping,
  RunnerPoolManifest,
  RunnerPoolConnection,
  TestRunnerPoolConnectionInput,
  // Repo-bootstrap shapes.
  ReferenceArchitecture,
  CreateReferenceArchitectureInput,
  UpdateReferenceArchitectureInput,
  BootstrapStatus,
  BootstrapFailure,
  BootstrapFailureKind,
  BootstrapJob,
  BootstrapRepoInput,
  // Service-blueprint (repository decomposition) shapes — produced by the
  // `blueprints` pipeline step and reconciled onto the board.
  BlueprintModule,
  BlueprintService,
  BlueprintSource,
  BoardScanSpawnResult,
  // Requirements-review (stateless context reviewer agent) shapes.
  ReviewItemCategory,
  ReviewItemSeverity,
  ReviewItemStatus,
  RequirementReviewItem,
  RequirementReviewStatus,
  RequirementReview,
  // Kaizen (post-run grading agent) shapes.
  KaizenGradingStatus,
  KaizenGrading,
  KaizenVerifiedCombo,
  KaizenOverview,
  KaizenRunGradings,
  RecommendationStatus,
  RequirementRecommendation,
  ReplyReviewItemInput,
  UpdateReviewItemStatusInput,
  IncorporateRequirementsInput,
  RequestRecommendationsInput,
  ReRequestRecommendationInput,
  ResolveRequirementsExceededInput,
  ResolveRequirementsExceededChoice,
  // Follow-up companion (future-looking Coder) shapes: surfaced loose-end / question items
  // + the live step state the engine parks/loops on.
  FollowUpItemKind,
  FollowUpItemStatus,
  FollowUpItem,
  FollowUpsStepState,
  AnswerFollowUpInput,
  StreamedFollowUp,
  // Clarity-review (bug-report triage reviewer agent) shapes — reuse the requirements
  // review item/status shapes, differ only in subject + the persisted document field.
  ClarityReviewItem,
  ClarityReviewStatus,
  ClarityReview,
  ReplyClarityItemInput,
  UpdateClarityItemStatusInput,
  IncorporateClarityInput,
  ResolveClarityExceededInput,
  ResolveClarityExceededChoice,
  // Brainstorm (structured-dialogue agent) shapes — reuse the requirements review
  // item/status shapes, differ in the `stage` discriminator + the converged-direction doc.
  BrainstormStage,
  BrainstormItem,
  BrainstormStatus,
  BrainstormSession,
  ReplyBrainstormItemInput,
  UpdateBrainstormItemStatusInput,
  IncorporateBrainstormInput,
  ResolveBrainstormExceededInput,
  ResolveBrainstormExceededChoice,
  // Shared iterative-gate cap resolution (requirements reviewer + quality companions).
  IterationCapChoice,
  ResolveIterationCapInput,
  // Structured in-repo specification (sharded module → group tree) shapes.
  RequirementPriority,
  RequirementKind,
  AcceptanceCriterion,
  RequirementItem,
  DomainRule,
  RequirementGroup,
  SpecModule,
  SpecDoc,
  // Companion-agent shapes: the raw model assessment + the standardized stored verdict.
  CompanionAssessment,
  CompanionVerdict,
  // Gate (ci/conflicts) / merge-policy shapes.
  GateStepState,
  GateFailingCheck,
  GateAttempt,
  // Human-testing gate shapes (ephemeral env + human validation loop).
  HumanTestStepState,
  HumanTestEnvironment,
  HumanTestRound,
  RequestHumanTestFixInput,
  // Visual-confirmation gate shapes (screenshot review + fix loop).
  VisualConfirmStepState,
  VisualConfirmPair,
  VisualConfirmRound,
  MergeAssessment,
  MergeThresholdPreset,
  RequirementConcernLevel,
  CreateMergePresetInput,
  UpdateMergePresetInput,
  // Consensus-orchestration shapes (optional `@cat-factory/consensus` mechanism)
  // + the core task-estimator triage that gates it.
  ConsensusStrategy,
  ConsensusParticipant,
  ConsensusGating,
  StepGating,
  ConsensusStepConfig,
  TaskEstimate,
  ConsensusScore,
  ConsensusContribution,
  ConsensusRound,
  ConsensusSessionStatus,
  ConsensusSession,
  // Agent config-contribution shapes.
  AgentConfigOption,
  AgentConfigDescriptor,
  AgentConfigCatalog,
  AgentConfigValues,
  // Tester / Fixer structured-report shapes.
  TestReport,
  TestOutcome,
  TestConcern,
  TestConcernSeverity,
  // Container provisioning vocabulary.
  CloudProvider,
  InstanceSize,
  UpdateAccountInput,
  // Per-workspace model presets (named model→agent mappings; a task picks one).
  ModelPreset,
  CreateModelPresetInput,
  UpdateModelPresetInput,
  // Per-workspace default service-fragment selection (new services inherit it).
  ServiceFragmentDefaults,
  SetServiceFragmentDefaultsInput,
  // Notification shapes.
  Notification,
  NotificationType,
  NotificationStatus,
  NotificationSeverity,
  NotificationPayload,
  ResolveNotificationAction,
  // Per-workspace runtime settings (human-wait escalation threshold + task limits).
  WorkspaceSettings,
  UpdateWorkspaceSettingsInput,
  TaskLimitMode,
  TaskLimitPerType,
  // Slack integration shapes (Slack as an extra notification transport).
  SlackConnection,
  SlackRoute,
  SlackNotificationSettings,
  SlackMemberMappingEntry,
  SlackMemberRole,
  SlackMemberMapping,
  SlackChannel,
  ConnectSlackByTokenInput,
  UpdateSlackSettingsInput,
  UpdateSlackMemberMappingInput,
  // Recurring-pipeline (scheduled run) shapes.
  ScheduleTemplate,
  Recurrence,
  PipelineSchedule,
  ScheduleRun,
  CreateScheduleInput,
  UpdateScheduleInput,
  // Issue-tracker selection shapes.
  TrackerKind,
  TrackerSettings,
  PutTrackerSettingsInput,
  WritebackOverride,
  // LLM observability: the compact per-call summary pushed over the event stream.
  LlmCallActivity,
  // Sandbox (parallel prompt/model testing surface) shapes.
  SandboxPromptOrigin,
  SandboxPromptVersion,
  SandboxFixtureKind,
  SandboxRepoRef,
  SandboxFixtureObjective,
  SandboxFixture,
  SandboxExperimentStatus,
  SandboxMatrix,
  SandboxExperiment,
  SandboxRunStatus,
  SandboxTokenUsage,
  SandboxRun,
  SandboxGradeDimension,
  SandboxObjectiveResult,
  SandboxGrade,
} from '@cat-factory/contracts'
