// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The cluster this workspace provisions per-run environments onto: probe a candidate connection
 * without saving it, or bind one. The credential is write-only, so a read reports which secret
 * keys are stored and never their values.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class EnvironmentsClient {
    private final Transport transport;

    EnvironmentsClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * Connect the workspace to the cluster its environments deploy onto
     * Bind environment provisioning to a Kubernetes cluster: the apiserver, how its TLS is
     * verified, the namespace template, and how an environment URL is derived once manifests are
     * applied. The secret bundle authenticating the connection is write-only; the response reports
     * which secret KEYS were stored and never their values. Idempotent, so re-connecting replaces
     * rather than accumulating.
     * {@code POST /api/v1/environments/connections} (operation {@code connectPublicEnvironment}).
     */
    public ConnectPublicEnvironmentResponse connect(ConnectPublicEnvironmentRequest body) {
        return transport.request("POST", "/api/v1/environments/connections", body, Map.of(), new TypeReference<ConnectPublicEnvironmentResponse>() {});
    }

    /**
     * Probe a candidate cluster connection without saving it
     * Reach the apiserver with the supplied credentials and report what came back, persisting
     * nothing. Worth a call of its own because the alternative is discovering an unreachable
     * cluster or an expired token on the deploy step of a run that has already paid for a design
     * pass and an implementation. A cluster that refuses the credential is an ANSWER, so it is a
     * 200 carrying `ok: false` rather than an error.
     * {@code POST /api/v1/environments/connections/test} (operation {@code
     * testPublicEnvironmentConnection}).
     */
    public TestPublicEnvironmentConnectionResponse testConnection(TestPublicEnvironmentConnectionRequest body) {
        return transport.request("POST", "/api/v1/environments/connections/test", body, Map.of(), new TypeReference<TestPublicEnvironmentConnectionResponse>() {});
    }
}
