// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Headless jobs (a public, inline pipeline run against a brief): start, poll or stream one.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class JobsClient {
    private final Transport transport;

    JobsClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * Cancel a job
     * Stop a headless job run, freeing its concurrency slot. Idempotent — an already-finished job
     * is returned as-is. Use this to abandon a run parked on a decision you do not intend to
     * answer.
     * {@code POST /api/v1/jobs/{id}/cancel} (operation {@code cancelPublicJob}).
     */
    public PublicJob cancel(String id) {
        return transport.request("POST", "/api/v1/jobs/" + Transport.pathSegment(id) + "/cancel", null, Map.of(), new TypeReference<PublicJob>() {});
    }

    /**
     * Start a headless job
     * Start a public, inline pipeline headlessly against a supplied brief. Returns a job id to
     * poll or stream. Nothing is pushed to GitHub.
     * {@code POST /api/v1/jobs} (operation {@code createPublicJob}).
     */
    public PublicJobAccepted create(CreatePublicJob body) {
        return transport.request("POST", "/api/v1/jobs", body, Map.of(), new TypeReference<PublicJobAccepted>() {});
    }

    /**
     * Get a job
     * Poll a headless job started through this surface: its status and, once finished, its result.
     * {@code GET /api/v1/jobs/{id}} (operation {@code getPublicJob}).
     */
    public PublicJob get(String id) {
        return transport.request("GET", "/api/v1/jobs/" + Transport.pathSegment(id), null, Map.of(), new TypeReference<PublicJob>() {});
    }

    /**
     * List the workspace's jobs (no query parameters).
     */
    public ListPublicJobsResponse list() {
        return list(JobsListQuery.none());
    }

    /**
     * List the workspace's jobs
     * List the headless runs THIS surface created, newest first and keyset-paginated. Scoped to
     * internal-anchored runs exactly like the single-job read, so an external key can never
     * enumerate the workspace’s ordinary board runs.
     * {@code GET /api/v1/jobs} (operation {@code listPublicJobs}).
     */
    public ListPublicJobsResponse list(JobsListQuery query) {
        return transport.request("GET", "/api/v1/jobs", null, query.toQuery(), new TypeReference<ListPublicJobsResponse>() {});
    }

    /**
     * Every {@code jobs} across every page of {@code list()}.
     * Pages lazily, following {@code nextCursor} until the server reports no further page. A page
     * may legitimately arrive empty while a cursor is still set, so iteration ends on the cursor,
     * never on an empty page.
     */
    public Iterator<PublicJob> listAll(JobsListQuery query) {
        return new PageIterator<PublicJob>() {
            @Override
            protected Page<PublicJob> fetch(@Nullable String cursor) {
                JobsListQuery nextQuery = JobsListQuery.builder()
                        .limit(query.limit())
                        .status(query.status())
                        .since(query.since())
                        .cursor(cursor)
                        .build();
                ListPublicJobsResponse page = list(nextQuery);
                return new Page<>(page.jobs(), page.nextCursor());
            }
        };
    }

    /**
     * Stream a job (SSE)
     * Server-sent events for a headless job run: `progress` frames until a terminal
     * `done`/`error`/`stopped`/`timeout` event. Authenticated by the API key header.
     * {@code GET /api/v1/jobs/{id}/events} (operation {@code streamPublicJobEvents}).
     */
    public EventStream stream(String id) {
        return transport.stream("GET", "/api/v1/jobs/" + Transport.pathSegment(id) + "/events", Map.of());
    }
}
