// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * What the calling key is and what it may do — the self-check an integration runs at startup.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class MeClient {
    private final Transport transport;

    MeClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * Describe the calling key
     * Report what the key on this request is and what it may do: its id, its account, the ONE
     * workspace every call under it acts within, its scope, and the label it was minted with.
     * `read` scope, the floor of the ladder, because an integration’s startup self-check has to
     * work whatever rung it holds. The scope ladder is INCLUSIVE (`read` ⊂ `write` ⊂ `decide` ⊂
     * `admin`), so compare against the rung an action needs rather than for equality.
     * {@code GET /api/v1/me} (operation {@code getPublicIdentity}).
     */
    public PublicIdentity get() {
        return transport.request("GET", "/api/v1/me", null, Map.of(), new TypeReference<PublicIdentity>() {});
    }
}
