// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The models a run in this workspace could actually dispatch to, and why an unavailable one is
 * unavailable: unconfigured, or refused by the account model-family policy. Those two need
 * opposite fixes.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class ModelsClient {
    private final Transport transport;

    ModelsClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * List the models a run in this workspace could dispatch to
     * The workspace’s model catalog with the two flags that decide whether an agent step can run
     * at all: `available`, and `policyBlocked` for a model that is configured but refused by the
     * account’s model-family policy. Those two need OPPOSITE fixes, which is why they are
     * separate: everything blocked by policy is already configured, so adding another provider key
     * changes nothing.
     * {@code GET /api/v1/models} (operation {@code listPublicWiredModels}).
     */
    public ListPublicWiredModelsResponse list() {
        return transport.request("GET", "/api/v1/models", null, Map.of(), new TypeReference<ListPublicWiredModelsResponse>() {});
    }
}
