// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The models a run in this workspace could actually dispatch to, and why an unavailable one is
 * unavailable: unconfigured, or refused by the account model-family policy. Those two need
 * opposite fixes.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class ModelsClient {
    private final Transport transport;

    ModelsClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * List the models a run in this workspace could dispatch to
     * The workspace’s model catalog with the flags that decide whether an agent step can run at
     * all, and which of four unrelated fixes an unrunnable one needs. `available` says a run can
     * dispatch to it now. `policyBlocked` says it is configured and refused by the account’s
     * model-family policy, so adding another provider key changes nothing. `personalSubscription`
     * says it runs on a credential belonging to a PERSON (an individual-usage subscription
     * vendor), which a key resolving no user can never see. `subscriptionConfigured` then says
     * whether that person actually holds one: `true` means the model is wired and only the key’s
     * identity is in the way, `false` means the owner is known and holds none, and `null` means
     * there was nobody to ask about, so it must not be read as `false`. `userScoped` is SUPERSEDED
     * by `personalSubscription` and still answers its original narrower question (whether a
     * subscription is the route in force); prefer the newer field.
     * {@code GET /api/v1/models} (operation {@code listPublicWiredModels}).
     */
    public ListPublicWiredModelsResponse list() {
        return transport.request("GET", "/api/v1/models", null, Map.of(), new TypeReference<ListPublicWiredModelsResponse>() {});
    }
}
