// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The pipelines a task can be started with, and whether each is headless-startable.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class PipelinesClient {
    private final Transport transport;

    PipelinesClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * List the workspace's pipelines
     * List the pipelines in the key’s workspace — id/name/steps plus whether each is public and
     * safe to run headlessly — so a caller can pick a pipelineId to start a task with.
     * {@code GET /api/v1/pipelines} (operation {@code listPublicPipelines}).
     */
    public PublicPipelineList list() {
        return transport.request("GET", "/api/v1/pipelines", null, Map.of(), new TypeReference<PublicPipelineList>() {});
    }
}
