// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * A board task's whole lifecycle: create, edit, start, stop, retry, watch, delete.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class TasksClient {
    private final Transport transport;

    TasksClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * Create a task under a service
     * Create a task inside a service frame the key’s workspace owns. The task starts in the
     * `planned` state; start it with the start endpoint.
     * {@code POST /api/v1/services/{serviceId}/tasks} (operation {@code createPublicTask}).
     */
    public PublicTask create(String serviceId, CreatePublicTask body) {
        return transport.request("POST", "/api/v1/services/" + Transport.pathSegment(serviceId) + "/tasks", body, Map.of(), new TypeReference<PublicTask>() {});
    }

    /**
     * Delete a task
     * Delete a task and its run history. Destructive, so it sits at the top of the scope ladder:
     * requires an `admin`-scoped key.
     * {@code DELETE /api/v1/tasks/{taskId}} (operation {@code deletePublicTask}).
     */
    public void delete(String taskId) {
        transport.requestNoContent("DELETE", "/api/v1/tasks/" + Transport.pathSegment(taskId), null, Map.of());
    }

    /**
     * Get a task's status
     * Read a task’s current lifecycle status, run progress, execution id, and PR URL (once one
     * exists).
     * {@code GET /api/v1/tasks/{taskId}} (operation {@code getPublicTask}).
     */
    public PublicTask get(String taskId) {
        return transport.request("GET", "/api/v1/tasks/" + Transport.pathSegment(taskId), null, Map.of(), new TypeReference<PublicTask>() {});
    }

    /**
     * Get a task's run (rich projection)
     * Read a task’s run in detail: per-step status/progress/subtasks, the failure kind and
     * message, and the PR (url + branch).
     * {@code GET /api/v1/tasks/{taskId}/run} (operation {@code getPublicRun}).
     */
    public PublicRun getRun(String taskId) {
        return transport.request("GET", "/api/v1/tasks/" + Transport.pathSegment(taskId) + "/run", null, Map.of(), new TypeReference<PublicRun>() {});
    }

    /**
     * List a service's tasks (no query parameters).
     */
    public PublicTaskList listByService(String serviceId) {
        return listByService(serviceId, TasksListByServiceQuery.none());
    }

    /**
     * List a service's tasks
     * List every task under a service (the whole subtree — tasks directly under the frame and
     * under its modules).
     * {@code GET /api/v1/services/{serviceId}/tasks} (operation {@code listPublicServiceTasks}).
     */
    public PublicTaskList listByService(String serviceId, TasksListByServiceQuery query) {
        return transport.request("GET", "/api/v1/services/" + Transport.pathSegment(serviceId) + "/tasks", null, query.toQuery(), new TypeReference<PublicTaskList>() {});
    }

    /**
     * Every {@code tasks} across every page of {@code listByService()}.
     * Pages lazily, following {@code nextCursor} until the server reports no further page. A page
     * may legitimately arrive empty while a cursor is still set, so iteration ends on the cursor,
     * never on an empty page.
     */
    public Iterator<PublicTask> listByServiceAll(String serviceId, TasksListByServiceQuery query) {
        return new PageIterator<PublicTask>() {
            @Override
            protected Page<PublicTask> fetch(@Nullable String cursor) {
                TasksListByServiceQuery nextQuery = TasksListByServiceQuery.builder()
                        .limit(query.limit())
                        .status(query.status())
                        .cursor(cursor)
                        .build();
                PublicTaskList page = listByService(serviceId, nextQuery);
                return new Page<>(page.tasks(), page.nextCursor());
            }
        };
    }

    /**
     * Retry a task's failed run
     * Retry a task’s failed run. A task on an individual-usage model cannot be retried through the
     * API (no headless personal-credential unlock).
     * {@code POST /api/v1/tasks/{taskId}/retry} (operation {@code retryPublicTask}).
     */
    public PublicTask retry(String taskId) {
        return transport.request("POST", "/api/v1/tasks/" + Transport.pathSegment(taskId) + "/retry", null, Map.of(), new TypeReference<PublicTask>() {});
    }

    /**
     * Start (run) a task
     * Start a task’s pipeline. Uses the request’s pipelineId, else the task’s pinned pipeline. A
     * task on an individual-usage model cannot be started through the API (no headless
     * personal-credential unlock).
     * {@code POST /api/v1/tasks/{taskId}/start} (operation {@code startPublicTask}).
     */
    public PublicTask start(String taskId, StartPublicTask body) {
        return transport.request("POST", "/api/v1/tasks/" + Transport.pathSegment(taskId) + "/start", body, Map.of(), new TypeReference<PublicTask>() {});
    }

    /**
     * Stop a task's run
     * Stop a task’s in-flight run. Records a `cancelled` terminal state, leaving the run
     * retryable.
     * {@code POST /api/v1/tasks/{taskId}/stop} (operation {@code stopPublicTask}).
     */
    public PublicTask stop(String taskId) {
        return transport.request("POST", "/api/v1/tasks/" + Transport.pathSegment(taskId) + "/stop", null, Map.of(), new TypeReference<PublicTask>() {});
    }

    /**
     * Stream a task run (SSE)
     * Server-sent events for a board task run: `progress` frames (the rich run projection) until a
     * terminal `done`/`error` event, or a `timeout` when the connection cap is reached.
     * Authenticated by the API key header.
     * {@code GET /api/v1/tasks/{taskId}/events} (operation {@code streamPublicTaskRun}).
     */
    public EventStream stream(String taskId) {
        return transport.stream("GET", "/api/v1/tasks/" + Transport.pathSegment(taskId) + "/events", Map.of());
    }

    /**
     * Edit a task's title/description
     * Edit a task’s human-authored fields (title/description) before it runs. Both fields are
     * optional.
     * {@code PATCH /api/v1/tasks/{taskId}} (operation {@code updatePublicTask}).
     */
    public PublicTask update(String taskId, UpdatePublicTask body) {
        return transport.request("PATCH", "/api/v1/tasks/" + Transport.pathSegment(taskId), body, Map.of(), new TypeReference<PublicTask>() {});
    }
}
