// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * What a task can be created AS in this workspace (the built-in kinds plus the operations the
 * deployment registered), and the fields each one accepts.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class TaskTypesClient {
    private final Transport transport;

    TaskTypesClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * List the task types this workspace may create
     * List the task types a task can be created as in the key’s workspace (the built-in ones plus
     * any the deployment registered), each with the fields it accepts. Fill those fields through
     * `fields` on task creation; the descriptors here are what that call validates against, so a
     * caller reads the form rather than guessing it. A type a workspace admin has hidden is
     * absent.
     * {@code GET /api/v1/task-types} (operation {@code listPublicTaskTypes}).
     */
    public ListPublicTaskTypesResponse list() {
        return transport.request("GET", "/api/v1/task-types", null, Map.of(), new TypeReference<ListPublicTaskTypesResponse>() {});
    }
}
