// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

package ai.catfactory.sdk.resources;

import ai.catfactory.sdk.EventStream;
import ai.catfactory.sdk.PageIterator;
import ai.catfactory.sdk.Transport;
import ai.catfactory.sdk.model.*;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.Iterator;
import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * The billing period's metered budget position and the per-model breakdown behind it.
 * Reached from {@link CatFactoryClient}; not constructed directly.
 */
public final class UsageClient {
    private final Transport transport;

    UsageClient(Transport transport) {
        this.transport = transport;
    }

    /**
     * Read the workspace's usage for the current period
     * Read this billing period’s METERED spend against the workspace budget (including whether it
     * is exceeded, which pauses runs) plus the per-(billing, vendor, provider, model) token
     * breakdown behind it. Costs on `subscription` rows are illustrative — a flat-rate plan bills
     * nothing per token — so branch on `billing` before summing. Workspace-scoped: the account-
     * and user-tier budgets are not reachable through this surface.
     * {@code GET /api/v1/usage} (operation {@code getPublicUsage}).
     */
    public PublicUsage get() {
        return transport.request("GET", "/api/v1/usage", null, Map.of(), new TypeReference<PublicUsage>() {});
    }
}
