# GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
# Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

"""The resource clients: one class per resource group, each a thin shell over the hand-written
``Transport``. Nothing here decides retry, auth, error mapping or stream framing — that is
``_http.py`` / ``errors.py`` / ``_sse.py``, so those change without touching 38 methods.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any
from urllib.parse import quote

from ._http import Transport
from ._sse import EventStream
from .errors import _repeated_cursor
from .models import (
    _encode,
    _enum,
    CreatePublicJob,
    CreatePublicTask,
    DebugAgentContextSnapshot,
    DebugLlmCall,
    DebugRunOverview,
    GetDebugLlmCallView,
    ListDebugAgentContextResponse,
    ListDebugLlmCallsOrder,
    ListDebugLlmCallsResponse,
    ListDebugLogsResponse,
    ListDebugRunsResponse,
    ListDebugSearchQueriesResponse,
    ListPublicJobsResponse,
    LlmCallOutcome,
    Notification,
    NotificationWebhook,
    PublicApproveStep,
    PublicChallengePrReviewFinding,
    PublicChooseFork,
    PublicDecisionList,
    PublicIncorporate,
    PublicJob,
    PublicJobAccepted,
    PublicJobStatus,
    PublicNotificationList,
    PublicNotificationWebhook,
    PublicPipelineList,
    PublicRejectStep,
    PublicReplyFinding,
    PublicRequestGateFix,
    PublicRequestStepChanges,
    PublicResolveAgentDecision,
    PublicResolveExceeded,
    PublicResolveInputGate,
    PublicResolveJudge,
    PublicResolvePrReview,
    PublicRun,
    PublicServiceList,
    PublicSetFindingStatus,
    PublicTask,
    PublicTaskList,
    PublicUsage,
    PutNotificationWebhook,
    RunStatus,
    StartPublicTask,
    TaskStatus,
    UpdatePublicTask,
)


def _quote(value: str) -> str:
    """Percent-encode a path parameter.

    An id is server-supplied but travels through a caller's own storage, and one carrying a
    slash would otherwise re-target the request at a different route rather than 404 on the id
    it names.
    """
    return quote(str(value), safe="")


class JobsResource:
    """Headless jobs (a public, inline pipeline run against a brief): start, poll or stream
    one.
    """

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def cancel(self, id: str, timeout: float | None = None) -> PublicJob:
        """Cancel a job
        Stop a headless job run, freeing its concurrency slot. Idempotent — an
        already-finished job is returned as-is. Use this to abandon a run parked on a
        decision you do not intend to answer.
        `POST /api/v1/jobs/{id}/cancel` (operation `cancelPublicJob`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/jobs/{_quote(id)}/cancel",
            query=None,
            timeout=timeout,
        )
        return PublicJob.from_dict(raw)

    def create(self, body: CreatePublicJob, timeout: float | None = None) -> PublicJobAccepted:
        """Start a headless job
        Start a public, inline pipeline headlessly against a supplied brief. Returns a job
        id to poll or stream. Nothing is pushed to GitHub.
        `POST /api/v1/jobs` (operation `createPublicJob`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/jobs",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicJobAccepted.from_dict(raw)

    def get(self, id: str, timeout: float | None = None) -> PublicJob:
        """Get a job
        Poll a headless job started through this surface: its status and, once finished, its
        result.
        `GET /api/v1/jobs/{id}` (operation `getPublicJob`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/jobs/{_quote(id)}",
            query=None,
            timeout=timeout,
        )
        return PublicJob.from_dict(raw)

    def list(self, *, limit: int | None = None, cursor: str | None = None, status: PublicJobStatus | None = None, since: int | None = None, timeout: float | None = None) -> ListPublicJobsResponse:
        """List the workspace's jobs
        List the headless runs THIS surface created, newest first and keyset-paginated.
        Scoped to internal-anchored runs exactly like the single-job read, so an external
        key can never enumerate the workspace’s ordinary board runs.
        `GET /api/v1/jobs` (operation `listPublicJobs`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/jobs",
            query={"limit": limit, "cursor": cursor, "status": status, "since": since},
            timeout=timeout,
        )
        return ListPublicJobsResponse.from_dict(raw)

    def list_all(self, *, limit: int | None = None, cursor: str | None = None, status: PublicJobStatus | None = None, since: int | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `jobs` across every page of `list()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListPublicJobsResponse.jobs`.
        """
        page_cursor = cursor
        while True:
            page = self.list(limit=limit, status=status, since=since, cursor=page_cursor, timeout=timeout)
            yield from page.jobs
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def stream(self, id: str, timeout: float | None = None) -> EventStream:
        """Stream a job (SSE)
        Server-sent events for a headless job run: `progress` frames until a terminal
        `done`/`error`/`stopped`/`timeout` event. Authenticated by the API key header.
        `GET /api/v1/jobs/{id}/events` (operation `streamPublicJobEvents`).
        """
        return self._transport.stream(
            "GET",
            f"/api/v1/jobs/{_quote(id)}/events",
            query=None,
            timeout=timeout,
        )


class ServicesResource:
    """The workspace's board services — the frames tasks are created under."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, timeout: float | None = None) -> PublicServiceList:
        """List the workspace's services
        List the board service frames in the key’s workspace, so a caller can discover the
        serviceId to create/list tasks under.
        `GET /api/v1/services` (operation `listPublicServices`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/services",
            query=None,
            timeout=timeout,
        )
        return PublicServiceList.from_dict(raw)


class TasksResource:
    """A board task's whole lifecycle: create, edit, start, stop, retry, watch, delete."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def create(self, service_id: str, body: CreatePublicTask, timeout: float | None = None) -> PublicTask:
        """Create a task under a service
        Create a task inside a service frame the key’s workspace owns. The task starts in
        the `planned` state; start it with the start endpoint. Optionally file it FROM a
        tracker ticket, and/or attach the requirements documents it is to be built against
        (named in a connected document source, or uploaded inline): the only way to get
        spec-sized input onto a repository-touching run.
        `POST /api/v1/services/{serviceId}/tasks` (operation `createPublicTask`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/services/{_quote(service_id)}/tasks",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)

    def delete(self, task_id: str, timeout: float | None = None) -> None:
        """Delete a task
        Delete a task and its run history. Destructive, so it sits at the top of the scope
        ladder: requires an `admin`-scoped key.
        `DELETE /api/v1/tasks/{taskId}` (operation `deletePublicTask`).
        """
        self._transport.request_no_content(
            "DELETE",
            f"/api/v1/tasks/{_quote(task_id)}",
            query=None,
            timeout=timeout,
        )

    def get(self, task_id: str, timeout: float | None = None) -> PublicTask:
        """Get a task's status
        Read a task’s current lifecycle status, run progress, run id, and PR URL (once one
        exists).
        `GET /api/v1/tasks/{taskId}` (operation `getPublicTask`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/tasks/{_quote(task_id)}",
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)

    def get_run(self, task_id: str, timeout: float | None = None) -> PublicRun:
        """Get a task's run (rich projection)
        Read a task’s run in detail: per-step status/progress/subtasks, the failure kind and
        message, and the PR (url + branch).
        `GET /api/v1/tasks/{taskId}/run` (operation `getPublicRun`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/tasks/{_quote(task_id)}/run",
            query=None,
            timeout=timeout,
        )
        return PublicRun.from_dict(raw)

    def list_by_service(self, service_id: str, *, limit: int | None = None, cursor: str | None = None, status: TaskStatus | None = None, timeout: float | None = None) -> PublicTaskList:
        """List a service's tasks
        List every task under a service (the whole subtree — tasks directly under the frame
        and under its modules).
        `GET /api/v1/services/{serviceId}/tasks` (operation `listPublicServiceTasks`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/services/{_quote(service_id)}/tasks",
            query={"limit": limit, "cursor": cursor, "status": status},
            timeout=timeout,
        )
        return PublicTaskList.from_dict(raw)

    def list_by_service_all(self, service_id: str, *, limit: int | None = None, cursor: str | None = None, status: TaskStatus | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `tasks` across every page of `list_by_service()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `PublicTaskList.tasks`.
        """
        page_cursor = cursor
        while True:
            page = self.list_by_service(service_id, limit=limit, status=status, cursor=page_cursor, timeout=timeout)
            yield from page.tasks
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def retry(self, task_id: str, timeout: float | None = None) -> PublicTask:
        """Retry a task's failed run
        Retry a task’s failed run. A task on an individual-usage model cannot be retried
        through the API (no headless personal-credential unlock).
        `POST /api/v1/tasks/{taskId}/retry` (operation `retryPublicTask`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/tasks/{_quote(task_id)}/retry",
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)

    def start(self, task_id: str, body: StartPublicTask, timeout: float | None = None) -> PublicTask:
        """Start (run) a task
        Start a task’s pipeline. Uses the request’s pipelineId, else the task’s pinned
        pipeline. A pipeline that can park on a human decision requires a `decide`-scope
        key. A task on an individual-usage model cannot be started through the API (no
        headless personal-credential unlock).
        `POST /api/v1/tasks/{taskId}/start` (operation `startPublicTask`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/tasks/{_quote(task_id)}/start",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)

    def stop(self, task_id: str, timeout: float | None = None) -> PublicTask:
        """Stop a task's run
        Stop a task’s in-flight run. Records a `cancelled` terminal state, leaving the run
        retryable.
        `POST /api/v1/tasks/{taskId}/stop` (operation `stopPublicTask`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/tasks/{_quote(task_id)}/stop",
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)

    def stream(self, task_id: str, timeout: float | None = None) -> EventStream:
        """Stream a task run (SSE)
        Server-sent events for a board task run: `progress` frames (the rich run projection)
        until a terminal `done`/`error` event, or a `timeout` when the connection cap is
        reached. Authenticated by the API key header.
        `GET /api/v1/tasks/{taskId}/events` (operation `streamPublicTaskRun`).
        """
        return self._transport.stream(
            "GET",
            f"/api/v1/tasks/{_quote(task_id)}/events",
            query=None,
            timeout=timeout,
        )

    def update(self, task_id: str, body: UpdatePublicTask, timeout: float | None = None) -> PublicTask:
        """Edit a task's title/description
        Edit a task’s human-authored fields (title/description) before it runs. Both fields
        are optional.
        `PATCH /api/v1/tasks/{taskId}` (operation `updatePublicTask`).
        """
        raw = self._transport.request(
            "PATCH",
            f"/api/v1/tasks/{_quote(task_id)}",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicTask.from_dict(raw)


class PipelinesResource:
    """The pipelines a task can be started with, and whether each is headless-startable."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def list(self, timeout: float | None = None) -> PublicPipelineList:
        """List the workspace's pipelines
        List the pipelines in the key’s workspace — id/name/steps plus whether each is
        public and safe to run headlessly — so a caller can pick a pipelineId to start a
        task with.
        `GET /api/v1/pipelines` (operation `listPublicPipelines`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/pipelines",
            query=None,
            timeout=timeout,
        )
        return PublicPipelineList.from_dict(raw)


class NotificationsResource:
    """The workspace's human-actionable inbox: list, act on, or dismiss a run tail."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def act(self, id: str, timeout: float | None = None) -> Notification:
        """Act on a notification
        Run a notification’s typed side-effect and resolve it: merge the PR (merge_review /
        pipeline_complete) or retry the run (ci_failed / test_failed). Performs a real
        GitHub merge, so it requires an admin-scoped key. Only these automated-action types
        are actionable through the API — a notification that parks a run on an interactive
        human decision cannot be acted on headlessly (dismiss it instead). A card that would
        retry a run on an individual-usage model likewise cannot be acted on through the
        API.
        `POST /api/v1/notifications/{id}/act` (operation `actPublicNotification`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/notifications/{_quote(id)}/act",
            query=None,
            timeout=timeout,
        )
        return Notification.from_dict(raw)

    def dismiss(self, id: str, timeout: float | None = None) -> Notification:
        """Dismiss a notification
        Dismiss a notification without acting on it.
        `POST /api/v1/notifications/{id}/dismiss` (operation `dismissPublicNotification`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/notifications/{_quote(id)}/dismiss",
            query=None,
            timeout=timeout,
        )
        return Notification.from_dict(raw)

    def list(self, timeout: float | None = None) -> PublicNotificationList:
        """List the workspace's open notifications
        List the open, human-actionable notifications in the key’s workspace (merge reviews,
        pipeline-complete confirmations, CI/test failures, and informational cards).
        `GET /api/v1/notifications` (operation `listPublicNotifications`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/notifications",
            query=None,
            timeout=timeout,
        )
        return PublicNotificationList.from_dict(raw)


class WebhookResource:
    """The workspace's one outbound endpoint: register, inspect or remove the receiver that
    notifications, run-lifecycle events and health alerts are pushed to.
    """

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def delete(self, timeout: float | None = None) -> None:
        """Remove the outbound webhook
        Deregister the endpoint; deliveries stop. Idempotent.
        `DELETE /api/v1/notification-webhook` (operation `deletePublicNotificationWebhook`).
        """
        self._transport.request_no_content(
            "DELETE",
            f"/api/v1/notification-webhook",
            query=None,
            timeout=timeout,
        )

    def get(self, timeout: float | None = None) -> PublicNotificationWebhook:
        """Read the workspace's outbound webhook
        The endpoint this workspace delivers notifications, run-lifecycle events and
        platform-health alerts to, or `{ "webhook": null }` when none is registered. The
        signing secret is never returned; `hasSecret` reports only whether one is set.
        `GET /api/v1/notification-webhook` (operation `getPublicNotificationWebhook`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/notification-webhook",
            query=None,
            timeout=timeout,
        )
        return PublicNotificationWebhook.from_dict(raw)

    def set(self, body: PutNotificationWebhook, timeout: float | None = None) -> NotificationWebhook:
        """Register or update the outbound webhook
        Register the HTTPS endpoint deliveries are POSTed to, or update the one already
        registered. Every omitted field keeps its stored value, so subscribing to run events
        is a one-field call that re-sends neither the URL nor the secret. `url` is required
        only on the first call, when there is nothing registered to keep; omitting it
        otherwise leaves the endpoint alone. Supplying `secret` rotates the signing secret;
        omitting it keeps the current one. The endpoint must be `https:` and publicly
        routable unless the deployment widened its allow-list.
        `PUT /api/v1/notification-webhook` (operation `putPublicNotificationWebhook`).
        """
        raw = self._transport.request(
            "PUT",
            f"/api/v1/notification-webhook",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return NotificationWebhook.from_dict(raw)


class UsageResource:
    """The billing period's metered budget position and the per-model breakdown behind it."""

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def get(self, timeout: float | None = None) -> PublicUsage:
        """Read the workspace's usage for the current period
        Read this billing period’s METERED spend against the workspace budget (including
        whether it is exceeded, which pauses runs) plus the per-(billing, vendor, provider,
        model) token breakdown behind it. Costs on `subscription` rows are illustrative — a
        flat-rate plan bills nothing per token — so branch on `billing` before summing.
        Workspace-scoped: the account- and user-tier budgets are not reachable through this
        surface.
        `GET /api/v1/usage` (operation `getPublicUsage`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/usage",
            query=None,
            timeout=timeout,
        )
        return PublicUsage.from_dict(raw)


class DecisionsResource:
    """Every way a run stops for a person: approval gates, review and brainstorm loops, forks,
    judge verdicts, PR review findings and the human-verdict gates.
    """

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def answer_agent_decision(self, run_id: str, decision_id: str, body: PublicResolveAgentDecision, timeout: float | None = None) -> PublicDecisionList:
        """Answer an agent-raised decision
        Answer a question an agent raised mid-work. Resolving RE-RUNS the asking step with
        the choice folded in, rather than advancing past it. The choice is taken verbatim,
        so it may be one of the offered options or a steer of your own. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/questions/{decisionId}/answer` (operation
        `resolvePublicRunAgentDecision`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/questions/{_quote(decision_id)}/answer",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def approve_step(self, run_id: str, approval_id: str, body: PublicApproveStep, timeout: float | None = None) -> PublicDecisionList:
        """Approve a parked step
        Approve the proposal a gated step is holding up, optionally replacing it with an
        edited one (the edit is what flows to every downstream step), and advance the run.
        The `approvalId` comes from the run's decision list; passing it back is what makes a
        racing app user and a racing integration resolve the same gate. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/approve` (operation
        `approvePublicRunStep`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/approvals/{_quote(approval_id)}/approve",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def approve_visual_confirmation(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Approve a visual-confirmation gate
        Approve the captured screenshots against the reference designs and advance the run.
        The images themselves are not readable over this API — the decision carries only
        artifact ids — so approving on the projection alone approves screenshots you have
        not seen. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/visual-confirmation/approve` (operation
        `approvePublicRunVisualConfirm`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/visual-confirmation/approve",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def challenge_pr_review_finding(self, run_id: str, finding_id: str, body: PublicChallengePrReviewFinding, timeout: float | None = None) -> PublicDecisionList:
        """Challenge a PR review finding
        Dispatch a read-only investigator to re-examine one finding against the full source,
        optionally with a specific concern. It upholds, strengthens or retracts the finding,
        and the review re-parks carrying the verdict. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/challenge`
        (operation `challengePublicRunPrReviewFinding`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/pr-review/findings/{_quote(finding_id)}/challenge",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def choose_fork(self, run_id: str, body: PublicChooseFork, timeout: float | None = None) -> PublicDecisionList:
        """Choose an implementation approach
        Pick one of the proposed implementation forks (by id) or submit your own approach.
        The Coder then runs with the choice folded in as a binding directive. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/fork/choose` (operation `choosePublicRunFork`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/fork/choose",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def confirm_human_test(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Confirm a human-test gate
        Confirm the change works in the ephemeral environment: it is torn down and the run
        advances. The decision carries the environment URL to exercise; confirming without
        exercising it approves untested work. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/human-test/confirm` (operation
        `confirmPublicRunHumanTest`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/human-test/confirm",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def dismiss_pr_review_finding(self, run_id: str, finding_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Dismiss a PR review finding
        Drop one finding from the parked review entirely. Curation rather than a resolution:
        the run stays parked. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/dismiss`
        (operation `dismissPublicRunPrReviewFinding`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/pr-review/findings/{_quote(finding_id)}/dismiss",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def incorporate(self, run_id: str, body: PublicIncorporate, timeout: float | None = None) -> PublicDecisionList:
        """Incorporate the answers
        Fold the recorded answers into one standardized requirements document. Asynchronous
        — the run re-reviews in the background, so the response shows the review
        `incorporating`. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/requirements/incorporate` (operation
        `incorporatePublicRunRequirements`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/incorporate",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def incorporate_brainstorm(self, run_id: str, stage: str, body: PublicIncorporate, timeout: float | None = None) -> PublicDecisionList:
        """Incorporate brainstorm picks
        Fold the picks into one converged direction. ASYNCHRONOUS: the response shows the
        session `incorporating` while the durable driver folds and re-runs in the
        background. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/incorporate` (operation
        `incorporatePublicRunBrainstorm`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/incorporate",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def incorporate_clarity(self, run_id: str, body: PublicIncorporate, timeout: float | None = None) -> PublicDecisionList:
        """Incorporate clarity answers
        Fold the recorded answers into one standardized bug report. ASYNCHRONOUS: the
        response shows the review `incorporating` while the durable driver folds and
        re-reviews in the background. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/clarity/incorporate` (operation
        `incorporatePublicRunClarity`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/incorporate",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def list(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """List a run's parked decisions
        Read what a run is currently asking a human: requirement-review findings (with the
        stable item ids a reply addresses) and any implementation-fork choice. `parked` is
        true while the run is blocked awaiting one of them.
        `GET /api/v1/runs/{runId}/decisions` (operation `listPublicRunDecisions`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/runs/{_quote(run_id)}/decisions",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def proceed(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Proceed with the current requirements
        Settle the requirements phase and advance the parked run (used when nothing is
        outstanding). Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/requirements/proceed` (operation
        `proceedPublicRunRequirements`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/proceed",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def proceed_brainstorm(self, run_id: str, stage: str, timeout: float | None = None) -> PublicDecisionList:
        """Proceed past a brainstorm
        Settle the brainstorm with the last converged direction and advance the parked run.
        Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/proceed` (operation
        `proceedPublicRunBrainstorm`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/proceed",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def proceed_clarity(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Proceed past the clarity review
        Settle the clarity phase with the last clarified report and advance the parked run.
        Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/clarity/proceed` (operation
        `proceedPublicRunClarity`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/proceed",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def reject_step(self, run_id: str, approval_id: str, body: PublicRejectStep, timeout: float | None = None) -> PublicDecisionList:
        """Reject a parked step
        Reject the gated proposal: the run stops entirely, recording a terminal `rejected`
        failure the board can retry. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/reject` (operation
        `rejectPublicRunStep`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/approvals/{_quote(approval_id)}/reject",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def reply_to_brainstorm_option(self, run_id: str, stage: str, item_id: str, body: PublicReplyFinding, timeout: float | None = None) -> PublicDecisionList:
        """Respond to a brainstorm option
        Pick or steer one of the options the brainstorm agent proposed, for the named stage
        (`requirements` or `architecture`). A task may hold one live session per stage at
        once. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}/reply`
        (operation `replyPublicRunBrainstormOption`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/options/{_quote(item_id)}/reply",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def reply_to_clarity_finding(self, run_id: str, item_id: str, body: PublicReplyFinding, timeout: float | None = None) -> PublicDecisionList:
        """Answer a clarity (bug-triage) finding
        Record an answer to one clarity-review finding — the bug-report twin of the
        requirements loop. Returns the run's updated decision list. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}/reply` (operation
        `replyPublicRunClarityFinding`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/findings/{_quote(item_id)}/reply",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def reply_to_finding(self, run_id: str, item_id: str, body: PublicReplyFinding, timeout: float | None = None) -> PublicDecisionList:
        """Answer a review finding
        Record an answer to one reviewer finding. Returns the run's updated decision list.
        Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}/reply`
        (operation `replyPublicRunFinding`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/findings/{_quote(item_id)}/reply",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def request_human_test_fix(self, run_id: str, body: PublicRequestGateFix, timeout: float | None = None) -> PublicDecisionList:
        """Request a fix from a human-test gate
        Submit findings against the tested environment and dispatch a fixer, which commits
        onto the PR branch before the environment is rebuilt. The findings ARE the fixer
        prompt, so they cannot be blank. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/human-test/request-fix` (operation
        `requestPublicRunHumanTestFix`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/human-test/request-fix",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def request_step_changes(self, run_id: str, approval_id: str, body: PublicRequestStepChanges, timeout: float | None = None) -> PublicDecisionList:
        """Request changes on a parked step
        Send the gated step back to re-run with your guidance folded in. Unlike the in-app
        twin this takes freeform feedback only: anchored per-block comments address source
        line ranges of a rendered proposal, which a headless caller never rendered. Requires
        a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/request-changes`
        (operation `requestPublicRunStepChanges`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/approvals/{_quote(approval_id)}/request-changes",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def request_visual_confirmation_fix(self, run_id: str, body: PublicRequestGateFix, timeout: float | None = None) -> PublicDecisionList:
        """Request a fix from a visual-confirmation gate
        Submit findings against the captured screenshots and dispatch a fixer. The findings
        ARE the fixer prompt, so they cannot be blank. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/visual-confirmation/request-fix` (operation
        `requestPublicRunVisualConfirmFix`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/visual-confirmation/request-fix",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def re_review(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Re-review the incorporated document
        Run one more reviewer pass over the incorporated document. On convergence the parked
        run advances. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/requirements/re-review` (operation
        `reReviewPublicRunRequirements`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/re-review",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def re_review_brainstorm(self, run_id: str, stage: str, timeout: float | None = None) -> PublicDecisionList:
        """Re-run a brainstorm pass
        Run one more brainstorm pass against the converged direction. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/re-review` (operation
        `reReviewPublicRunBrainstorm`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/re-review",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def re_review_clarity(self, run_id: str, timeout: float | None = None) -> PublicDecisionList:
        """Re-triage the clarified report
        Run one more triage pass over the incorporated bug report. On convergence the parked
        run advances. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/clarity/re-review` (operation
        `reReviewPublicRunClarity`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/re-review",
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_brainstorm_exceeded(self, run_id: str, stage: str, body: PublicResolveExceeded, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a brainstorm at its iteration cap
        Pick how a brainstorm that exhausted its pass budget proceeds: one more round,
        proceed with the last converged direction, or stop and reset the task. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/resolve-exceeded` (operation
        `resolvePublicRunBrainstormExceeded`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/resolve-exceeded",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_clarity_exceeded(self, run_id: str, body: PublicResolveExceeded, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a clarity review at its iteration cap
        Pick how a clarity review that exhausted its pass budget proceeds: one more round,
        proceed with the last clarified report, or stop and reset the task. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/clarity/resolve-exceeded` (operation
        `resolvePublicRunClarityExceeded`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/resolve-exceeded",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_exceeded(self, run_id: str, body: PublicResolveExceeded, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a review at its iteration cap
        Pick how a review that exhausted its reviewer-pass budget proceeds: one more round,
        proceed with the last incorporated document, or stop and reset the task. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/requirements/resolve-exceeded` (operation
        `resolvePublicRunRequirementsExceeded`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/resolve-exceeded",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_input_gate(self, run_id: str, body: PublicResolveInputGate, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a run parked on the task's input check
        Settle a run the pre-dispatch input gate parked before its first agent step because
        the task states nothing an agent could act on. `recheck` re-evaluates the task as it
        now stands (edit it over `PATCH /api/v1/tasks/{taskId}` first: the fix is verified,
        not taken on trust) and releases the run only if the blocking findings are gone; a
        still-blocked verdict comes back as an ordinary 200 with refreshed findings.
        `proceed` waives the findings, which stay on the run as an `overridden` record.
        Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/input-gate/resolve` (operation
        `resolvePublicRunInputGate`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/input-gate/resolve",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_judge(self, run_id: str, body: PublicResolveJudge, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a parked judge verdict
        Settle a run parked on a judge verdict: proceed anyway, bounce the producing step
        for rework, or stop the run. Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/judge/resolve` (operation
        `resolvePublicRunJudge`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/judge/resolve",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_pr_review(self, run_id: str, body: PublicResolvePrReview, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a parked PR deep review
        Record the curated finding selection and say what to do with it: `finish` completes
        the read-only review, `fix` hands the selected findings to a fixer that commits onto
        the reviewed PR branch, `post` publishes them as inline PR review comments. `fix`
        and `post` need at least one selected finding and act on the real pull request.
        Requires a `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/pr-review/resolve` (operation
        `resolvePublicRunPrReview`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/pr-review/resolve",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def resolve_step_exceeded(self, run_id: str, approval_id: str, body: PublicResolveExceeded, timeout: float | None = None) -> PublicDecisionList:
        """Resolve a companion gate at its rework cap
        Pick how a quality companion that spent its automatic rework budget proceeds: one
        more round, proceed with the output as it stands, or stop and reset the task. A gate
        in this state reports `exceeded: true` and refuses the plain approve. Requires a
        `decide`-scope key.
        `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/resolve-exceeded`
        (operation `resolvePublicRunStepExceeded`).
        """
        raw = self._transport.request(
            "POST",
            f"/api/v1/runs/{_quote(run_id)}/decisions/approvals/{_quote(approval_id)}/resolve-exceeded",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def set_brainstorm_option_status(self, run_id: str, stage: str, item_id: str, body: PublicSetFindingStatus, timeout: float | None = None) -> PublicDecisionList:
        """Dismiss or reopen a brainstorm option
        Dismiss a proposed option, or reopen one dismissed by mistake. Only `open` options
        block incorporation. Requires a `decide`-scope key.
        `PATCH /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}`
        (operation `setPublicRunBrainstormOptionStatus`).
        """
        raw = self._transport.request(
            "PATCH",
            f"/api/v1/runs/{_quote(run_id)}/decisions/brainstorm/{_quote(stage)}/options/{_quote(item_id)}",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def set_clarity_finding_status(self, run_id: str, item_id: str, body: PublicSetFindingStatus, timeout: float | None = None) -> PublicDecisionList:
        """Dismiss or reopen a clarity finding
        Dismiss a clarity finding as not applicable, or reopen one dismissed by mistake.
        Only `open` findings block incorporation. Requires a `decide`-scope key.
        `PATCH /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}` (operation
        `setPublicRunClarityFindingStatus`).
        """
        raw = self._transport.request(
            "PATCH",
            f"/api/v1/runs/{_quote(run_id)}/decisions/clarity/findings/{_quote(item_id)}",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)

    def set_finding_status(self, run_id: str, item_id: str, body: PublicSetFindingStatus, timeout: float | None = None) -> PublicDecisionList:
        """Dismiss or reopen a finding
        Dismiss a finding as not applicable, or reopen one dismissed by mistake. Requires a
        `decide`-scope key.
        `PATCH /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}` (operation
        `setPublicRunFindingStatus`).
        """
        raw = self._transport.request(
            "PATCH",
            f"/api/v1/runs/{_quote(run_id)}/decisions/requirements/findings/{_quote(item_id)}",
            body=_encode(body),
            query=None,
            timeout=timeout,
        )
        return PublicDecisionList.from_dict(raw)


class DebugResource:
    """A run's recorded telemetry: LLM calls, the context each agent was given, infra logs.

    """

    def __init__(self, transport: Transport) -> None:
        self._transport = transport

    def get_agent_context(self, snapshot_id: str, *, body_chars: int | None = None, body_offset: int | None = None, timeout: float | None = None) -> DebugAgentContextSnapshot:
        """Get one agent-context snapshot
        The complete context one dispatch was PROVIDED: system and user prompts, the folded
        standards fragments, and the injected `.cat-context/*` files an agent reads through
        tools (which therefore appear in no proxy telemetry). Windowed by
        `bodyOffset`/`bodyChars`.
        `GET /api/v1/debug/agent-context/{snapshotId}` (operation `getDebugAgentContext`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/agent-context/{_quote(snapshot_id)}",
            query={"bodyChars": body_chars, "bodyOffset": body_offset},
            timeout=timeout,
        )
        return DebugAgentContextSnapshot.from_dict(raw)

    def get_llm_call(self, call_id: str, *, body_chars: int | None = None, body_offset: int | None = None, view: GetDebugLlmCallView | None = None, timeout: float | None = None) -> DebugLlmCall:
        """Get one LLM call
        One recorded model call with its budgeted prompt delta, response and reasoning.
        `bodyOffset`/`bodyChars` window the bodies, so an arbitrarily long transcript is
        readable in bounded pages.
        `GET /api/v1/debug/llm-calls/{callId}` (operation `getDebugLlmCall`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/llm-calls/{_quote(call_id)}",
            query={"bodyChars": body_chars, "bodyOffset": body_offset, "view": view},
            timeout=timeout,
        )
        return DebugLlmCall.from_dict(raw)

    def get_run(self, run_id: str, timeout: float | None = None) -> DebugRunOverview:
        """Get a run's diagnostic map
        One run’s diagnostic overview: its steps, which telemetry sinks this deployment
        retains (and how much each holds), the LLM cost/latency rollups, and the derived
        signals worth looking at first.
        `GET /api/v1/debug/runs/{runId}` (operation `getDebugRun`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs/{_quote(run_id)}",
            query=None,
            timeout=timeout,
        )
        return DebugRunOverview.from_dict(raw)

    def list_agent_context(self, run_id: str, *, step_index: int | None = None, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> ListDebugAgentContextResponse:
        """List a run's agent-context dispatches
        Every dispatch whose provided context was captured, with SIZES only (no bodies) so
        the list stays bounded. Read one in full through the snapshot endpoint.
        `GET /api/v1/debug/runs/{runId}/agent-context` (operation `listDebugAgentContext`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs/{_quote(run_id)}/agent-context",
            query={"stepIndex": step_index, "limit": limit, "cursor": cursor},
            timeout=timeout,
        )
        return ListDebugAgentContextResponse.from_dict(raw)

    def list_agent_context_all(self, run_id: str, *, step_index: int | None = None, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `snapshots` across every page of `list_agent_context()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListDebugAgentContextResponse.snapshots`.
        """
        page_cursor = cursor
        while True:
            page = self.list_agent_context(run_id, step_index=step_index, limit=limit, cursor=page_cursor, timeout=timeout)
            yield from page.snapshots
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def list_llm_calls(self, run_id: str, *, agent_kind: str | None = None, phase: str | None = None, outcome: LlmCallOutcome | None = None, contains: str | None = None, order: ListDebugLlmCallsOrder | None = None, limit: int | None = None, cursor: str | None = None, body_chars: int | None = None, timeout: float | None = None) -> ListDebugLlmCallsResponse:
        """List a run's LLM calls
        The model calls a run made, keyset-paginated and filterable by agent kind, phase,
        outcome or a substring of the bodies. Bodies are returned only when `bodyChars` asks
        for them.
        `GET /api/v1/debug/runs/{runId}/llm-calls` (operation `listDebugLlmCalls`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs/{_quote(run_id)}/llm-calls",
            query={"agentKind": agent_kind, "phase": phase, "outcome": outcome, "contains": contains, "order": order, "limit": limit, "cursor": cursor, "bodyChars": body_chars},
            timeout=timeout,
        )
        return ListDebugLlmCallsResponse.from_dict(raw)

    def list_llm_calls_all(self, run_id: str, *, agent_kind: str | None = None, phase: str | None = None, outcome: LlmCallOutcome | None = None, contains: str | None = None, order: ListDebugLlmCallsOrder | None = None, limit: int | None = None, cursor: str | None = None, body_chars: int | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `calls` across every page of `list_llm_calls()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListDebugLlmCallsResponse.calls`.
        """
        page_cursor = cursor
        while True:
            page = self.list_llm_calls(run_id, agent_kind=agent_kind, phase=phase, outcome=outcome, contains=contains, order=order, limit=limit, body_chars=body_chars, cursor=page_cursor, timeout=timeout)
            yield from page.calls
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def list_logs(self, run_id: str, *, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> ListDebugLogsResponse:
        """List a run's infrastructure log
        The run’s provisioning event log — how its environment, runner pool and containers
        came up, or why they did not.
        `GET /api/v1/debug/runs/{runId}/logs` (operation `listDebugLogs`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs/{_quote(run_id)}/logs",
            query={"limit": limit, "cursor": cursor},
            timeout=timeout,
        )
        return ListDebugLogsResponse.from_dict(raw)

    def list_logs_all(self, run_id: str, *, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `entries` across every page of `list_logs()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListDebugLogsResponse.entries`.
        """
        page_cursor = cursor
        while True:
            page = self.list_logs(run_id, limit=limit, cursor=page_cursor, timeout=timeout)
            yield from page.entries
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def list_runs(self, *, status: RunStatus | None = None, since: int | None = None, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> ListDebugRunsResponse:
        """List the workspace's runs
        The triage entry point: the workspace’s runs, newest first and keyset-paginated,
        with an optional status and `since` filter.
        `GET /api/v1/debug/runs` (operation `listDebugRuns`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs",
            query={"status": status, "since": since, "limit": limit, "cursor": cursor},
            timeout=timeout,
        )
        return ListDebugRunsResponse.from_dict(raw)

    def list_runs_all(self, *, status: RunStatus | None = None, since: int | None = None, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `runs` across every page of `list_runs()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListDebugRunsResponse.runs`.
        """
        page_cursor = cursor
        while True:
            page = self.list_runs(status=status, since=since, limit=limit, cursor=page_cursor, timeout=timeout)
            yield from page.runs
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor

    def list_search_queries(self, run_id: str, *, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> ListDebugSearchQueriesResponse:
        """List a run's web searches
        The web searches the run’s agents actually performed, keyset-paginated. Retained
        only when the deployment records agent context.
        `GET /api/v1/debug/runs/{runId}/search-queries` (operation
        `listDebugSearchQueries`).
        """
        raw = self._transport.request(
            "GET",
            f"/api/v1/debug/runs/{_quote(run_id)}/search-queries",
            query={"limit": limit, "cursor": cursor},
            timeout=timeout,
        )
        return ListDebugSearchQueriesResponse.from_dict(raw)

    def list_search_queries_all(self, run_id: str, *, limit: int | None = None, cursor: str | None = None, timeout: float | None = None) -> Iterator[Any]:
        """Every `queries` across every page of `list_search_queries()`, as they arrive.
        Follows `next_cursor` until the server reports no further page. A page may
        legitimately come back empty while `next_cursor` is still set, so this pages until
        the cursor is None rather than stopping at the first empty page.
        Yields items of `ListDebugSearchQueriesResponse.queries`.
        """
        page_cursor = cursor
        while True:
            page = self.list_search_queries(run_id, limit=limit, cursor=page_cursor, timeout=timeout)
            yield from page.queries
            if not page.next_cursor:
                return
            if page.next_cursor == page_cursor:
                raise _repeated_cursor()
            page_cursor = page.next_cursor


def build_resources(transport: Transport) -> dict[str, Any]:
    """Every resource client, keyed by the attribute it is mounted at on the client."""
    return {
        "jobs": JobsResource(transport),
        "services": ServicesResource(transport),
        "tasks": TasksResource(transport),
        "pipelines": PipelinesResource(transport),
        "notifications": NotificationsResource(transport),
        "webhook": WebhookResource(transport),
        "usage": UsageResource(transport),
        "decisions": DecisionsResource(transport),
        "debug": DebugResource(transport),
    }
