// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

// The session type declarations, surface version 1.70.0: one method signature per
// `/api/v1` operation, ready to compose into the `.d.ts` an object-capability session serves
// through its `getTypeScriptTypes()`.
//
// WHAT IS DELIBERATELY ABSENT is the result shape. A session relays the deployment's own decoded
// JSON, and the authority for those shapes is the OpenAPI document this file is generated from,
// which every deployment serves at `GET /api/v1/openapi.json`. Inlining the model tree here
// would put a second copy of it inside every Worker bundle, free to disagree with the first the
// moment a consumer upgrades one and not the other. So results are `unknown` and SAY they are,
// rather than a hand-maintained subset that reads as complete.

/** One operation's session method, as the source lines a rendered `.d.ts` splices in. */
export interface SessionMethodSignature {
  /** The binding name, which is also the method's own spelling. */
  name: string
  /** The JSDoc block, indented and newline-terminated. */
  doc: string
  /** The method signature, indented and newline-terminated. */
  signature: string
}

/** Every `/api/v1` operation's session method signature, in resource-group order. */
export const SESSION_METHOD_SIGNATURES: readonly SessionMethodSignature[] = [
  {
    name: 'jobs_cancel',
    doc: '  /**\n   * Cancel a job\n   *\n   * `POST /api/v1/jobs/{id}/cancel`, scope floor `write`.\n   */\n',
    signature: '  jobs_cancel(args: { id: string }): Promise<unknown>\n',
  },
  {
    name: 'jobs_create',
    doc: '  /**\n   * Start a headless job\n   *\n   * `POST /api/v1/jobs`, scope floor `write`.\n   */\n',
    signature: '  jobs_create(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'jobs_get',
    doc: '  /**\n   * Get a job\n   *\n   * `GET /api/v1/jobs/{id}`, scope floor `read`.\n   */\n',
    signature: '  jobs_get(args: { id: string }): Promise<unknown>\n',
  },
  {
    name: 'jobs_list',
    doc: '  /**\n   * List the workspace\'s jobs\n   *\n   * `GET /api/v1/jobs`, scope floor `read`.\n   */\n',
    signature: '  jobs_list(args?: { limit?: string | number | boolean; cursor?: string | number | boolean; status?: string | number | boolean; since?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'jobs_stream',
    doc: '  /**\n   * Stream a job (SSE)\n   *\n   * `GET /api/v1/jobs/{id}/events`, scope floor `read`.\n   * Result is stream, which a session call cannot carry: this operation is withheld from every tier.\n   */\n',
    signature: '  jobs_stream(args: { id: string }): Promise<unknown>\n',
  },
  {
    name: 'services_create',
    doc: '  /**\n   * Create a service\n   *\n   * `POST /api/v1/services`, scope floor `admin`.\n   */\n',
    signature: '  services_create(args?: { body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'services_delete',
    doc: '  /**\n   * Delete a service and everything under it\n   *\n   * `DELETE /api/v1/services/{serviceId}`, scope floor `admin`.\n   */\n',
    signature: '  services_delete(args: { serviceId: string }): Promise<unknown>\n',
  },
  {
    name: 'services_list',
    doc: '  /**\n   * List the workspace\'s services\n   *\n   * `GET /api/v1/services`, scope floor `read`.\n   */\n',
    signature: '  services_list(): Promise<unknown>\n',
  },
  {
    name: 'services_update',
    doc: '  /**\n   * Patch a service, including where its per-run manifests live\n   *\n   * `PATCH /api/v1/services/{serviceId}`, scope floor `admin`.\n   */\n',
    signature: '  services_update(args: { serviceId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'spec_get',
    doc: '  /**\n   * Get a service\'s in-repo specification\n   *\n   * `GET /api/v1/services/{serviceId}/spec`, scope floor `read`.\n   */\n',
    signature: '  spec_get(args: { serviceId: string }): Promise<unknown>\n',
  },
  {
    name: 'spec_get_for_run',
    doc: '  /**\n   * Get the specification one run was judged against\n   *\n   * `GET /api/v1/runs/{runId}/spec`, scope floor `read`.\n   */\n',
    signature: '  spec_get_for_run(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'repos_bootstrap',
    doc: '  /**\n   * Create a repository and adapt it with the bootstrapper agent\n   *\n   * `POST /api/v1/repos/bootstrap`, scope floor `admin`.\n   */\n',
    signature: '  repos_bootstrap(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'repos_get_bootstrap',
    doc: '  /**\n   * Poll one repository bootstrap\n   *\n   * `GET /api/v1/repos/bootstrap/{jobId}`, scope floor `admin`.\n   */\n',
    signature: '  repos_get_bootstrap(args: { jobId: string }): Promise<unknown>\n',
  },
  {
    name: 'repos_get_file',
    doc: '  /**\n   * Read one file out of a linked repository\n   *\n   * `GET /api/v1/repos/{owner}/{name}/contents`, scope floor `admin`.\n   */\n',
    signature: '  repos_get_file(args: { owner: string; name: string; path: string | number | boolean; ref?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'repos_link',
    doc: '  /**\n   * Adopt an existing repository into this workspace\n   *\n   * `POST /api/v1/repos/link`, scope floor `admin`.\n   */\n',
    signature: '  repos_link(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'repos_list',
    doc: '  /**\n   * List the repositories a service can be created against\n   *\n   * `GET /api/v1/repos`, scope floor `read`.\n   */\n',
    signature: '  repos_list(): Promise<unknown>\n',
  },
  {
    name: 'repos_list_available',
    doc: '  /**\n   * List the repositories this workspace could adopt\n   *\n   * `GET /api/v1/repos/available`, scope floor `admin`.\n   */\n',
    signature: '  repos_list_available(args?: { q?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'tasks_add_dependency',
    doc: '  /**\n   * Declare that a task waits for another\n   *\n   * `POST /api/v1/tasks/{taskId}/dependencies`, scope floor `write`.\n   */\n',
    signature: '  tasks_add_dependency(args: { taskId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_attach_document',
    doc: '  /**\n   * Attach a document to a task\n   *\n   * `POST /api/v1/tasks/{taskId}/documents`, scope floor `write`.\n   */\n',
    signature: '  tasks_attach_document(args: { taskId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_create',
    doc: '  /**\n   * Create a task under a service\n   *\n   * `POST /api/v1/services/{serviceId}/tasks`, scope floor `write`.\n   */\n',
    signature: '  tasks_create(args: { serviceId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_delete',
    doc: '  /**\n   * Delete a task\n   *\n   * `DELETE /api/v1/tasks/{taskId}`, scope floor `admin`.\n   */\n',
    signature: '  tasks_delete(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_detach_document',
    doc: '  /**\n   * Detach a document from a task\n   *\n   * `POST /api/v1/tasks/{taskId}/documents/detach`, scope floor `write`.\n   */\n',
    signature: '  tasks_detach_document(args: { taskId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_get',
    doc: '  /**\n   * Get a task\'s status\n   *\n   * `GET /api/v1/tasks/{taskId}`, scope floor `read`.\n   */\n',
    signature: '  tasks_get(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_get_run',
    doc: '  /**\n   * Get a task\'s run (rich projection)\n   *\n   * `GET /api/v1/tasks/{taskId}/run`, scope floor `read`.\n   */\n',
    signature: '  tasks_get_run(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_list_by_service',
    doc: '  /**\n   * List a service\'s tasks\n   *\n   * `GET /api/v1/services/{serviceId}/tasks`, scope floor `read`.\n   */\n',
    signature: '  tasks_list_by_service(args: { serviceId: string; limit?: string | number | boolean; cursor?: string | number | boolean; status?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'tasks_list_documents',
    doc: '  /**\n   * List a task\'s attached documents\n   *\n   * `GET /api/v1/tasks/{taskId}/documents`, scope floor `read`.\n   */\n',
    signature: '  tasks_list_documents(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_remove_dependency',
    doc: '  /**\n   * Drop a dependency edge\n   *\n   * `POST /api/v1/tasks/{taskId}/dependencies/remove`, scope floor `write`.\n   */\n',
    signature: '  tasks_remove_dependency(args: { taskId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_retry',
    doc: '  /**\n   * Retry a task\'s failed run\n   *\n   * `POST /api/v1/tasks/{taskId}/retry`, scope floor `write`.\n   */\n',
    signature: '  tasks_retry(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_start',
    doc: '  /**\n   * Start (run) a task\n   *\n   * `POST /api/v1/tasks/{taskId}/start`, scope floor `write`.\n   */\n',
    signature: '  tasks_start(args: { taskId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'tasks_stop',
    doc: '  /**\n   * Stop a task\'s run\n   *\n   * `POST /api/v1/tasks/{taskId}/stop`, scope floor `write`.\n   */\n',
    signature: '  tasks_stop(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_stream',
    doc: '  /**\n   * Stream a task run (SSE)\n   *\n   * `GET /api/v1/tasks/{taskId}/events`, scope floor `read`.\n   * Result is stream, which a session call cannot carry: this operation is withheld from every tier.\n   */\n',
    signature: '  tasks_stream(args: { taskId: string }): Promise<unknown>\n',
  },
  {
    name: 'tasks_update',
    doc: '  /**\n   * Edit a task\'s inputs\n   *\n   * `PATCH /api/v1/tasks/{taskId}`, scope floor `write`.\n   */\n',
    signature: '  tasks_update(args: { taskId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'pipelines_list',
    doc: '  /**\n   * List the workspace\'s pipelines\n   *\n   * `GET /api/v1/pipelines`, scope floor `read`.\n   */\n',
    signature: '  pipelines_list(): Promise<unknown>\n',
  },
  {
    name: 'task_types_list',
    doc: '  /**\n   * List the task types this workspace may create\n   *\n   * `GET /api/v1/task-types`, scope floor `read`.\n   */\n',
    signature: '  task_types_list(): Promise<unknown>\n',
  },
  {
    name: 'use_cases_get',
    doc: '  /**\n   * Get one use case\n   *\n   * `GET /api/v1/use-cases/{useCaseId}`, scope floor `read`.\n   */\n',
    signature: '  use_cases_get(args: { useCaseId: string }): Promise<unknown>\n',
  },
  {
    name: 'use_cases_invoke',
    doc: '  /**\n   * Run a use case\n   *\n   * `POST /api/v1/use-cases/{useCaseId}/invocations`, scope floor `write`.\n   */\n',
    signature: '  use_cases_invoke(args: { useCaseId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'use_cases_list',
    doc: '  /**\n   * List the deployment\'s inline use cases\n   *\n   * `GET /api/v1/use-cases`, scope floor `read`.\n   */\n',
    signature: '  use_cases_list(): Promise<unknown>\n',
  },
  {
    name: 'notifications_act',
    doc: '  /**\n   * Act on a notification\n   *\n   * `POST /api/v1/notifications/{id}/act`, scope floor `admin`.\n   */\n',
    signature: '  notifications_act(args: { id: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'notifications_dismiss',
    doc: '  /**\n   * Dismiss a notification\n   *\n   * `POST /api/v1/notifications/{id}/dismiss`, scope floor `write`.\n   */\n',
    signature: '  notifications_dismiss(args: { id: string }): Promise<unknown>\n',
  },
  {
    name: 'notifications_list',
    doc: '  /**\n   * List the workspace\'s open notifications\n   *\n   * `GET /api/v1/notifications`, scope floor `read`.\n   */\n',
    signature: '  notifications_list(): Promise<unknown>\n',
  },
  {
    name: 'environments_connect',
    doc: '  /**\n   * Connect the workspace to the cluster its environments deploy onto\n   *\n   * `POST /api/v1/environments/connections`, scope floor `admin`.\n   */\n',
    signature: '  environments_connect(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'environments_list_connections',
    doc: '  /**\n   * List the environment connections this workspace holds\n   *\n   * `GET /api/v1/environments/connections`, scope floor `admin`.\n   */\n',
    signature: '  environments_list_connections(): Promise<unknown>\n',
  },
  {
    name: 'environments_list_manifest_types',
    doc: '  /**\n   * List the custom manifest types a service can pin\n   *\n   * `GET /api/v1/environments/manifest-types`, scope floor `admin`.\n   */\n',
    signature: '  environments_list_manifest_types(): Promise<unknown>\n',
  },
  {
    name: 'environments_test_connection',
    doc: '  /**\n   * Probe a candidate cluster connection without saving it\n   *\n   * `POST /api/v1/environments/connections/test`, scope floor `admin`.\n   */\n',
    signature: '  environments_test_connection(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'models_list',
    doc: '  /**\n   * List the models a run in this workspace could dispatch to\n   *\n   * `GET /api/v1/models`, scope floor `admin`.\n   */\n',
    signature: '  models_list(): Promise<unknown>\n',
  },
  {
    name: 'vcs_get_connection',
    doc: '  /**\n   * Read the workspace’s source-control connection and what it may do\n   *\n   * `GET /api/v1/vcs/connection`, scope floor `admin`.\n   */\n',
    signature: '  vcs_get_connection(): Promise<unknown>\n',
  },
  {
    name: 'tracker_get_writeback',
    doc: '  /**\n   * Read the workspace’s tracker writeback disposition\n   *\n   * `GET /api/v1/tracker/writeback`, scope floor `admin`.\n   */\n',
    signature: '  tracker_get_writeback(): Promise<unknown>\n',
  },
  {
    name: 'tracker_update_writeback',
    doc: '  /**\n   * Change the workspace’s tracker writeback disposition\n   *\n   * `PATCH /api/v1/tracker/writeback`, scope floor `admin`.\n   */\n',
    signature: '  tracker_update_writeback(args?: { body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'risk_policies_list',
    doc: '  /**\n   * List the workspace’s risk policies\n   *\n   * `GET /api/v1/risk-policies`, scope floor `admin`.\n   */\n',
    signature: '  risk_policies_list(): Promise<unknown>\n',
  },
  {
    name: 'model_presets_list',
    doc: '  /**\n   * List the workspace’s model presets\n   *\n   * `GET /api/v1/model-presets`, scope floor `admin`.\n   */\n',
    signature: '  model_presets_list(): Promise<unknown>\n',
  },
  {
    name: 'webhook_delete',
    doc: '  /**\n   * Remove the outbound webhook\n   *\n   * `DELETE /api/v1/notification-webhook`, scope floor `admin`.\n   */\n',
    signature: '  webhook_delete(): Promise<unknown>\n',
  },
  {
    name: 'webhook_delete_named',
    doc: '  /**\n   * Remove one named outbound webhook\n   *\n   * `DELETE /api/v1/notification-webhooks/{webhookId}`, scope floor `admin`.\n   */\n',
    signature: '  webhook_delete_named(args: { webhookId: string }): Promise<unknown>\n',
  },
  {
    name: 'webhook_get',
    doc: '  /**\n   * Read the workspace\'s outbound webhook\n   *\n   * `GET /api/v1/notification-webhook`, scope floor `admin`.\n   */\n',
    signature: '  webhook_get(): Promise<unknown>\n',
  },
  {
    name: 'webhook_get_named',
    doc: '  /**\n   * Read one named outbound webhook\n   *\n   * `GET /api/v1/notification-webhooks/{webhookId}`, scope floor `admin`.\n   */\n',
    signature: '  webhook_get_named(args: { webhookId: string }): Promise<unknown>\n',
  },
  {
    name: 'webhook_list',
    doc: '  /**\n   * List the workspace\'s outbound webhooks\n   *\n   * `GET /api/v1/notification-webhooks`, scope floor `admin`.\n   */\n',
    signature: '  webhook_list(): Promise<unknown>\n',
  },
  {
    name: 'webhook_set',
    doc: '  /**\n   * Register or update the outbound webhook\n   *\n   * `PUT /api/v1/notification-webhook`, scope floor `admin`.\n   */\n',
    signature: '  webhook_set(args?: { body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'webhook_set_named',
    doc: '  /**\n   * Register or update one named outbound webhook\n   *\n   * `PUT /api/v1/notification-webhooks/{webhookId}`, scope floor `admin`.\n   */\n',
    signature: '  webhook_set_named(args: { webhookId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'usage_get',
    doc: '  /**\n   * Read the workspace\'s usage for the current period\n   *\n   * `GET /api/v1/usage`, scope floor `read`.\n   */\n',
    signature: '  usage_get(): Promise<unknown>\n',
  },
  {
    name: 'usage_spend',
    doc: '  /**\n   * Break the workspace\'s spend down by repository, ticket, run or step kind\n   *\n   * `GET /api/v1/usage/spend`, scope floor `read`.\n   */\n',
    signature: '  usage_spend(args: { dimension: string | number | boolean; window?: string | number | boolean; limit?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'me_get',
    doc: '  /**\n   * Describe the calling key\n   *\n   * `GET /api/v1/me`, scope floor `read`.\n   */\n',
    signature: '  me_get(): Promise<unknown>\n',
  },
  {
    name: 'decisions_answer_agent_decision',
    doc: '  /**\n   * Answer an agent-raised decision\n   *\n   * `POST /api/v1/runs/{runId}/decisions/questions/{decisionId}/answer`, scope floor `decide`.\n   */\n',
    signature: '  decisions_answer_agent_decision(args: { runId: string; decisionId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_answer_follow_up',
    doc: '  /**\n   * Answer a follow-up question\n   *\n   * `POST /api/v1/runs/{runId}/decisions/follow-ups/items/{itemId}/answer`, scope floor `decide`.\n   */\n',
    signature: '  decisions_answer_follow_up(args: { runId: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_answer_interview_question',
    doc: '  /**\n   * Answer an interview question\n   *\n   * `POST /api/v1/runs/{runId}/decisions/interview/answer`, scope floor `decide`.\n   */\n',
    signature: '  decisions_answer_interview_question(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_approve_step',
    doc: '  /**\n   * Approve a parked step\n   *\n   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/approve`, scope floor `decide`.\n   */\n',
    signature: '  decisions_approve_step(args: { runId: string; approvalId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_approve_visual_confirmation',
    doc: '  /**\n   * Approve a visual-confirmation gate\n   *\n   * `POST /api/v1/runs/{runId}/decisions/visual-confirmation/approve`, scope floor `decide`.\n   */\n',
    signature: '  decisions_approve_visual_confirmation(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_challenge_pr_review_finding',
    doc: '  /**\n   * Challenge a PR review finding\n   *\n   * `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/challenge`, scope floor `decide`.\n   */\n',
    signature: '  decisions_challenge_pr_review_finding(args: { runId: string; findingId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_choose_fork',
    doc: '  /**\n   * Choose an implementation approach\n   *\n   * `POST /api/v1/runs/{runId}/decisions/fork/choose`, scope floor `decide`.\n   */\n',
    signature: '  decisions_choose_fork(args: { runId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_confirm_human_test',
    doc: '  /**\n   * Confirm a human-test gate\n   *\n   * `POST /api/v1/runs/{runId}/decisions/human-test/confirm`, scope floor `decide`.\n   */\n',
    signature: '  decisions_confirm_human_test(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_continue_interview',
    doc: '  /**\n   * Continue a parked interview\n   *\n   * `POST /api/v1/runs/{runId}/decisions/interview/continue`, scope floor `decide`.\n   */\n',
    signature: '  decisions_continue_interview(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_dismiss_follow_up',
    doc: '  /**\n   * Dismiss a follow-up item\n   *\n   * `POST /api/v1/runs/{runId}/decisions/follow-ups/items/{itemId}/dismiss`, scope floor `decide`.\n   */\n',
    signature: '  decisions_dismiss_follow_up(args: { runId: string; itemId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_dismiss_pr_review_finding',
    doc: '  /**\n   * Dismiss a PR review finding\n   *\n   * `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/dismiss`, scope floor `decide`.\n   */\n',
    signature: '  decisions_dismiss_pr_review_finding(args: { runId: string; findingId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_file_follow_up',
    doc: '  /**\n   * File a follow-up item as an issue\n   *\n   * `POST /api/v1/runs/{runId}/decisions/follow-ups/items/{itemId}/file`, scope floor `decide`.\n   */\n',
    signature: '  decisions_file_follow_up(args: { runId: string; itemId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_incorporate',
    doc: '  /**\n   * Incorporate the answers\n   *\n   * `POST /api/v1/runs/{runId}/decisions/requirements/incorporate`, scope floor `decide`.\n   */\n',
    signature: '  decisions_incorporate(args: { runId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_incorporate_brainstorm',
    doc: '  /**\n   * Incorporate brainstorm picks\n   *\n   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/incorporate`, scope floor `decide`.\n   */\n',
    signature: '  decisions_incorporate_brainstorm(args: { runId: string; stage: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_incorporate_clarity',
    doc: '  /**\n   * Incorporate clarity answers\n   *\n   * `POST /api/v1/runs/{runId}/decisions/clarity/incorporate`, scope floor `decide`.\n   */\n',
    signature: '  decisions_incorporate_clarity(args: { runId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_list',
    doc: '  /**\n   * List a run\'s parked decisions\n   *\n   * `GET /api/v1/runs/{runId}/decisions`, scope floor `read`.\n   */\n',
    signature: '  decisions_list(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_proceed',
    doc: '  /**\n   * Proceed with the current requirements\n   *\n   * `POST /api/v1/runs/{runId}/decisions/requirements/proceed`, scope floor `decide`.\n   */\n',
    signature: '  decisions_proceed(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_proceed_brainstorm',
    doc: '  /**\n   * Proceed past a brainstorm\n   *\n   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/proceed`, scope floor `decide`.\n   */\n',
    signature: '  decisions_proceed_brainstorm(args: { runId: string; stage: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_proceed_clarity',
    doc: '  /**\n   * Proceed past the clarity review\n   *\n   * `POST /api/v1/runs/{runId}/decisions/clarity/proceed`, scope floor `decide`.\n   */\n',
    signature: '  decisions_proceed_clarity(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_proceed_interview',
    doc: '  /**\n   * Proceed past a parked interview\n   *\n   * `POST /api/v1/runs/{runId}/decisions/interview/proceed`, scope floor `decide`.\n   */\n',
    signature: '  decisions_proceed_interview(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_reject_step',
    doc: '  /**\n   * Reject a parked step\n   *\n   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/reject`, scope floor `decide`.\n   */\n',
    signature: '  decisions_reject_step(args: { runId: string; approvalId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_reply_to_brainstorm_option',
    doc: '  /**\n   * Respond to a brainstorm option\n   *\n   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}/reply`, scope floor `decide`.\n   */\n',
    signature: '  decisions_reply_to_brainstorm_option(args: { runId: string; stage: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_reply_to_clarity_finding',
    doc: '  /**\n   * Answer a clarity (bug-triage) finding\n   *\n   * `POST /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}/reply`, scope floor `decide`.\n   */\n',
    signature: '  decisions_reply_to_clarity_finding(args: { runId: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_reply_to_finding',
    doc: '  /**\n   * Answer a review finding\n   *\n   * `POST /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}/reply`, scope floor `decide`.\n   */\n',
    signature: '  decisions_reply_to_finding(args: { runId: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_request_human_test_fix',
    doc: '  /**\n   * Request a fix from a human-test gate\n   *\n   * `POST /api/v1/runs/{runId}/decisions/human-test/request-fix`, scope floor `decide`.\n   */\n',
    signature: '  decisions_request_human_test_fix(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_request_step_changes',
    doc: '  /**\n   * Request changes on a parked step\n   *\n   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/request-changes`, scope floor `decide`.\n   */\n',
    signature: '  decisions_request_step_changes(args: { runId: string; approvalId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_request_visual_confirmation_fix',
    doc: '  /**\n   * Request a fix from a visual-confirmation gate\n   *\n   * `POST /api/v1/runs/{runId}/decisions/visual-confirmation/request-fix`, scope floor `decide`.\n   */\n',
    signature: '  decisions_request_visual_confirmation_fix(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_re_review',
    doc: '  /**\n   * Re-review the incorporated document\n   *\n   * `POST /api/v1/runs/{runId}/decisions/requirements/re-review`, scope floor `decide`.\n   */\n',
    signature: '  decisions_re_review(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_re_review_brainstorm',
    doc: '  /**\n   * Re-run a brainstorm pass\n   *\n   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/re-review`, scope floor `decide`.\n   */\n',
    signature: '  decisions_re_review_brainstorm(args: { runId: string; stage: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_re_review_clarity',
    doc: '  /**\n   * Re-triage the clarified report\n   *\n   * `POST /api/v1/runs/{runId}/decisions/clarity/re-review`, scope floor `decide`.\n   */\n',
    signature: '  decisions_re_review_clarity(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_brainstorm_exceeded',
    doc: '  /**\n   * Resolve a brainstorm at its iteration cap\n   *\n   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/resolve-exceeded`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_brainstorm_exceeded(args: { runId: string; stage: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_clarity_exceeded',
    doc: '  /**\n   * Resolve a clarity review at its iteration cap\n   *\n   * `POST /api/v1/runs/{runId}/decisions/clarity/resolve-exceeded`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_clarity_exceeded(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_exceeded',
    doc: '  /**\n   * Resolve a review at its iteration cap\n   *\n   * `POST /api/v1/runs/{runId}/decisions/requirements/resolve-exceeded`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_exceeded(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_input_gate',
    doc: '  /**\n   * Resolve a run parked on the task\'s input check\n   *\n   * `POST /api/v1/runs/{runId}/decisions/input-gate/resolve`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_input_gate(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_judge',
    doc: '  /**\n   * Resolve a parked judge verdict\n   *\n   * `POST /api/v1/runs/{runId}/decisions/judge/resolve`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_judge(args: { runId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_pr_review',
    doc: '  /**\n   * Resolve a parked PR deep review\n   *\n   * `POST /api/v1/runs/{runId}/decisions/pr-review/resolve`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_pr_review(args: { runId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_resolve_step_exceeded',
    doc: '  /**\n   * Resolve a companion gate at its rework cap\n   *\n   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/resolve-exceeded`, scope floor `decide`.\n   */\n',
    signature: '  decisions_resolve_step_exceeded(args: { runId: string; approvalId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_send_back_follow_up',
    doc: '  /**\n   * Send a follow-up item back to the Coder\n   *\n   * `POST /api/v1/runs/{runId}/decisions/follow-ups/items/{itemId}/send-back`, scope floor `decide`.\n   */\n',
    signature: '  decisions_send_back_follow_up(args: { runId: string; itemId: string }): Promise<unknown>\n',
  },
  {
    name: 'decisions_set_brainstorm_option_status',
    doc: '  /**\n   * Dismiss or reopen a brainstorm option\n   *\n   * `PATCH /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}`, scope floor `decide`.\n   */\n',
    signature: '  decisions_set_brainstorm_option_status(args: { runId: string; stage: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_set_clarity_finding_status',
    doc: '  /**\n   * Dismiss or reopen a clarity finding\n   *\n   * `PATCH /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}`, scope floor `decide`.\n   */\n',
    signature: '  decisions_set_clarity_finding_status(args: { runId: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'decisions_set_finding_status',
    doc: '  /**\n   * Dismiss or reopen a finding\n   *\n   * `PATCH /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}`, scope floor `decide`.\n   */\n',
    signature: '  decisions_set_finding_status(args: { runId: string; itemId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'debug_get_agent_context',
    doc: '  /**\n   * Get one agent-context snapshot\n   *\n   * `GET /api/v1/debug/agent-context/{snapshotId}`, scope floor `read`.\n   */\n',
    signature: '  debug_get_agent_context(args: { snapshotId: string; bodyChars?: string | number | boolean; bodyOffset?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_get_llm_call',
    doc: '  /**\n   * Get one LLM call\n   *\n   * `GET /api/v1/debug/llm-calls/{callId}`, scope floor `read`.\n   */\n',
    signature: '  debug_get_llm_call(args: { callId: string; bodyChars?: string | number | boolean; bodyOffset?: string | number | boolean; view?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_get_llm_export',
    doc: '  /**\n   * Export a run\'s model activity as one bundle\n   *\n   * `GET /api/v1/debug/runs/{runId}/llm-export`, scope floor `read`.\n   */\n',
    signature: '  debug_get_llm_export(args: { runId: string; limit?: string | number | boolean; order?: string | number | boolean; bodyChars?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_get_run',
    doc: '  /**\n   * Get a run\'s diagnostic map\n   *\n   * `GET /api/v1/debug/runs/{runId}`, scope floor `read`.\n   */\n',
    signature: '  debug_get_run(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_agent_context',
    doc: '  /**\n   * List a run\'s agent-context dispatches\n   *\n   * `GET /api/v1/debug/runs/{runId}/agent-context`, scope floor `read`.\n   */\n',
    signature: '  debug_list_agent_context(args: { runId: string; stepIndex?: string | number | boolean; limit?: string | number | boolean; cursor?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_llm_calls',
    doc: '  /**\n   * List a run\'s LLM calls\n   *\n   * `GET /api/v1/debug/runs/{runId}/llm-calls`, scope floor `read`.\n   */\n',
    signature: '  debug_list_llm_calls(args: { runId: string; agentKind?: string | number | boolean; phase?: string | number | boolean; outcome?: string | number | boolean; contains?: string | number | boolean; order?: string | number | boolean; limit?: string | number | boolean; cursor?: string | number | boolean; bodyChars?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_logs',
    doc: '  /**\n   * List a run\'s infrastructure log\n   *\n   * `GET /api/v1/debug/runs/{runId}/logs`, scope floor `read`.\n   */\n',
    signature: '  debug_list_logs(args: { runId: string; limit?: string | number | boolean; cursor?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_runs',
    doc: '  /**\n   * List the workspace\'s runs\n   *\n   * `GET /api/v1/debug/runs`, scope floor `read`.\n   */\n',
    signature: '  debug_list_runs(args?: { status?: string | number | boolean; since?: string | number | boolean; limit?: string | number | boolean; cursor?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_search_queries',
    doc: '  /**\n   * List a run\'s web searches\n   *\n   * `GET /api/v1/debug/runs/{runId}/search-queries`, scope floor `read`.\n   */\n',
    signature: '  debug_list_search_queries(args: { runId: string; limit?: string | number | boolean; cursor?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'debug_list_tool_calls',
    doc: '  /**\n   * List a run\'s tool calls\n   *\n   * `GET /api/v1/debug/runs/{runId}/tool-calls`, scope floor `read`.\n   */\n',
    signature: '  debug_list_tool_calls(args: { runId: string; limit?: string | number | boolean; cursor?: string | number | boolean; jobId?: string | number | boolean; order?: string | number | boolean; outcome?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'evidence_download_artifact',
    doc: '  /**\n   * Download an artifact\'s bytes\n   *\n   * `GET /api/v1/artifacts/{artifactId}/blob`, scope floor `read`.\n   * Result is binary, which a session call cannot carry: this operation is withheld from every tier.\n   */\n',
    signature: '  evidence_download_artifact(args: { artifactId: string }): Promise<unknown>\n',
  },
  {
    name: 'evidence_get_outcome',
    doc: '  /**\n   * Get a run\'s outcome summary\n   *\n   * `GET /api/v1/runs/{runId}/outcome`, scope floor `read`.\n   */\n',
    signature: '  evidence_get_outcome(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'evidence_get_report',
    doc: '  /**\n   * Get a run\'s verification report\n   *\n   * `GET /api/v1/runs/{runId}/report`, scope floor `read`.\n   */\n',
    signature: '  evidence_get_report(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'evidence_list_artifacts',
    doc: '  /**\n   * List a run\'s captured artifacts\n   *\n   * `GET /api/v1/runs/{runId}/artifacts`, scope floor `read`.\n   */\n',
    signature: '  evidence_list_artifacts(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'merge_records_get',
    doc: '  /**\n   * Get one merge record\n   *\n   * `GET /api/v1/merge-records/{recordId}`, scope floor `read`.\n   */\n',
    signature: '  merge_records_get(args: { recordId: string }): Promise<unknown>\n',
  },
  {
    name: 'merge_records_get_for_run',
    doc: '  /**\n   * Get the merge decision a run left behind\n   *\n   * `GET /api/v1/runs/{runId}/merge-record`, scope floor `read`.\n   */\n',
    signature: '  merge_records_get_for_run(args: { runId: string }): Promise<unknown>\n',
  },
  {
    name: 'merge_records_list_rollups',
    doc: '  /**\n   * List the per-change-class merge rollups\n   *\n   * `GET /api/v1/merge-records/rollups`, scope floor `read`.\n   */\n',
    signature: '  merge_records_list_rollups(): Promise<unknown>\n',
  },
  {
    name: 'merge_records_tag_effort',
    doc: '  /**\n   * Tag the reviewer effort a merge took\n   *\n   * `POST /api/v1/merge-records/{recordId}/effort`, scope floor `write`.\n   */\n',
    signature: '  merge_records_tag_effort(args: { recordId: string; body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'kaizen_acknowledge_entry',
    doc: '  /**\n   * Acknowledge a Kaizen entry\n   *\n   * `POST /api/v1/kaizen/entries/{entryId}/acknowledge`, scope floor `write`.\n   */\n',
    signature: '  kaizen_acknowledge_entry(args: { entryId: string; body?: unknown }): Promise<unknown>\n',
  },
  {
    name: 'kaizen_get_entry',
    doc: '  /**\n   * Get one Kaizen entry\n   *\n   * `GET /api/v1/kaizen/entries/{entryId}`, scope floor `read`.\n   */\n',
    signature: '  kaizen_get_entry(args: { entryId: string }): Promise<unknown>\n',
  },
  {
    name: 'kaizen_list_entries',
    doc: '  /**\n   * List the workspace\'s Kaizen entries\n   *\n   * `GET /api/v1/kaizen/entries`, scope floor `read`.\n   */\n',
    signature: '  kaizen_list_entries(args?: { limit?: string | number | boolean; cursor?: string | number | boolean; acknowledged?: string | number | boolean; settled?: string | number | boolean; status?: string | number | boolean; agentKind?: string | number | boolean; since?: string | number | boolean }): Promise<unknown>\n',
  },
  {
    name: 'keys_create',
    doc: '  /**\n   * Provision an API key\n   *\n   * `POST /api/v1/keys`, scope floor `admin`.\n   */\n',
    signature: '  keys_create(args: { body: unknown }): Promise<unknown>\n',
  },
  {
    name: 'keys_list',
    doc: '  /**\n   * List the workspace\'s API keys\n   *\n   * `GET /api/v1/keys`, scope floor `admin`.\n   */\n',
    signature: '  keys_list(): Promise<unknown>\n',
  },
  {
    name: 'keys_revoke',
    doc: '  /**\n   * Revoke an API key\n   *\n   * `DELETE /api/v1/keys/{keyId}`, scope floor `admin`.\n   */\n',
    signature: '  keys_revoke(args: { keyId: string }): Promise<unknown>\n',
  },
]
