// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

// Wire models for the cat-factory public API (`/api/v1`), surface version 1.4.0.
//
// A field declared `T | null` is ALWAYS SENT and may hold null; a field declared `?` may be
// absent entirely. The two are kept apart on purpose — "the server said null" and "the server
// said nothing" are different facts, and a caller that cannot tell them apart cannot report
// either one honestly.

export interface CreatePublicJob {
  /** Length 1..50000. */
  input: string
  /** Length 1..∞. */
  pipelineId: string
  /** Length 0..200. */
  title?: string
}

export interface CreatePublicTask {
  /** Length 0..2000. */
  description?: string
  taskType?: 'feature' | 'bug' | 'document' | 'spike' | 'review' | 'ralph' | (string & {})
  ticket?: PublicTaskTicket
  /** Length 1..200. */
  title: string
}

export interface DebugAgentContextSnapshot {
  agentKind: string
  contextFiles: DebugContextFile[]
  createdAt: number
  extras: Record<string, unknown>
  fragments: DebugContextFragment[]
  /** Always present; `null` when the server has no value for it. */
  harness: string | null
  /** Always present; `null` when the server has no value for it. */
  model: string | null
  runId: string
  snapshotId: string
  stepIndex: number
  systemPrompt: DebugText
  userPrompt: DebugText
}

export interface DebugAgentContextSummary {
  agentKind: string
  contextFilesChars: number
  createdAt: number
  fragmentsChars: number
  /** Always present; `null` when the server has no value for it. */
  harness: string | null
  /** Always present; `null` when the server has no value for it. */
  model: string | null
  snapshotId: string
  stepIndex: number
  systemPromptChars: number
  userPromptChars: number
}

export interface DebugContextFile {
  content: DebugText
  path: string
  title: string
  url: string
}

export interface DebugContextFragment {
  body: DebugText
  id: string
}

export interface DebugInfraLogEntry {
  /** Always present; `null` when the server has no value for it. */
  blockId: string | null
  createdAt: number
  /** Always present; `null` when the server has no value for it. */
  detail: string | null
  /** Always present; `null` when the server has no value for it. */
  error: string | null
  /** Always present; `null` when the server has no value for it. */
  executionId: string | null
  id: string
  operation: DebugInfraLogEntryOperation
  outcome: DebugInfraLogEntryOutcome
  /** Always present; `null` when the server has no value for it. */
  providerId: string | null
  subsystem: DebugInfraLogEntrySubsystem
  /** Always present; `null` when the server has no value for it. */
  targetId: string | null
  workspaceId: string
}

export type DebugInfraLogEntryOperation = 'provision' | 'teardown' | 'status' | 'dispatch' | 'release' | 'poll-failure'

/** Every `DebugInfraLogEntryOperation` value, for exhaustive handling and runtime validation. */
export const DEBUG_INFRA_LOG_ENTRY_OPERATION_VALUES = ['provision', 'teardown', 'status', 'dispatch', 'release', 'poll-failure'] as const

export type DebugInfraLogEntryOutcome = 'success' | 'failure'

/** Every `DebugInfraLogEntryOutcome` value, for exhaustive handling and runtime validation. */
export const DEBUG_INFRA_LOG_ENTRY_OUTCOME_VALUES = ['success', 'failure'] as const

export type DebugInfraLogEntrySubsystem = 'environment' | 'runner-pool' | 'container'

/** Every `DebugInfraLogEntrySubsystem` value, for exhaustive handling and runtime validation. */
export const DEBUG_INFRA_LOG_ENTRY_SUBSYSTEM_VALUES = ['environment', 'runner-pool', 'container'] as const

export interface DebugLlmAgentKindRollup {
  agentKind: string
  /** Always present; `null` when the server has no value for it. */
  cacheHitRate: number | null
  cacheReadTokens: number
  cacheWriteTokens: number
  calls: number
  completionTokens: number
  /** Always present; `null` when the server has no value for it. */
  costEstimate: number | null
  errors: number
  /** Always present; `null` when the server has no value for it. */
  maxOutputTokens: number | null
  /** Always present; `null` when the server has no value for it. */
  outputHeadroomRatio: number | null
  overheadMs: number
  peakCompletionTokens: number
  promptTokens: number
  /** Always present; `null` when the server has no value for it. */
  transportOverheadRatio: number | null
  truncatedCalls: number
  upstreamMs: number
  warnings: number
}

export interface DebugLlmCall {
  agentKind: string
  cacheReadTokens: number
  cacheWriteTokens: number
  callId: string
  completionTokens: number
  createdAt: number
  elidedLeadingMessages: number
  /** Always present; `null` when the server has no value for it. */
  errorMessage: string | null
  /** Always present; `null` when the server has no value for it. */
  finishReason: string | null
  /** Always present; `null` when the server has no value for it. */
  httpStatus: number | null
  messageCount: number
  model: string
  ok: boolean
  outcome: LlmCallOutcome
  overheadMs: number
  phase: string
  prompt: DebugText
  promptMessages?: DebugPromptMessage[] | null
  promptTokens: number
  provider: string
  reasoning: DebugText
  /** Always present; `null` when the server has no value for it. */
  requestMaxTokens: number | null
  response: DebugText
  /** Always present; `null` when the server has no value for it. */
  runId: string | null
  streaming: boolean
  toolCount: number
  totalMs: number
  totalTokens: number
  /** Always present; `null` when the server has no value for it. */
  turnIndex: number | null
  upstreamMs: number
}

export interface DebugLlmPhaseRollup {
  /** Always present; `null` when the server has no value for it. */
  cacheHitRate: number | null
  cacheReadTokens: number
  cacheWriteTokens: number
  calls: number
  /** Always present; `null` when the server has no value for it. */
  carryCostShare: number | null
  carryCostTokens: number
  completionTokens: number
  /** Always present; `null` when the server has no value for it. */
  costEstimate: number | null
  errors: number
  overheadMs: number
  phase: string
  promptTokens: number
  truncatedCalls: number
  upstreamMs: number
  warnings: number
}

export interface DebugLlmTotals {
  /** Always present; `null` when the server has no value for it. */
  cacheHitRate: number | null
  cacheReadTokens: number
  cacheWriteTokens: number
  calls: number
  completionTokens: number
  /** Always present; `null` when the server has no value for it. */
  costEstimate: number | null
  errors: number
  overheadMs: number
  promptTokens: number
  /** Always present; `null` when the server has no value for it. */
  transportOverheadRatio: number | null
  truncatedCalls: number
  upstreamMs: number
  warnings: number
}

export interface DebugPromptMessage {
  content: DebugText
  index: number
  /** Always present; `null` when the server has no value for it. */
  name: string | null
  role: string
  /** Always present; `null` when the server has no value for it. */
  toolCallId: string | null
  toolCalls: DebugToolCall[]
}

export interface DebugRunFailure {
  /** Always present; `null` when the server has no value for it. */
  detail: string | null
  /** Always present; `null` when the server has no value for it. */
  hint: string | null
  kind: DebugRunFailureKind
  /** Always present; `null` when the server has no value for it. */
  lastSubtasks: DebugSubtaskCounts | null
  message: string
  occurredAt: number
  reason?: string | null
  stepIndex?: number
}

export type DebugRunFailureKind = 'preflight' | 'dispatch' | 'environment' | 'evicted' | 'timeout' | 'agent' | 'job_failed' | 'rejected' | 'companion_rejected' | 'stalled' | 'cancelled' | 'unknown'

/** Every `DebugRunFailureKind` value, for exhaustive handling and runtime validation. */
export const DEBUG_RUN_FAILURE_KIND_VALUES = ['preflight', 'dispatch', 'environment', 'evicted', 'timeout', 'agent', 'job_failed', 'rejected', 'companion_rejected', 'stalled', 'cancelled', 'unknown'] as const

export interface DebugRunOverview {
  /** Always present; `null` when the server has no value for it. */
  diagnostics: DebugRunOverviewDiagnostics | null
  generatedAt: number
  kind: 'cat-factory.run-debug-overview'
  llm: DebugRunOverviewLlm
  run: DebugRunSummary
  signals: DebugRunSignal[]
  sinks: DebugRunOverviewSinks
  steps: DebugRunStep[]
  version: 1
}

export interface DebugRunOverviewDiagnostics {
  host?: DebugRunOverviewDiagnosticsHost
  lastDispatch?: DebugRunOverviewDiagnosticsLastDispatch
}

export interface DebugRunOverviewDiagnosticsHost {
  platform?: string
}

export interface DebugRunOverviewDiagnosticsLastDispatch {
  agentKind: string
  at: number
  executionBackend?: string
  model?: string | null
  repo?: DebugRunOverviewDiagnosticsLastDispatchRepo
  stepIndex: number
}

export interface DebugRunOverviewDiagnosticsLastDispatchRepo {
  baseBranch?: string
  name: string
  owner: string
  provider?: string
}

export interface DebugRunOverviewLlm {
  byAgentKind: DebugLlmAgentKindRollup[]
  byPhase: DebugLlmPhaseRollup[]
  /** Always present; `null` when the server has no value for it. */
  costCurrency: string | null
  totals: DebugLlmTotals
}

export interface DebugRunOverviewSinks {
  agentContext: DebugRunOverviewSinksAgentContext
  llmCalls: DebugRunOverviewSinksAgentContext
  provisioningLog: DebugRunOverviewSinksAgentContext
  searchQueries: DebugRunOverviewSinksAgentContext
}

export interface DebugRunOverviewSinksAgentContext {
  available: boolean
  count: number
}

export interface DebugRunSignal {
  /** Always present; `null` when the server has no value for it. */
  agentKind: string | null
  code: string
  /** Always present; `null` when the server has no value for it. */
  count: number | null
  message: string
  severity: DebugRunSignalSeverity
  /** Always present; `null` when the server has no value for it. */
  stepIndex: number | null
}

export type DebugRunSignalSeverity = 'info' | 'warning' | 'error'

/** Every `DebugRunSignalSeverity` value, for exhaustive handling and runtime validation. */
export const DEBUG_RUN_SIGNAL_SEVERITY_VALUES = ['info', 'warning', 'error'] as const

export interface DebugRunStep {
  agentKind: string
  evictionRecoveries: number
  /** Always present; `null` when the server has no value for it. */
  finishedAt: number | null
  /** Always present; `null` when the server has no value for it. */
  firstEvictionDetail: DebugText | null
  hasStructuredResult: boolean
  index: number
  /** Always present; `null` when the server has no value for it. */
  lastActivityAt: number | null
  /** Always present; `null` when the server has no value for it. */
  model: string | null
  outputChars: number
  progress: number
  skipped: boolean
  /** Always present; `null` when the server has no value for it. */
  startedAt: number | null
  state: string
  /** Always present; `null` when the server has no value for it. */
  subtasks: RunSubtaskCounts | null
}

export interface DebugRunSummary {
  blockId: string
  createdAt: number
  currentStep: number
  /** Always present; `null` when the server has no value for it. */
  failure: DebugRunFailure | null
  pipelineId: string
  pipelineName: string
  runId: string
  status: RunStatus
  stepCount: number
}

export interface DebugSearchQuery {
  agentKind: string
  createdAt: number
  executionId: string
  id: string
  /** Always present; `null` when the server has no value for it. */
  provider: DebugSearchQueryProvider | null
  query: string
  resultCount: number
  workspaceId: string
}

export type DebugSearchQueryProvider = 'brave' | 'searxng'

/** Every `DebugSearchQueryProvider` value, for exhaustive handling and runtime validation. */
export const DEBUG_SEARCH_QUERY_PROVIDER_VALUES = ['brave', 'searxng'] as const

export interface DebugSubtaskCounts {
  completed: number
  inProgress: number
  items?: DebugSubtaskItem[]
  total: number
}

export interface DebugSubtaskItem {
  label: string
  status: DebugSubtaskItemStatus
}

export type DebugSubtaskItemStatus = 'pending' | 'in_progress' | 'completed'

/** Every `DebugSubtaskItemStatus` value, for exhaustive handling and runtime validation. */
export const DEBUG_SUBTASK_ITEM_STATUS_VALUES = ['pending', 'in_progress', 'completed'] as const

export interface DebugText {
  chars: number
  matchOffset?: number | null
  offset: number
  text: string
  totalChars: number
  truncated: boolean
}

export interface DebugToolCall {
  args: DebugText
  name: string
}

export interface ErrorResponse {
  error: ErrorResponseError
}

export interface ErrorResponseError {
  code: string
  details?: unknown
  issues?: ErrorResponseErrorIssue[]
  message: string
}

export interface ErrorResponseErrorIssue {
  message: string
  path?: string
}

export type GetDebugLlmCallView = 'raw' | 'messages'

/** Every `GetDebugLlmCallView` value, for exhaustive handling and runtime validation. */
export const GET_DEBUG_LLM_CALL_VIEW_VALUES = ['raw', 'messages'] as const

export interface ListDebugAgentContextResponse {
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
  snapshots: DebugAgentContextSummary[]
}

export type ListDebugLlmCallsOrder = 'newest' | 'oldest'

/** Every `ListDebugLlmCallsOrder` value, for exhaustive handling and runtime validation. */
export const LIST_DEBUG_LLM_CALLS_ORDER_VALUES = ['newest', 'oldest'] as const

export interface ListDebugLlmCallsResponse {
  calls: DebugLlmCall[]
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
}

export interface ListDebugLogsResponse {
  entries: DebugInfraLogEntry[]
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
}

export interface ListDebugRunsResponse {
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
  runs: DebugRunSummary[]
}

export interface ListDebugSearchQueriesResponse {
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
  queries: DebugSearchQuery[]
}

export interface ListPublicJobsResponse {
  jobs: PublicJob[]
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
}

export type LlmCallOutcome = 'ok' | 'warning' | 'error'

/** Every `LlmCallOutcome` value, for exhaustive handling and runtime validation. */
export const LLM_CALL_OUTCOME_VALUES = ['ok', 'warning', 'error'] as const

export interface Notification {
  /** Always present; `null` when the server has no value for it. */
  blockId: string | null
  body: string
  createdAt: number
  /** Always present; `null` when the server has no value for it. */
  executionId: string | null
  id: string
  payload?: NotificationPayload | null
  /** Always present; `null` when the server has no value for it. */
  resolvedAt: number | null
  severity?: NotificationSeverity
  status: NotificationStatus
  title: string
  type: NotificationType
}

export interface NotificationPayload {
  assessment?: NotificationPayloadAssessment
  changeClass?: NotificationPayloadChangeClass
  driftAffected?: NotificationPayloadDriftAffected[]
  findingCount?: number
  forkCount?: number
  initiativeReason?: NotificationPayloadInitiativeReason
  mergeTrackRecordId?: string
  mergedRepos?: string[]
  onCallAssessment?: NotificationPayloadOnCallAssessment
  pipelineName?: string
  platformAlertTransition?: number
  platformAlerts?: NotificationPayloadPlatformAlert[]
  platformFailedTotal?: number
  platformFailingRuns?: NotificationPayloadPlatformFailingRun[]
  platformWindow?: NotificationPayloadPlatformWindow
  prUrl?: string
  releaseSignals?: NotificationPayloadReleaseSignal[]
  revertUrl?: string
  sliceCount?: number
  targetUserId?: string | null
  unmergedRepos?: string[]
  unreachableAreas?: NotificationPayloadUnreachableArea[]
}

export interface NotificationPayloadAssessment {
  /** Range 0..1. */
  complexity: number
  /** Range 0..1. */
  impact: number
  rationale: string
  /** Range 0..1. */
  risk: number
}

export type NotificationPayloadChangeClass = 'docs' | 'test' | 'dependency' | 'config' | 'source' | 'schema' | 'unknown'

/** Every `NotificationPayloadChangeClass` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_CHANGE_CLASS_VALUES = ['docs', 'test', 'dependency', 'config', 'source', 'schema', 'unknown'] as const

export interface NotificationPayloadDriftAffected {
  id: string
  label: string
  reason: NotificationPayloadDriftAffectedReason
  /** Always present; `null` when the server has no value for it. */
  sealedAt: number | null
  source: string
}

export type NotificationPayloadDriftAffectedReason = 'key-mismatch' | 'corrupt'

/** Every `NotificationPayloadDriftAffectedReason` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_DRIFT_AFFECTED_REASON_VALUES = ['key-mismatch', 'corrupt'] as const

export type NotificationPayloadInitiativeReason = 'item_blocked' | 'complete' | 'checkpoint'

/** Every `NotificationPayloadInitiativeReason` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_INITIATIVE_REASON_VALUES = ['item_blocked', 'complete', 'checkpoint'] as const

export interface NotificationPayloadOnCallAssessment {
  /** Range 0..1. */
  culpritConfidence: number
  evidence: string[]
  rationale: string
  recommendation: NotificationPayloadOnCallAssessmentRecommendation
}

export type NotificationPayloadOnCallAssessmentRecommendation = 'revert' | 'hold' | 'monitor'

/** Every `NotificationPayloadOnCallAssessmentRecommendation` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_ON_CALL_ASSESSMENT_RECOMMENDATION_VALUES = ['revert', 'hold', 'monitor'] as const

export type NotificationPayloadPlatformAlert = 'failure_rate_high' | 'duration_p99_high' | 'backlog_high' | 'throughput_stalled' | 'failure_kind_dominant' | 'sweep_degraded'

/** Every `NotificationPayloadPlatformAlert` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_PLATFORM_ALERT_VALUES = ['failure_rate_high', 'duration_p99_high', 'backlog_high', 'throughput_stalled', 'failure_kind_dominant', 'sweep_degraded'] as const

export interface NotificationPayloadPlatformFailingRun {
  /** Always present; `null` when the server has no value for it. */
  blockId: string | null
  createdAt: number
  executionId: string
  failureKind: string
}

export type NotificationPayloadPlatformWindow = '1h' | '24h' | '7d'

/** Every `NotificationPayloadPlatformWindow` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_PLATFORM_WINDOW_VALUES = ['1h', '24h', '7d'] as const

export interface NotificationPayloadReleaseSignal {
  detail?: string
  id: string
  kind: NotificationPayloadReleaseSignalKind
  name: string
  state: NotificationPayloadReleaseSignalState
}

export type NotificationPayloadReleaseSignalKind = 'monitor' | 'slo'

/** Every `NotificationPayloadReleaseSignalKind` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_RELEASE_SIGNAL_KIND_VALUES = ['monitor', 'slo'] as const

export type NotificationPayloadReleaseSignalState = 'ok' | 'warn' | 'alert' | 'no_data'

/** Every `NotificationPayloadReleaseSignalState` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_RELEASE_SIGNAL_STATE_VALUES = ['ok', 'warn', 'alert', 'no_data'] as const

export type NotificationPayloadUnreachableArea = 'ephemeralEnvironments' | 'agentExecutor' | 'binaryStorage'

/** Every `NotificationPayloadUnreachableArea` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_PAYLOAD_UNREACHABLE_AREA_VALUES = ['ephemeralEnvironments', 'agentExecutor', 'binaryStorage'] as const

export type NotificationSeverity = 'normal' | 'urgent'

/** Every `NotificationSeverity` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_SEVERITY_VALUES = ['normal', 'urgent'] as const

export type NotificationStatus = 'open' | 'acted' | 'dismissed'

/** Every `NotificationStatus` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_STATUS_VALUES = ['open', 'acted', 'dismissed'] as const

export type NotificationType = 'merge_review' | 'pipeline_complete' | 'ci_failed' | 'test_failed' | 'requirement_review' | 'clarity_review' | 'release_regression' | 'decision_required' | 'human_test_ready' | 'visual_confirmation_ready' | 'human_review' | 'followup_pending' | 'fork_decision_pending' | 'judge_review' | 'pr_review_ready' | 'initiative' | 'platform_health' | 'infra_unreachable' | 'budget_paused' | 'key_drift' | 'merge_tag_request'

/** Every `NotificationType` value, for exhaustive handling and runtime validation. */
export const NOTIFICATION_TYPE_VALUES = ['merge_review', 'pipeline_complete', 'ci_failed', 'test_failed', 'requirement_review', 'clarity_review', 'release_regression', 'decision_required', 'human_test_ready', 'visual_confirmation_ready', 'human_review', 'followup_pending', 'fork_decision_pending', 'judge_review', 'pr_review_ready', 'initiative', 'platform_health', 'infra_unreachable', 'budget_paused', 'key_drift', 'merge_tag_request'] as const

export interface PublicAgentDecision {
  decisionId: string
  kind: 'agent-decision'
  options: string[]
  question: string
  stepKind: string
}

export interface PublicApprovalGateDecision {
  approvalId: string
  exceeded: boolean
  /** Always present; `null` when the server has no value for it. */
  feedback: string | null
  kind: 'approval-gate'
  proposal: string
  status: PublicApprovalGateDecisionStatus
  stepIndex: number
  stepKind: string
}

export type PublicApprovalGateDecisionStatus = 'pending' | 'approved' | 'changes_requested' | 'rejected'

/** Every `PublicApprovalGateDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_APPROVAL_GATE_DECISION_STATUS_VALUES = ['pending', 'approved', 'changes_requested', 'rejected'] as const

export interface PublicApproveStep {
  /** Length 0..50000. */
  proposal?: string
}

export interface PublicBrainstormDecision {
  /** Always present; `null` when the server has no value for it. */
  convergedDirection: string | null
  iteration: number
  kind: 'brainstorm'
  maxIterations: number
  options: PublicReviewFinding[]
  sessionId: string
  stage: PublicBrainstormDecisionStage
  status: PublicRequirementsDecisionStatus
  taskId: string
}

export type PublicBrainstormDecisionStage = 'requirements' | 'architecture'

/** Every `PublicBrainstormDecisionStage` value, for exhaustive handling and runtime validation. */
export const PUBLIC_BRAINSTORM_DECISION_STAGE_VALUES = ['requirements', 'architecture'] as const

export interface PublicChallengePrReviewFinding {
  /** Length 0..4000. */
  question?: string
}

export interface PublicChooseFork {
  custom?: string | null
  forkId?: string | null
  note?: string | null
}

export interface PublicClarityDecision {
  /** Always present; `null` when the server has no value for it. */
  clarifiedReport: string | null
  findings: PublicReviewFinding[]
  iteration: number
  kind: 'clarity-review'
  maxIterations: number
  reviewId: string
  status: PublicRequirementsDecisionStatus
  taskId: string
}

/** Discriminated by `kind`. */
export type PublicDecision =
  | PublicRequirementsDecision
  | PublicForkDecision
  | PublicJudgeDecision
  | PublicInputGateDecision
  | PublicApprovalGateDecision
  | PublicAgentDecision
  | PublicClarityDecision
  | PublicBrainstormDecision
  | PublicPrReviewDecision
  | PublicHumanTestDecision
  | PublicVisualConfirmDecision

export interface PublicDecisionList {
  decisions: PublicDecision[]
  parked: boolean
  runId: string
  status: RunStatus
  taskId: string
}

export interface PublicForkDecision {
  forks: PublicForkDecisionFork[]
  kind: 'fork'
  /** Always present; `null` when the server has no value for it. */
  seamSummary: string | null
  status: PublicForkDecisionStatus
}

export interface PublicForkDecisionFork {
  approach: string
  id: string
  recommended?: boolean
  riskNotes?: string | null
  summary: string
  title: string
  tradeoffs: string[]
}

export type PublicForkDecisionStatus = 'proposing' | 'awaiting_choice' | 'answering' | 'chosen' | 'single_path' | 'skipped'

/** Every `PublicForkDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_FORK_DECISION_STATUS_VALUES = ['proposing', 'awaiting_choice', 'answering', 'chosen', 'single_path', 'skipped'] as const

export interface PublicHumanTestDecision {
  attempts: number
  /** Always present; `null` when the server has no value for it. */
  degradedReason: string | null
  /** Always present; `null` when the server has no value for it. */
  environment: PublicHumanTestEnvironment | null
  kind: 'human-test'
  maxAttempts: number
  phase: PublicHumanTestDecisionPhase
}

export type PublicHumanTestDecisionPhase = 'provisioning' | 'awaiting_human' | 'fixing' | 'resolving_conflicts' | 'passed'

/** Every `PublicHumanTestDecisionPhase` value, for exhaustive handling and runtime validation. */
export const PUBLIC_HUMAN_TEST_DECISION_PHASE_VALUES = ['provisioning', 'awaiting_human', 'fixing', 'resolving_conflicts', 'passed'] as const

export interface PublicHumanTestEnvironment {
  /** Always present; `null` when the server has no value for it. */
  expiresAt: number | null
  status: PublicHumanTestEnvironmentStatus
  /** Always present; `null` when the server has no value for it. */
  url: string | null
}

export type PublicHumanTestEnvironmentStatus = 'provisioning' | 'ready' | 'failed' | 'expired' | 'tearing_down' | 'torn_down'

/** Every `PublicHumanTestEnvironmentStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_HUMAN_TEST_ENVIRONMENT_STATUS_VALUES = ['provisioning', 'ready', 'failed', 'expired', 'tearing_down', 'torn_down'] as const

export interface PublicIncorporate {
  /** Length 0..4000. */
  feedback?: string
}

export interface PublicInputGateDecision {
  checkedAt: number
  issues: PublicInputGateDecisionIssue[]
  kind: 'input-gate'
  mode: PublicInputGateDecisionMode
  status: PublicInputGateDecisionStatus
}

export interface PublicInputGateDecisionIssue {
  code: PublicInputGateDecisionIssueCode
  severity: PublicInputGateDecisionIssueSeverity
}

export type PublicInputGateDecisionIssueCode = 'description_missing' | 'description_placeholder' | 'description_thin' | 'reproduction_missing' | 'review_target_missing' | 'success_criteria_missing'

/** Every `PublicInputGateDecisionIssueCode` value, for exhaustive handling and runtime validation. */
export const PUBLIC_INPUT_GATE_DECISION_ISSUE_CODE_VALUES = ['description_missing', 'description_placeholder', 'description_thin', 'reproduction_missing', 'review_target_missing', 'success_criteria_missing'] as const

export type PublicInputGateDecisionIssueSeverity = 'blocking' | 'advisory'

/** Every `PublicInputGateDecisionIssueSeverity` value, for exhaustive handling and runtime validation. */
export const PUBLIC_INPUT_GATE_DECISION_ISSUE_SEVERITY_VALUES = ['blocking', 'advisory'] as const

export type PublicInputGateDecisionMode = 'standard' | 'advisory' | 'off'

/** Every `PublicInputGateDecisionMode` value, for exhaustive handling and runtime validation. */
export const PUBLIC_INPUT_GATE_DECISION_MODE_VALUES = ['standard', 'advisory', 'off'] as const

export type PublicInputGateDecisionStatus = 'off' | 'not_applicable' | 'passed' | 'blocked' | 'overridden'

/** Every `PublicInputGateDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_INPUT_GATE_DECISION_STATUS_VALUES = ['off', 'not_applicable', 'passed', 'blocked', 'overridden'] as const

export interface PublicJob {
  createdAt: number
  /** Always present; `null` when the server has no value for it. */
  error: RunError | null
  jobId: string
  pipelineId: string
  /** Always present; `null` when the server has no value for it. */
  result: PublicJobResult | null
  status: PublicJobStatus
}

export interface PublicJobAccepted {
  jobId: string
  links: PublicJobAcceptedLinks
  status: PublicJobStatus
}

export interface PublicJobAcceptedLinks {
  events: string
  self: string
}

export interface PublicJobResult {
  /** Always present; `null` when the server has no value for it. */
  data: unknown | null
  output: string
}

export type PublicJobStatus = 'running' | 'succeeded' | 'failed'

/** Every `PublicJobStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_JOB_STATUS_VALUES = ['running', 'succeeded', 'failed'] as const

export interface PublicJudgeDecision {
  bounces: number
  kind: 'judge'
  maxBounces: number
  /** Always present; `null` when the server has no value for it. */
  rubricId: string | null
  /** Always present; `null` when the server has no value for it. */
  rubricName: string | null
  status: PublicJudgeDecisionStatus
  stepKind: string
  /** Always present; `null` when the server has no value for it. */
  threshold: number | null
  /** Always present; `null` when the server has no value for it. */
  verdict: PublicJudgeVerdict | null
}

export type PublicJudgeDecisionStatus = 'evaluating' | 'awaiting_decision' | 'bouncing' | 'passed' | 'failed' | 'skipped'

/** Every `PublicJudgeDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_JUDGE_DECISION_STATUS_VALUES = ['evaluating', 'awaiting_decision', 'bouncing', 'passed', 'failed', 'skipped'] as const

export interface PublicJudgeFinding {
  detail?: string
  severity: Severity
  title: string
  where?: string
}

export interface PublicJudgeVerdict {
  findings: PublicJudgeFinding[]
  /** Range 0..1. */
  score: number
  summary: string
}

export interface PublicNotificationList {
  notifications: Notification[]
}

export interface PublicPipeline {
  headlessStartable: boolean
  name: string
  pipelineId: string
  public: boolean
  steps: string[]
}

export interface PublicPipelineList {
  pipelines: PublicPipeline[]
}

export interface PublicPrReviewDecision {
  findings: PublicPrReviewDecisionFinding[]
  kind: 'pr-review'
  /** Always present; `null` when the server has no value for it. */
  prUrl: string | null
  selectedFindingIds: string[]
  slices: PublicPrReviewDecisionSlice[]
  status: PublicPrReviewDecisionStatus
  /** Always present; `null` when the server has no value for it. */
  summary: string | null
}

export interface PublicPrReviewDecisionFinding {
  category: PublicPrReviewDecisionFindingCategory
  challenge?: PublicPrReviewDecisionFindingChallenge | null
  detail: string
  id: string
  line?: number | null
  path: string
  severity: PublicPrReviewDecisionFindingSeverity
  side?: PublicPrReviewDecisionFindingSide | null
  sliceId?: string | null
  suggestedFix?: string | null
  title: string
}

export type PublicPrReviewDecisionFindingCategory = 'correctness' | 'security' | 'performance' | 'maintainability' | 'style' | 'test' | 'other'

/** Every `PublicPrReviewDecisionFindingCategory` value, for exhaustive handling and runtime validation. */
export const PUBLIC_PR_REVIEW_DECISION_FINDING_CATEGORY_VALUES = ['correctness', 'security', 'performance', 'maintainability', 'style', 'test', 'other'] as const

export interface PublicPrReviewDecisionFindingChallenge {
  justification?: string | null
  question?: string | null
  status: PublicPrReviewDecisionFindingChallengeStatus
}

export type PublicPrReviewDecisionFindingChallengeStatus = 'investigating' | 'upheld' | 'amended' | 'retracted' | 'failed'

/** Every `PublicPrReviewDecisionFindingChallengeStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_PR_REVIEW_DECISION_FINDING_CHALLENGE_STATUS_VALUES = ['investigating', 'upheld', 'amended', 'retracted', 'failed'] as const

export type PublicPrReviewDecisionFindingSeverity = 'blocker' | 'high' | 'medium' | 'low' | 'nit'

/** Every `PublicPrReviewDecisionFindingSeverity` value, for exhaustive handling and runtime validation. */
export const PUBLIC_PR_REVIEW_DECISION_FINDING_SEVERITY_VALUES = ['blocker', 'high', 'medium', 'low', 'nit'] as const

export type PublicPrReviewDecisionFindingSide = 'LEFT' | 'RIGHT'

/** Every `PublicPrReviewDecisionFindingSide` value, for exhaustive handling and runtime validation. */
export const PUBLIC_PR_REVIEW_DECISION_FINDING_SIDE_VALUES = ['LEFT', 'RIGHT'] as const

export interface PublicPrReviewDecisionSlice {
  id: string
  paths: string[]
  rationale: string
  title: string
}

export type PublicPrReviewDecisionStatus = 'reviewing' | 'awaiting_selection' | 'challenging' | 'fixing' | 'posting' | 'done' | 'skipped'

/** Every `PublicPrReviewDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_PR_REVIEW_DECISION_STATUS_VALUES = ['reviewing', 'awaiting_selection', 'challenging', 'fixing', 'posting', 'done', 'skipped'] as const

export interface PublicRejectStep {
  /** Length 0..2000. */
  reason?: string
}

export interface PublicReplyFinding {
  /** Length 1..4000. */
  reply: string
}

export interface PublicRequestGateFix {
  /** Length 1..10000. */
  findings: string
}

export interface PublicRequestStepChanges {
  /** Length 1..10000. */
  feedback: string
}

export interface PublicRequirementsDecision {
  findings: PublicReviewFinding[]
  /** Always present; `null` when the server has no value for it. */
  incorporatedRequirements: string | null
  iteration: number
  kind: 'requirements-review'
  maxIterations: number
  reviewId: string
  status: PublicRequirementsDecisionStatus
  taskId: string
}

export type PublicRequirementsDecisionStatus = 'ready' | 'incorporating' | 'reviewing' | 'merged' | 'exceeded' | 'incorporated'

/** Every `PublicRequirementsDecisionStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_REQUIREMENTS_DECISION_STATUS_VALUES = ['ready', 'incorporating', 'reviewing', 'merged', 'exceeded', 'incorporated'] as const

export interface PublicResolveAgentDecision {
  /** Length 1..4000. */
  choice: string
}

export interface PublicResolveExceeded {
  choice: PublicResolveExceededChoice
}

export type PublicResolveExceededChoice = 'extra-round' | 'proceed' | 'stop-reset'

/** Every `PublicResolveExceededChoice` value, for exhaustive handling and runtime validation. */
export const PUBLIC_RESOLVE_EXCEEDED_CHOICE_VALUES = ['extra-round', 'proceed', 'stop-reset'] as const

export interface PublicResolveInputGate {
  choice: PublicResolveInputGateChoice
}

export type PublicResolveInputGateChoice = 'recheck' | 'proceed'

/** Every `PublicResolveInputGateChoice` value, for exhaustive handling and runtime validation. */
export const PUBLIC_RESOLVE_INPUT_GATE_CHOICE_VALUES = ['recheck', 'proceed'] as const

export interface PublicResolveJudge {
  choice: PublicResolveJudgeChoice
  feedback?: string | null
}

export type PublicResolveJudgeChoice = 'proceed' | 'bounce' | 'stop'

/** Every `PublicResolveJudgeChoice` value, for exhaustive handling and runtime validation. */
export const PUBLIC_RESOLVE_JUDGE_CHOICE_VALUES = ['proceed', 'bounce', 'stop'] as const

export interface PublicResolvePrReview {
  action?: PublicResolvePrReviewAction
  findingIds?: string[]
}

export type PublicResolvePrReviewAction = 'finish' | 'fix' | 'post'

/** Every `PublicResolvePrReviewAction` value, for exhaustive handling and runtime validation. */
export const PUBLIC_RESOLVE_PR_REVIEW_ACTION_VALUES = ['finish', 'fix', 'post'] as const

export interface PublicReviewFinding {
  category: PublicReviewFindingCategory
  detail: string
  itemId: string
  /** Always present; `null` when the server has no value for it. */
  reply: string | null
  severity: PublicReviewFindingSeverity
  status: PublicReviewFindingStatus
  title: string
}

export type PublicReviewFindingCategory = 'gap' | 'clarification' | 'assumption' | 'risk' | 'question'

/** Every `PublicReviewFindingCategory` value, for exhaustive handling and runtime validation. */
export const PUBLIC_REVIEW_FINDING_CATEGORY_VALUES = ['gap', 'clarification', 'assumption', 'risk', 'question'] as const

export type PublicReviewFindingSeverity = 'low' | 'medium' | 'high'

/** Every `PublicReviewFindingSeverity` value, for exhaustive handling and runtime validation. */
export const PUBLIC_REVIEW_FINDING_SEVERITY_VALUES = ['low', 'medium', 'high'] as const

export type PublicReviewFindingStatus = 'open' | 'answered' | 'resolved' | 'dismissed' | 'recommend_requested'

/** Every `PublicReviewFindingStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_REVIEW_FINDING_STATUS_VALUES = ['open', 'answered', 'resolved', 'dismissed', 'recommend_requested'] as const

export interface PublicRun {
  createdAt: number
  currentStep: number
  /** Always present; `null` when the server has no value for it. */
  error: RunError | null
  /** Always present; `null` when the server has no value for it. */
  pullRequest: RunPullRequest | null
  runId: string
  status: RunStatus
  steps: PublicRunStep[]
  taskId: string
}

export interface PublicRunStep {
  agentKind: string
  progress: number
  state: StepState
  /** Always present; `null` when the server has no value for it. */
  subtasks: RunSubtaskCounts | null
}

export interface PublicService {
  description: string
  serviceId: string
  status: TaskStatus
  title: string
  type: PublicServiceType
}

export interface PublicServiceList {
  services: PublicService[]
}

export type PublicServiceType = 'frontend' | 'service' | 'library' | 'document' | 'api' | 'database' | 'queue' | 'integration' | 'external' | 'environment'

/** Every `PublicServiceType` value, for exhaustive handling and runtime validation. */
export const PUBLIC_SERVICE_TYPE_VALUES = ['frontend', 'service', 'library', 'document', 'api', 'database', 'queue', 'integration', 'external', 'environment'] as const

export interface PublicSetFindingStatus {
  status: PublicSetFindingStatusStatus
}

export type PublicSetFindingStatusStatus = 'dismissed' | 'open'

/** Every `PublicSetFindingStatusStatus` value, for exhaustive handling and runtime validation. */
export const PUBLIC_SET_FINDING_STATUS_STATUS_VALUES = ['dismissed', 'open'] as const

export interface PublicTask {
  description: string
  progress: number
  /** Always present; `null` when the server has no value for it. */
  pullRequestUrl: string | null
  /** Always present; `null` when the server has no value for it. */
  runId: string | null
  serviceId: string
  status: TaskStatus
  taskId: string
  taskType: 'feature' | 'bug' | 'document' | 'spike' | 'review' | 'ralph' | 'recurring' | (string & {})
  title: string
}

export interface PublicTaskList {
  /** Always present; `null` when the server has no value for it. */
  nextCursor: string | null
  tasks: PublicTask[]
}

export interface PublicTaskTicket {
  /** Length 1..500. */
  ref: string
  source: 'jira' | 'github' | 'linear' | (string & {})
}

export interface PublicUsage {
  budget: PublicUsageBudget
  currency: string
  periodStart: number
  rows: PublicUsageRow[]
}

export interface PublicUsageBudget {
  costLimit: number
  costSpent: number
  exceeded: boolean
  inputTokens: number
  outputTokens: number
}

export interface PublicUsageRow {
  billing: PublicUsageRowBilling
  calls: number
  costEstimate: number
  inputTokens: number
  model: string
  outputTokens: number
  provider: string
  /** Always present; `null` when the server has no value for it. */
  vendor: string | null
}

export type PublicUsageRowBilling = 'metered' | 'subscription'

/** Every `PublicUsageRowBilling` value, for exhaustive handling and runtime validation. */
export const PUBLIC_USAGE_ROW_BILLING_VALUES = ['metered', 'subscription'] as const

export interface PublicVisualConfirmDecision {
  attempts: number
  /** Always present; `null` when the server has no value for it. */
  degradedReason: string | null
  kind: 'visual-confirmation'
  maxAttempts: number
  pairs: PublicVisualConfirmDecisionPair[]
  phase: PublicVisualConfirmDecisionPhase
}

export interface PublicVisualConfirmDecisionPair {
  actualArtifactId?: string | null
  referenceArtifactId?: string | null
  view: string
}

export type PublicVisualConfirmDecisionPhase = 'awaiting_human' | 'fixing' | 'approved'

/** Every `PublicVisualConfirmDecisionPhase` value, for exhaustive handling and runtime validation. */
export const PUBLIC_VISUAL_CONFIRM_DECISION_PHASE_VALUES = ['awaiting_human', 'fixing', 'approved'] as const

export interface RunError {
  code: string
  message: string
}

export interface RunPullRequest {
  /** Always present; `null` when the server has no value for it. */
  branch: string | null
  url: string
}

export type RunStatus = 'running' | 'blocked' | 'paused' | 'done' | 'failed'

/** Every `RunStatus` value, for exhaustive handling and runtime validation. */
export const RUN_STATUS_VALUES = ['running', 'blocked', 'paused', 'done', 'failed'] as const

export interface RunSubtaskCounts {
  completed: number
  inProgress: number
  total: number
}

export type Severity = 'low' | 'medium' | 'high' | 'critical'

/** Every `Severity` value, for exhaustive handling and runtime validation. */
export const SEVERITY_VALUES = ['low', 'medium', 'high', 'critical'] as const

export interface StartPublicTask {
  /** Length 1..120. */
  pipelineId?: string
}

export type StepState = 'pending' | 'working' | 'waiting_decision' | 'done'

/** Every `StepState` value, for exhaustive handling and runtime validation. */
export const STEP_STATE_VALUES = ['pending', 'working', 'waiting_decision', 'done'] as const

export type TaskStatus = 'planned' | 'ready' | 'in_progress' | 'blocked' | 'pr_ready' | 'done'

/** Every `TaskStatus` value, for exhaustive handling and runtime validation. */
export const TASK_STATUS_VALUES = ['planned', 'ready', 'in_progress', 'blocked', 'pr_ready', 'done'] as const

export interface UpdatePublicTask {
  /** Length 0..2000. */
  description?: string
  /** Length 1..200. */
  title?: string
}
