// GENERATED by `pnpm gen:sdk` from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate after any change to the `/api/v1` contracts; `pnpm check:sdk` fails CI on drift.

// The resource clients: one class per resource group, each a thin, typed shell over the
// hand-written `Transport`. Nothing here decides retry, auth, error mapping or stream framing —
// that is `http.ts` / `errors.ts` / `sse.ts`, so those can change without touching 38 methods.

import type { EventStream } from './sse.ts'
import type { RequestOptions, Transport } from './http.ts'
import { encodePathSegment } from './http.ts'
import { repeatedCursorError } from './errors.ts'
import type {
  CreatePublicJob,
  CreatePublicTask,
  DebugAgentContextSnapshot,
  DebugLlmCall,
  DebugRunOverview,
  GetDebugLlmCallView,
  ListDebugAgentContextResponse,
  ListDebugLlmCallsOrder,
  ListDebugLlmCallsResponse,
  ListDebugLogsResponse,
  ListDebugRunsResponse,
  ListDebugSearchQueriesResponse,
  ListPublicJobsResponse,
  LlmCallOutcome,
  Notification,
  PublicApproveStep,
  PublicChallengePrReviewFinding,
  PublicChooseFork,
  PublicDecisionList,
  PublicIncorporate,
  PublicJob,
  PublicJobAccepted,
  PublicJobStatus,
  PublicNotificationList,
  PublicPipelineList,
  PublicRejectStep,
  PublicReplyFinding,
  PublicRequestGateFix,
  PublicRequestStepChanges,
  PublicResolveAgentDecision,
  PublicResolveExceeded,
  PublicResolveInputGate,
  PublicResolveJudge,
  PublicResolvePrReview,
  PublicRun,
  PublicServiceList,
  PublicSetFindingStatus,
  PublicTask,
  PublicTaskList,
  PublicUsage,
  RunStatus,
  StartPublicTask,
  TaskStatus,
  UpdatePublicTask,
} from './models.generated.ts'

/** Query parameters for `client.debug.getAgentContext()`. */
export type DebugGetAgentContextQuery = {
  bodyChars?: number
  bodyOffset?: number
}

/** Query parameters for `client.debug.getLlmCall()`. */
export type DebugGetLlmCallQuery = {
  bodyChars?: number
  bodyOffset?: number
  view?: GetDebugLlmCallView
}

/** Query parameters for `client.debug.listAgentContext()`. */
export type DebugListAgentContextQuery = {
  stepIndex?: number
  limit?: number
  cursor?: string
}

/** Query parameters for `client.debug.listLlmCalls()`. */
export type DebugListLlmCallsQuery = {
  agentKind?: string
  phase?: string
  outcome?: LlmCallOutcome
  contains?: string
  order?: ListDebugLlmCallsOrder
  limit?: number
  cursor?: string
  bodyChars?: number
}

/** Query parameters for `client.debug.listLogs()`. */
export type DebugListLogsQuery = {
  limit?: number
  cursor?: string
}

/** Query parameters for `client.debug.listRuns()`. */
export type DebugListRunsQuery = {
  status?: RunStatus
  since?: number
  limit?: number
  cursor?: string
}

/** Query parameters for `client.debug.listSearchQueries()`. */
export type DebugListSearchQueriesQuery = {
  limit?: number
  cursor?: string
}

/** Query parameters for `client.jobs.list()`. */
export type JobsListQuery = {
  limit?: number
  cursor?: string
  status?: PublicJobStatus
  since?: number
}

/** Query parameters for `client.tasks.listByService()`. */
export type TasksListByServiceQuery = {
  limit?: number
  cursor?: string
  status?: TaskStatus
}

/** Headless jobs (a public, inline pipeline run against a brief): start, poll or stream one. */
export class JobsResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Cancel a job
   * Stop a headless job run, freeing its concurrency slot. Idempotent — an already-finished job is returned as-is. Use this to abandon a run parked on a decision you do not intend to answer.
   * `POST /api/v1/jobs/{id}/cancel` — operation `cancelPublicJob`.
   */
  cancel(id: string, options: RequestOptions = {}): Promise<PublicJob> {
    return this.#transport.request<PublicJob>({
      method: 'POST',
      path: `/api/v1/jobs/${encodePathSegment(id)}/cancel`,
      options,
    })
  }

  /**
   * Start a headless job
   * Start a public, inline pipeline headlessly against a supplied brief. Returns a job id to poll or stream. Nothing is pushed to GitHub.
   * `POST /api/v1/jobs` — operation `createPublicJob`.
   */
  create(body: CreatePublicJob, options: RequestOptions = {}): Promise<PublicJobAccepted> {
    return this.#transport.request<PublicJobAccepted>({
      method: 'POST',
      path: `/api/v1/jobs`,
      body,
      options,
    })
  }

  /**
   * Get a job
   * Poll a headless job started through this surface: its status and, once finished, its result.
   * `GET /api/v1/jobs/{id}` — operation `getPublicJob`.
   */
  get(id: string, options: RequestOptions = {}): Promise<PublicJob> {
    return this.#transport.request<PublicJob>({
      method: 'GET',
      path: `/api/v1/jobs/${encodePathSegment(id)}`,
      options,
    })
  }

  /**
   * List the workspace's jobs
   * List the headless runs THIS surface created, newest first and keyset-paginated. Scoped to internal-anchored runs exactly like the single-job read, so an external key can never enumerate the workspace’s ordinary board runs.
   * `GET /api/v1/jobs` — operation `listPublicJobs`.
   */
  list(query: JobsListQuery = {}, options: RequestOptions = {}): Promise<ListPublicJobsResponse> {
    return this.#transport.request<ListPublicJobsResponse>({
      method: 'GET',
      path: `/api/v1/jobs`,
      query,
      options,
    })
  }

  /**
   * Every `jobs` across every page of `list()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listAll(query: JobsListQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListPublicJobsResponse['jobs'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.list({ ...query, cursor }, options)
      for (const item of page.jobs) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * Stream a job (SSE)
   * Server-sent events for a headless job run: `progress` frames until a terminal `done`/`error`/`stopped`/`timeout` event. Authenticated by the API key header.
   * `GET /api/v1/jobs/{id}/events` — operation `streamPublicJobEvents`.
   */
  stream(id: string, options: RequestOptions = {}): Promise<EventStream> {
    return this.#transport.stream({
      method: 'GET',
      path: `/api/v1/jobs/${encodePathSegment(id)}/events`,
      options,
    })
  }
}

/** The workspace's board services — the frames tasks are created under. */
export class ServicesResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * List the workspace's services
   * List the board service frames in the key’s workspace, so a caller can discover the serviceId to create/list tasks under.
   * `GET /api/v1/services` — operation `listPublicServices`.
   */
  list(options: RequestOptions = {}): Promise<PublicServiceList> {
    return this.#transport.request<PublicServiceList>({
      method: 'GET',
      path: `/api/v1/services`,
      options,
    })
  }
}

/** A board task's whole lifecycle: create, edit, start, stop, retry, watch, delete. */
export class TasksResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Create a task under a service
   * Create a task inside a service frame the key’s workspace owns. The task starts in the `planned` state; start it with the start endpoint.
   * `POST /api/v1/services/{serviceId}/tasks` — operation `createPublicTask`.
   */
  create(serviceId: string, body: CreatePublicTask, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'POST',
      path: `/api/v1/services/${encodePathSegment(serviceId)}/tasks`,
      body,
      options,
    })
  }

  /**
   * Delete a task
   * Delete a task and its run history. Destructive, so it sits at the top of the scope ladder: requires an `admin`-scoped key.
   * `DELETE /api/v1/tasks/{taskId}` — operation `deletePublicTask`.
   */
  delete(taskId: string, options: RequestOptions = {}): Promise<void> {
    return this.#transport.requestNoContent({
      method: 'DELETE',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}`,
      options,
    })
  }

  /**
   * Get a task's status
   * Read a task’s current lifecycle status, run progress, run id, and PR URL (once one exists).
   * `GET /api/v1/tasks/{taskId}` — operation `getPublicTask`.
   */
  get(taskId: string, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'GET',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}`,
      options,
    })
  }

  /**
   * Get a task's run (rich projection)
   * Read a task’s run in detail: per-step status/progress/subtasks, the failure kind and message, and the PR (url + branch).
   * `GET /api/v1/tasks/{taskId}/run` — operation `getPublicRun`.
   */
  getRun(taskId: string, options: RequestOptions = {}): Promise<PublicRun> {
    return this.#transport.request<PublicRun>({
      method: 'GET',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}/run`,
      options,
    })
  }

  /**
   * List a service's tasks
   * List every task under a service (the whole subtree — tasks directly under the frame and under its modules).
   * `GET /api/v1/services/{serviceId}/tasks` — operation `listPublicServiceTasks`.
   */
  listByService(serviceId: string, query: TasksListByServiceQuery = {}, options: RequestOptions = {}): Promise<PublicTaskList> {
    return this.#transport.request<PublicTaskList>({
      method: 'GET',
      path: `/api/v1/services/${encodePathSegment(serviceId)}/tasks`,
      query,
      options,
    })
  }

  /**
   * Every `tasks` across every page of `listByService()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listByServiceAll(serviceId: string, query: TasksListByServiceQuery = {}, options: RequestOptions = {}): AsyncGenerator<PublicTaskList['tasks'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listByService(serviceId, { ...query, cursor }, options)
      for (const item of page.tasks) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * Retry a task's failed run
   * Retry a task’s failed run. A task on an individual-usage model cannot be retried through the API (no headless personal-credential unlock).
   * `POST /api/v1/tasks/{taskId}/retry` — operation `retryPublicTask`.
   */
  retry(taskId: string, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'POST',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}/retry`,
      options,
    })
  }

  /**
   * Start (run) a task
   * Start a task’s pipeline. Uses the request’s pipelineId, else the task’s pinned pipeline. A pipeline that can park on a human decision requires a `decide`-scope key. A task on an individual-usage model cannot be started through the API (no headless personal-credential unlock).
   * `POST /api/v1/tasks/{taskId}/start` — operation `startPublicTask`.
   */
  start(taskId: string, body: StartPublicTask, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'POST',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}/start`,
      body,
      options,
    })
  }

  /**
   * Stop a task's run
   * Stop a task’s in-flight run. Records a `cancelled` terminal state, leaving the run retryable.
   * `POST /api/v1/tasks/{taskId}/stop` — operation `stopPublicTask`.
   */
  stop(taskId: string, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'POST',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}/stop`,
      options,
    })
  }

  /**
   * Stream a task run (SSE)
   * Server-sent events for a board task run: `progress` frames (the rich run projection) until a terminal `done`/`error` event, or a `timeout` when the connection cap is reached. Authenticated by the API key header.
   * `GET /api/v1/tasks/{taskId}/events` — operation `streamPublicTaskRun`.
   */
  stream(taskId: string, options: RequestOptions = {}): Promise<EventStream> {
    return this.#transport.stream({
      method: 'GET',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}/events`,
      options,
    })
  }

  /**
   * Edit a task's title/description
   * Edit a task’s human-authored fields (title/description) before it runs. Both fields are optional.
   * `PATCH /api/v1/tasks/{taskId}` — operation `updatePublicTask`.
   */
  update(taskId: string, body: UpdatePublicTask, options: RequestOptions = {}): Promise<PublicTask> {
    return this.#transport.request<PublicTask>({
      method: 'PATCH',
      path: `/api/v1/tasks/${encodePathSegment(taskId)}`,
      body,
      options,
    })
  }
}

/** The pipelines a task can be started with, and whether each is headless-startable. */
export class PipelinesResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * List the workspace's pipelines
   * List the pipelines in the key’s workspace — id/name/steps plus whether each is public and safe to run headlessly — so a caller can pick a pipelineId to start a task with.
   * `GET /api/v1/pipelines` — operation `listPublicPipelines`.
   */
  list(options: RequestOptions = {}): Promise<PublicPipelineList> {
    return this.#transport.request<PublicPipelineList>({
      method: 'GET',
      path: `/api/v1/pipelines`,
      options,
    })
  }
}

/** The workspace's human-actionable inbox: list, act on, or dismiss a run tail. */
export class NotificationsResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Act on a notification
   * Run a notification’s typed side-effect and resolve it: merge the PR (merge_review / pipeline_complete) or retry the run (ci_failed / test_failed). Performs a real GitHub merge, so it requires an admin-scoped key. Only these automated-action types are actionable through the API — a notification that parks a run on an interactive human decision cannot be acted on headlessly (dismiss it instead). A card that would retry a run on an individual-usage model likewise cannot be acted on through the API.
   * `POST /api/v1/notifications/{id}/act` — operation `actPublicNotification`.
   */
  act(id: string, options: RequestOptions = {}): Promise<Notification> {
    return this.#transport.request<Notification>({
      method: 'POST',
      path: `/api/v1/notifications/${encodePathSegment(id)}/act`,
      options,
    })
  }

  /**
   * Dismiss a notification
   * Dismiss a notification without acting on it.
   * `POST /api/v1/notifications/{id}/dismiss` — operation `dismissPublicNotification`.
   */
  dismiss(id: string, options: RequestOptions = {}): Promise<Notification> {
    return this.#transport.request<Notification>({
      method: 'POST',
      path: `/api/v1/notifications/${encodePathSegment(id)}/dismiss`,
      options,
    })
  }

  /**
   * List the workspace's open notifications
   * List the open, human-actionable notifications in the key’s workspace (merge reviews, pipeline-complete confirmations, CI/test failures, and informational cards).
   * `GET /api/v1/notifications` — operation `listPublicNotifications`.
   */
  list(options: RequestOptions = {}): Promise<PublicNotificationList> {
    return this.#transport.request<PublicNotificationList>({
      method: 'GET',
      path: `/api/v1/notifications`,
      options,
    })
  }
}

/** The billing period's metered budget position and the per-model breakdown behind it. */
export class UsageResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Read the workspace's usage for the current period
   * Read this billing period’s METERED spend against the workspace budget (including whether it is exceeded, which pauses runs) plus the per-(billing, vendor, provider, model) token breakdown behind it. Costs on `subscription` rows are illustrative — a flat-rate plan bills nothing per token — so branch on `billing` before summing. Workspace-scoped: the account- and user-tier budgets are not reachable through this surface.
   * `GET /api/v1/usage` — operation `getPublicUsage`.
   */
  get(options: RequestOptions = {}): Promise<PublicUsage> {
    return this.#transport.request<PublicUsage>({
      method: 'GET',
      path: `/api/v1/usage`,
      options,
    })
  }
}

/** Every way a run stops for a person: approval gates, review and brainstorm loops, forks, judge verdicts, PR review findings and the human-verdict gates. */
export class DecisionsResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Answer an agent-raised decision
   * Answer a question an agent raised mid-work. Resolving RE-RUNS the asking step with the choice folded in, rather than advancing past it. The choice is taken verbatim, so it may be one of the offered options or a steer of your own. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/questions/{decisionId}/answer` — operation `resolvePublicRunAgentDecision`.
   */
  answerAgentDecision(runId: string, decisionId: string, body: PublicResolveAgentDecision, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/questions/${encodePathSegment(decisionId)}/answer`,
      body,
      options,
    })
  }

  /**
   * Approve a parked step
   * Approve the proposal a gated step is holding up, optionally replacing it with an edited one (the edit is what flows to every downstream step), and advance the run. The `approvalId` comes from the run's decision list; passing it back is what makes a racing app user and a racing integration resolve the same gate. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/approve` — operation `approvePublicRunStep`.
   */
  approveStep(runId: string, approvalId: string, body: PublicApproveStep, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/approvals/${encodePathSegment(approvalId)}/approve`,
      body,
      options,
    })
  }

  /**
   * Approve a visual-confirmation gate
   * Approve the captured screenshots against the reference designs and advance the run. The images themselves are not readable over this API — the decision carries only artifact ids — so approving on the projection alone approves screenshots you have not seen. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/visual-confirmation/approve` — operation `approvePublicRunVisualConfirm`.
   */
  approveVisualConfirmation(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/visual-confirmation/approve`,
      options,
    })
  }

  /**
   * Challenge a PR review finding
   * Dispatch a read-only investigator to re-examine one finding against the full source, optionally with a specific concern. It upholds, strengthens or retracts the finding, and the review re-parks carrying the verdict. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/challenge` — operation `challengePublicRunPrReviewFinding`.
   */
  challengePrReviewFinding(runId: string, findingId: string, body: PublicChallengePrReviewFinding, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/pr-review/findings/${encodePathSegment(findingId)}/challenge`,
      body,
      options,
    })
  }

  /**
   * Choose an implementation approach
   * Pick one of the proposed implementation forks (by id) or submit your own approach. The Coder then runs with the choice folded in as a binding directive. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/fork/choose` — operation `choosePublicRunFork`.
   */
  chooseFork(runId: string, body: PublicChooseFork, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/fork/choose`,
      body,
      options,
    })
  }

  /**
   * Confirm a human-test gate
   * Confirm the change works in the ephemeral environment: it is torn down and the run advances. The decision carries the environment URL to exercise; confirming without exercising it approves untested work. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/human-test/confirm` — operation `confirmPublicRunHumanTest`.
   */
  confirmHumanTest(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/human-test/confirm`,
      options,
    })
  }

  /**
   * Dismiss a PR review finding
   * Drop one finding from the parked review entirely. Curation rather than a resolution: the run stays parked. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/pr-review/findings/{findingId}/dismiss` — operation `dismissPublicRunPrReviewFinding`.
   */
  dismissPrReviewFinding(runId: string, findingId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/pr-review/findings/${encodePathSegment(findingId)}/dismiss`,
      options,
    })
  }

  /**
   * Incorporate the answers
   * Fold the recorded answers into one standardized requirements document. Asynchronous — the run re-reviews in the background, so the response shows the review `incorporating`. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/requirements/incorporate` — operation `incorporatePublicRunRequirements`.
   */
  incorporate(runId: string, body: PublicIncorporate, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/incorporate`,
      body,
      options,
    })
  }

  /**
   * Incorporate brainstorm picks
   * Fold the picks into one converged direction. ASYNCHRONOUS: the response shows the session `incorporating` while the durable driver folds and re-runs in the background. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/incorporate` — operation `incorporatePublicRunBrainstorm`.
   */
  incorporateBrainstorm(runId: string, stage: string, body: PublicIncorporate, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/incorporate`,
      body,
      options,
    })
  }

  /**
   * Incorporate clarity answers
   * Fold the recorded answers into one standardized bug report. ASYNCHRONOUS: the response shows the review `incorporating` while the durable driver folds and re-reviews in the background. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/clarity/incorporate` — operation `incorporatePublicRunClarity`.
   */
  incorporateClarity(runId: string, body: PublicIncorporate, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/incorporate`,
      body,
      options,
    })
  }

  /**
   * List a run's parked decisions
   * Read what a run is currently asking a human: requirement-review findings (with the stable item ids a reply addresses) and any implementation-fork choice. `parked` is true while the run is blocked awaiting one of them.
   * `GET /api/v1/runs/{runId}/decisions` — operation `listPublicRunDecisions`.
   */
  list(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'GET',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions`,
      options,
    })
  }

  /**
   * Proceed with the current requirements
   * Settle the requirements phase and advance the parked run (used when nothing is outstanding). Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/requirements/proceed` — operation `proceedPublicRunRequirements`.
   */
  proceed(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/proceed`,
      options,
    })
  }

  /**
   * Proceed past a brainstorm
   * Settle the brainstorm with the last converged direction and advance the parked run. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/proceed` — operation `proceedPublicRunBrainstorm`.
   */
  proceedBrainstorm(runId: string, stage: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/proceed`,
      options,
    })
  }

  /**
   * Proceed past the clarity review
   * Settle the clarity phase with the last clarified report and advance the parked run. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/clarity/proceed` — operation `proceedPublicRunClarity`.
   */
  proceedClarity(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/proceed`,
      options,
    })
  }

  /**
   * Reject a parked step
   * Reject the gated proposal: the run stops entirely, recording a terminal `rejected` failure the board can retry. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/reject` — operation `rejectPublicRunStep`.
   */
  rejectStep(runId: string, approvalId: string, body: PublicRejectStep, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/approvals/${encodePathSegment(approvalId)}/reject`,
      body,
      options,
    })
  }

  /**
   * Respond to a brainstorm option
   * Pick or steer one of the options the brainstorm agent proposed, for the named stage (`requirements` or `architecture`). A task may hold one live session per stage at once. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}/reply` — operation `replyPublicRunBrainstormOption`.
   */
  replyToBrainstormOption(runId: string, stage: string, itemId: string, body: PublicReplyFinding, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/options/${encodePathSegment(itemId)}/reply`,
      body,
      options,
    })
  }

  /**
   * Answer a clarity (bug-triage) finding
   * Record an answer to one clarity-review finding — the bug-report twin of the requirements loop. Returns the run's updated decision list. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}/reply` — operation `replyPublicRunClarityFinding`.
   */
  replyToClarityFinding(runId: string, itemId: string, body: PublicReplyFinding, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/findings/${encodePathSegment(itemId)}/reply`,
      body,
      options,
    })
  }

  /**
   * Answer a review finding
   * Record an answer to one reviewer finding. Returns the run's updated decision list. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}/reply` — operation `replyPublicRunFinding`.
   */
  replyToFinding(runId: string, itemId: string, body: PublicReplyFinding, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/findings/${encodePathSegment(itemId)}/reply`,
      body,
      options,
    })
  }

  /**
   * Request a fix from a human-test gate
   * Submit findings against the tested environment and dispatch a fixer, which commits onto the PR branch before the environment is rebuilt. The findings ARE the fixer prompt, so they cannot be blank. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/human-test/request-fix` — operation `requestPublicRunHumanTestFix`.
   */
  requestHumanTestFix(runId: string, body: PublicRequestGateFix, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/human-test/request-fix`,
      body,
      options,
    })
  }

  /**
   * Request changes on a parked step
   * Send the gated step back to re-run with your guidance folded in. Unlike the in-app twin this takes freeform feedback only: anchored per-block comments address source line ranges of a rendered proposal, which a headless caller never rendered. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/request-changes` — operation `requestPublicRunStepChanges`.
   */
  requestStepChanges(runId: string, approvalId: string, body: PublicRequestStepChanges, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/approvals/${encodePathSegment(approvalId)}/request-changes`,
      body,
      options,
    })
  }

  /**
   * Request a fix from a visual-confirmation gate
   * Submit findings against the captured screenshots and dispatch a fixer. The findings ARE the fixer prompt, so they cannot be blank. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/visual-confirmation/request-fix` — operation `requestPublicRunVisualConfirmFix`.
   */
  requestVisualConfirmationFix(runId: string, body: PublicRequestGateFix, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/visual-confirmation/request-fix`,
      body,
      options,
    })
  }

  /**
   * Re-review the incorporated document
   * Run one more reviewer pass over the incorporated document. On convergence the parked run advances. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/requirements/re-review` — operation `reReviewPublicRunRequirements`.
   */
  reReview(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/re-review`,
      options,
    })
  }

  /**
   * Re-run a brainstorm pass
   * Run one more brainstorm pass against the converged direction. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/re-review` — operation `reReviewPublicRunBrainstorm`.
   */
  reReviewBrainstorm(runId: string, stage: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/re-review`,
      options,
    })
  }

  /**
   * Re-triage the clarified report
   * Run one more triage pass over the incorporated bug report. On convergence the parked run advances. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/clarity/re-review` — operation `reReviewPublicRunClarity`.
   */
  reReviewClarity(runId: string, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/re-review`,
      options,
    })
  }

  /**
   * Resolve a brainstorm at its iteration cap
   * Pick how a brainstorm that exhausted its pass budget proceeds: one more round, proceed with the last converged direction, or stop and reset the task. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/brainstorm/{stage}/resolve-exceeded` — operation `resolvePublicRunBrainstormExceeded`.
   */
  resolveBrainstormExceeded(runId: string, stage: string, body: PublicResolveExceeded, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/resolve-exceeded`,
      body,
      options,
    })
  }

  /**
   * Resolve a clarity review at its iteration cap
   * Pick how a clarity review that exhausted its pass budget proceeds: one more round, proceed with the last clarified report, or stop and reset the task. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/clarity/resolve-exceeded` — operation `resolvePublicRunClarityExceeded`.
   */
  resolveClarityExceeded(runId: string, body: PublicResolveExceeded, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/resolve-exceeded`,
      body,
      options,
    })
  }

  /**
   * Resolve a review at its iteration cap
   * Pick how a review that exhausted its reviewer-pass budget proceeds: one more round, proceed with the last incorporated document, or stop and reset the task. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/requirements/resolve-exceeded` — operation `resolvePublicRunRequirementsExceeded`.
   */
  resolveExceeded(runId: string, body: PublicResolveExceeded, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/resolve-exceeded`,
      body,
      options,
    })
  }

  /**
   * Resolve a run parked on the task's input check
   * Settle a run the pre-token input gate parked before its first agent step because the task states nothing an agent could act on. `recheck` re-evaluates the task as it now stands (edit it over `PATCH /api/v1/tasks/{taskId}` first: the fix is verified, not taken on trust) and releases the run only if the blocking findings are gone; a still-blocked verdict comes back as an ordinary 200 with refreshed findings. `proceed` waives the findings, which stay on the run as an `overridden` record. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/input-gate/resolve` — operation `resolvePublicRunInputGate`.
   */
  resolveInputGate(runId: string, body: PublicResolveInputGate, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/input-gate/resolve`,
      body,
      options,
    })
  }

  /**
   * Resolve a parked judge verdict
   * Settle a run parked on a judge verdict: proceed anyway, bounce the producing step for rework, or stop the run. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/judge/resolve` — operation `resolvePublicRunJudge`.
   */
  resolveJudge(runId: string, body: PublicResolveJudge, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/judge/resolve`,
      body,
      options,
    })
  }

  /**
   * Resolve a parked PR deep review
   * Record the curated finding selection and say what to do with it: `finish` completes the read-only review, `fix` hands the selected findings to a fixer that commits onto the reviewed PR branch, `post` publishes them as inline PR review comments. `fix` and `post` need at least one selected finding and act on the real pull request. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/pr-review/resolve` — operation `resolvePublicRunPrReview`.
   */
  resolvePrReview(runId: string, body: PublicResolvePrReview, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/pr-review/resolve`,
      body,
      options,
    })
  }

  /**
   * Resolve a companion gate at its rework cap
   * Pick how a quality companion that spent its automatic rework budget proceeds: one more round, proceed with the output as it stands, or stop and reset the task. A gate in this state reports `exceeded: true` and refuses the plain approve. Requires a `decide`-scope key.
   * `POST /api/v1/runs/{runId}/decisions/approvals/{approvalId}/resolve-exceeded` — operation `resolvePublicRunStepExceeded`.
   */
  resolveStepExceeded(runId: string, approvalId: string, body: PublicResolveExceeded, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'POST',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/approvals/${encodePathSegment(approvalId)}/resolve-exceeded`,
      body,
      options,
    })
  }

  /**
   * Dismiss or reopen a brainstorm option
   * Dismiss a proposed option, or reopen one dismissed by mistake. Only `open` options block incorporation. Requires a `decide`-scope key.
   * `PATCH /api/v1/runs/{runId}/decisions/brainstorm/{stage}/options/{itemId}` — operation `setPublicRunBrainstormOptionStatus`.
   */
  setBrainstormOptionStatus(runId: string, stage: string, itemId: string, body: PublicSetFindingStatus, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'PATCH',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/brainstorm/${encodePathSegment(stage)}/options/${encodePathSegment(itemId)}`,
      body,
      options,
    })
  }

  /**
   * Dismiss or reopen a clarity finding
   * Dismiss a clarity finding as not applicable, or reopen one dismissed by mistake. Only `open` findings block incorporation. Requires a `decide`-scope key.
   * `PATCH /api/v1/runs/{runId}/decisions/clarity/findings/{itemId}` — operation `setPublicRunClarityFindingStatus`.
   */
  setClarityFindingStatus(runId: string, itemId: string, body: PublicSetFindingStatus, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'PATCH',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/clarity/findings/${encodePathSegment(itemId)}`,
      body,
      options,
    })
  }

  /**
   * Dismiss or reopen a finding
   * Dismiss a finding as not applicable, or reopen one dismissed by mistake. Requires a `decide`-scope key.
   * `PATCH /api/v1/runs/{runId}/decisions/requirements/findings/{itemId}` — operation `setPublicRunFindingStatus`.
   */
  setFindingStatus(runId: string, itemId: string, body: PublicSetFindingStatus, options: RequestOptions = {}): Promise<PublicDecisionList> {
    return this.#transport.request<PublicDecisionList>({
      method: 'PATCH',
      path: `/api/v1/runs/${encodePathSegment(runId)}/decisions/requirements/findings/${encodePathSegment(itemId)}`,
      body,
      options,
    })
  }
}

/** A run's recorded telemetry: LLM calls, the context each agent was given, infra logs. */
export class DebugResource {
  readonly #transport: Transport

  constructor(transport: Transport) {
    this.#transport = transport
  }

  /**
   * Get one agent-context snapshot
   * The complete context one dispatch was PROVIDED: system and user prompts, the folded standards fragments, and the injected `.cat-context/*` files an agent reads through tools (which therefore appear in no proxy telemetry). Windowed by `bodyOffset`/`bodyChars`.
   * `GET /api/v1/debug/agent-context/{snapshotId}` — operation `getDebugAgentContext`.
   */
  getAgentContext(snapshotId: string, query: DebugGetAgentContextQuery = {}, options: RequestOptions = {}): Promise<DebugAgentContextSnapshot> {
    return this.#transport.request<DebugAgentContextSnapshot>({
      method: 'GET',
      path: `/api/v1/debug/agent-context/${encodePathSegment(snapshotId)}`,
      query,
      options,
    })
  }

  /**
   * Get one LLM call
   * One recorded model call with its budgeted prompt delta, response and reasoning. `bodyOffset`/`bodyChars` window the bodies, so an arbitrarily long transcript is readable in bounded pages.
   * `GET /api/v1/debug/llm-calls/{callId}` — operation `getDebugLlmCall`.
   */
  getLlmCall(callId: string, query: DebugGetLlmCallQuery = {}, options: RequestOptions = {}): Promise<DebugLlmCall> {
    return this.#transport.request<DebugLlmCall>({
      method: 'GET',
      path: `/api/v1/debug/llm-calls/${encodePathSegment(callId)}`,
      query,
      options,
    })
  }

  /**
   * Get a run's diagnostic map
   * One run’s diagnostic overview: its steps, which telemetry sinks this deployment retains (and how much each holds), the LLM cost/latency rollups, and the derived signals worth looking at first.
   * `GET /api/v1/debug/runs/{runId}` — operation `getDebugRun`.
   */
  getRun(runId: string, options: RequestOptions = {}): Promise<DebugRunOverview> {
    return this.#transport.request<DebugRunOverview>({
      method: 'GET',
      path: `/api/v1/debug/runs/${encodePathSegment(runId)}`,
      options,
    })
  }

  /**
   * List a run's agent-context dispatches
   * Every dispatch whose provided context was captured, with SIZES only (no bodies) so the list stays bounded. Read one in full through the snapshot endpoint.
   * `GET /api/v1/debug/runs/{runId}/agent-context` — operation `listDebugAgentContext`.
   */
  listAgentContext(runId: string, query: DebugListAgentContextQuery = {}, options: RequestOptions = {}): Promise<ListDebugAgentContextResponse> {
    return this.#transport.request<ListDebugAgentContextResponse>({
      method: 'GET',
      path: `/api/v1/debug/runs/${encodePathSegment(runId)}/agent-context`,
      query,
      options,
    })
  }

  /**
   * Every `snapshots` across every page of `listAgentContext()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listAgentContextAll(runId: string, query: DebugListAgentContextQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListDebugAgentContextResponse['snapshots'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listAgentContext(runId, { ...query, cursor }, options)
      for (const item of page.snapshots) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * List a run's LLM calls
   * The model calls a run made, keyset-paginated and filterable by agent kind, phase, outcome or a substring of the bodies. Bodies are returned only when `bodyChars` asks for them.
   * `GET /api/v1/debug/runs/{runId}/llm-calls` — operation `listDebugLlmCalls`.
   */
  listLlmCalls(runId: string, query: DebugListLlmCallsQuery = {}, options: RequestOptions = {}): Promise<ListDebugLlmCallsResponse> {
    return this.#transport.request<ListDebugLlmCallsResponse>({
      method: 'GET',
      path: `/api/v1/debug/runs/${encodePathSegment(runId)}/llm-calls`,
      query,
      options,
    })
  }

  /**
   * Every `calls` across every page of `listLlmCalls()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listLlmCallsAll(runId: string, query: DebugListLlmCallsQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListDebugLlmCallsResponse['calls'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listLlmCalls(runId, { ...query, cursor }, options)
      for (const item of page.calls) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * List a run's infrastructure log
   * The run’s provisioning event log — how its environment, runner pool and containers came up, or why they did not.
   * `GET /api/v1/debug/runs/{runId}/logs` — operation `listDebugLogs`.
   */
  listLogs(runId: string, query: DebugListLogsQuery = {}, options: RequestOptions = {}): Promise<ListDebugLogsResponse> {
    return this.#transport.request<ListDebugLogsResponse>({
      method: 'GET',
      path: `/api/v1/debug/runs/${encodePathSegment(runId)}/logs`,
      query,
      options,
    })
  }

  /**
   * Every `entries` across every page of `listLogs()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listLogsAll(runId: string, query: DebugListLogsQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListDebugLogsResponse['entries'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listLogs(runId, { ...query, cursor }, options)
      for (const item of page.entries) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * List the workspace's runs
   * The triage entry point: the workspace’s runs, newest first and keyset-paginated, with an optional status and `since` filter.
   * `GET /api/v1/debug/runs` — operation `listDebugRuns`.
   */
  listRuns(query: DebugListRunsQuery = {}, options: RequestOptions = {}): Promise<ListDebugRunsResponse> {
    return this.#transport.request<ListDebugRunsResponse>({
      method: 'GET',
      path: `/api/v1/debug/runs`,
      query,
      options,
    })
  }

  /**
   * Every `runs` across every page of `listRuns()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listRunsAll(query: DebugListRunsQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListDebugRunsResponse['runs'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listRuns({ ...query, cursor }, options)
      for (const item of page.runs) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }

  /**
   * List a run's web searches
   * The web searches the run’s agents actually performed, keyset-paginated. Retained only when the deployment records agent context.
   * `GET /api/v1/debug/runs/{runId}/search-queries` — operation `listDebugSearchQueries`.
   */
  listSearchQueries(runId: string, query: DebugListSearchQueriesQuery = {}, options: RequestOptions = {}): Promise<ListDebugSearchQueriesResponse> {
    return this.#transport.request<ListDebugSearchQueriesResponse>({
      method: 'GET',
      path: `/api/v1/debug/runs/${encodePathSegment(runId)}/search-queries`,
      query,
      options,
    })
  }

  /**
   * Every `queries` across every page of `listSearchQueries()`.
   * Follows `nextCursor` until the server reports no further page. The cursor is opaque
   * and carries a position, never authority — each page re-applies the key's full scope.
   */
  async *listSearchQueriesAll(runId: string, query: DebugListSearchQueriesQuery = {}, options: RequestOptions = {}): AsyncGenerator<ListDebugSearchQueriesResponse['queries'][number]> {
    let cursor: string | undefined = query.cursor
    for (;;) {
      const page = await this.listSearchQueries(runId, { ...query, cursor }, options)
      for (const item of page.queries) yield item
      if (!page.nextCursor) return
      if (page.nextCursor === cursor) throw repeatedCursorError()
      cursor = page.nextCursor
    }
  }
}

/**
 * The resource clients a `CatFactoryClient` exposes, one per tag of the published OpenAPI surface.
 *
 * Generated and INHERITED by the client rather than re-listed on it: a resource group added to the
 * SDK surface table would otherwise generate, compile, and simply not be reachable from the client
 * anyone actually constructs. (A declaration-merged interface would do the same job, but TypeScript
 * cannot see that such properties are initialised — so a real base class it is.)
 */
export abstract class CatFactoryResources {
  /** Headless jobs (a public, inline pipeline run against a brief): start, poll or stream one. */
  readonly jobs: JobsResource
  /** The workspace's board services — the frames tasks are created under. */
  readonly services: ServicesResource
  /** A board task's whole lifecycle: create, edit, start, stop, retry, watch, delete. */
  readonly tasks: TasksResource
  /** The pipelines a task can be started with, and whether each is headless-startable. */
  readonly pipelines: PipelinesResource
  /** The workspace's human-actionable inbox: list, act on, or dismiss a run tail. */
  readonly notifications: NotificationsResource
  /** The billing period's metered budget position and the per-model breakdown behind it. */
  readonly usage: UsageResource
  /** Every way a run stops for a person: approval gates, review and brainstorm loops, forks, judge verdicts, PR review findings and the human-verdict gates. */
  readonly decisions: DecisionsResource
  /** A run's recorded telemetry: LLM calls, the context each agent was given, infra logs. */
  readonly debug: DebugResource

  protected constructor(transport: Transport) {
    this.jobs = new JobsResource(transport)
    this.services = new ServicesResource(transport)
    this.tasks = new TasksResource(transport)
    this.pipelines = new PipelinesResource(transport)
    this.notifications = new NotificationsResource(transport)
    this.usage = new UsageResource(transport)
    this.decisions = new DecisionsResource(transport)
    this.debug = new DebugResource(transport)
  }
}
