// Pricing tables and spend metering/gating for @cat-factory.

export {
  SpendService,
  type SpendServiceDependencies,
  type RecordUsageInput,
  type ScopedSpendForecast,
  type BudgetTierScope,
} from './SpendService.js'
export {
  type ModelPrice,
  type ResolvedModelPrice,
  type InputTokenClassUsage,
  type SpendPricing,
  CACHE_READ_MULTIPLIER,
  CACHE_WRITE_MULTIPLIER,
  DEFAULT_MODEL_PRICES,
  DEFAULT_MONTHLY_LIMIT_EUR,
  DEFAULT_SPEND_PRICING,
  budgetCapsOverlay,
  effectiveTierLimit,
  priceFor,
  ratesFor,
  modelCostResolver,
  estimateCost,
  estimateClassedCost,
  withDynamicPrices,
  startOfMonthUtc,
  startOfNextMonthUtc,
} from './pricing.js'
export {
  type SpendAlertSignals,
  type SpendAlertState,
  type SpendForecast,
  type SpendForecastConfidence,
  type SpendForecastInput,
  BURN_RATE_WINDOW_MS,
  DEFAULT_SPEND_ALERT_THRESHOLDS,
  MIN_OBSERVED_SPAN_MS,
  forecastSpend,
  mergeSpendAlertStates,
  spendAlertEscalated,
  spendAlertFiring,
  spendAlertState,
} from './forecast.logic.js'
