// Pure ordering for the requirements-review window's findings list.
//
// A reviewer pass raises its findings in whatever order it produced them, and the human then
// works down the list answering, dismissing or handing findings to the Requirement Writer. A
// finding they have dealt with keeps its slot, so on a long review (and on every re-review, which
// re-raises what is still unresolved alongside what is new) the ones still waiting on a reaction
// end up scattered between settled ones. This floats what still needs the human to the top and
// sinks what is already handled, so "what is left for me?" is answered by looking at the top of
// the list instead of scrolling it end to end.
//
// Kept out of the SFC so the bucketing, the comparator and the pinning rule are unit-testable
// without mounting Nuxt.
import type { RequirementReviewItem, ReviewItemSeverity } from '~/types/requirements'

/**
 * How much of the human's attention a finding still wants.
 * - `action` — the ball is in THEIR court: an unanswered finding, or a Writer suggestion sitting
 *   there awaiting accept/reject.
 * - `waiting` — the ball is in the MACHINE's court: the Requirement Writer is still producing a
 *   suggestion for this finding, so there is nothing to react to yet.
 * - `settled` — answered, dismissed or resolved; nothing further is owed per-finding (the review
 *   as a whole still needs the incorporate/proceed decision, which lives in the action rail).
 */
export type FindingAttention = 'action' | 'waiting' | 'settled'

/**
 * WHO can answer a finding, which is the reviewer's own `autoAnswerable` judgement read as the two
 * groups it sorts findings into.
 *
 * - `judgement` — it takes a business / product / domain decision, or information the reviewer was
 *   not given. Only a person can settle it, and a run nobody is watching parks on it.
 * - `practice` — a confident answer follows from universal best practice, from the idiomatic
 *   approach of a stack the work already uses, or from the context already provided. The
 *   Requirement Writer pre-answers these, and an unattended run may adopt a sufficiently confident
 *   suggestion without waiting (see `reviewSettledForUnattended`).
 *
 * The two are the PRIMARY grouping in the window, ahead of how much attention a finding wants,
 * because they are answered by different people rather than at different times: the value of
 * seeing them apart is knowing which of them is yours.
 */
export type FindingClass = 'judgement' | 'practice'

/**
 * Which group a finding is in. ABSENT `autoAnswerable` reads as `judgement`, matching the contract's
 * own reading of an unclassified finding (a pass that predates the flag, or a garbled reply): the
 * safe direction is the one that asks a person.
 */
export function findingClass(item: Pick<RequirementReviewItem, 'autoAnswerable'>): FindingClass {
  return item.autoAnswerable === true ? 'practice' : 'judgement'
}

/** What the review's recommendation collection currently holds for one finding. */
export interface FindingRecommendationState {
  /** A requested suggestion is still being generated by the Writer. */
  pending: boolean
  /** A generated suggestion is waiting on the human's accept/reject. */
  ready: boolean
}

/** One finding in the rendered order, tagged with the buckets its position came from. */
export interface OrderedFinding {
  id: string
  attention: FindingAttention
  group: FindingClass
}

const ATTENTION_RANK: Record<FindingAttention, number> = { action: 0, waiting: 1, settled: 2 }
// `judgement` first: it is the group that always needs the person reading this, whatever state its
// findings are in, and the practice group is the one the platform may have already answered.
const CLASS_RANK: Record<FindingClass, number> = { judgement: 0, practice: 1 }
const SEVERITY_RANK: Record<ReviewItemSeverity, number> = { high: 0, medium: 1, low: 2 }

/**
 * Which bucket a finding belongs in. The recommendation state OUTRANKS the finding's own status,
 * because that is where the actionability actually moved: a finding parked in
 * `recommend_requested` is the human's problem again the moment a suggestion lands (accept or
 * reject), and is nobody's problem while the Writer is still thinking. A `recommend_requested`
 * finding with NEITHER a pending nor a ready suggestion has had its recommendation declined or
 * lost, so nothing more is coming and it is back on the human — the opposite of what its status
 * alone would suggest.
 */
export function findingAttention(
  item: Pick<RequirementReviewItem, 'status'>,
  recommendation: FindingRecommendationState,
): FindingAttention {
  if (recommendation.ready) return 'action'
  if (recommendation.pending) return 'waiting'
  if (item.status === 'open' || item.status === 'recommend_requested') return 'action'
  return 'settled'
}

/**
 * The findings in the order the window should render them: the two GROUPS first (the ones only a
 * person can decide, then the ones practice can answer), and within each of them unreacted-to
 * first, then whatever the Writer is still working on, then everything already handled. Severity
 * stays the next key (the order the window has always used within a bucket), and the reviewer's own
 * ordering breaks the remaining ties so the sort is total and stable.
 *
 * Group ahead of attention, which is a change of primary key rather than an extra tiebreak: a
 * settled judgement finding now sorts above an open practice one. That is the intended reading —
 * the groups are two lists with different audiences, and each is internally ordered by what is
 * left to do in it, rather than one list interleaving work the reader owns with work they do not.
 */
export function orderFindings(
  items: readonly RequirementReviewItem[],
  recommendationFor: (item: RequirementReviewItem) => FindingRecommendationState,
): OrderedFinding[] {
  return items
    .map((item, index) => ({
      id: item.id,
      attention: findingAttention(item, recommendationFor(item)),
      group: findingClass(item),
      severity: item.severity,
      index,
    }))
    .sort(
      (a, b) =>
        CLASS_RANK[a.group] - CLASS_RANK[b.group] ||
        ATTENTION_RANK[a.attention] - ATTENTION_RANK[b.attention] ||
        SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity] ||
        a.index - b.index,
    )
    .map(({ id, attention, group }) => ({ id, attention, group }))
}

/**
 * Which order to actually render: the PINNED one while it still covers exactly the same findings,
 * otherwise the freshly computed one.
 *
 * The window pins the order while the human is typing in a finding's box and re-pins once they
 * leave it, because an answer auto-saves on blur: re-sorting at that exact moment would slide the
 * card they just clicked into out from under the cursor. Pinning is only ever allowed to hold a
 * position STALE, never to hide a finding — a reviewer pass that adds or drops findings therefore
 * invalidates the pin outright rather than rendering a list missing the new ones.
 */
export function reconcileFindingOrder(
  desired: readonly OrderedFinding[],
  pinned: readonly OrderedFinding[] | null,
): readonly OrderedFinding[] {
  if (!pinned || pinned.length !== desired.length) return desired
  const ids = new Set(desired.map((entry) => entry.id))
  return pinned.every((entry) => ids.has(entry.id)) ? pinned : desired
}
