// Public surface of the framework-agnostic core.
// Each concern now lives in its own package; @cat-factory/core re-exports everything
// for backward compatibility — no consumer import paths need to change.

// Kernel: shared vocabulary, pure logic, port interfaces
export * from '@cat-factory/kernel'

// Tenancy base: workspaces and accounts
export {
  WorkspaceService,
  type WorkspaceServiceDependencies,
  AccountService,
  type AccountServiceDependencies,
  type AccountUser,
} from '@cat-factory/workspaces'

// Spend metering and pricing
export {
  SpendService,
  type SpendServiceDependencies,
  type RecordUsageInput,
  type ModelPrice,
  type SpendPricing,
  DEFAULT_MODEL_PRICES,
  DEFAULT_MONTHLY_LIMIT_EUR,
  DEFAULT_SPEND_PRICING,
  priceFor,
  estimateCost,
  startOfMonthUtc,
} from '@cat-factory/spend'

// Agent catalog, routing, prompts, and fragment library
export {
  AiAgentExecutor,
  type AiAgentExecutorDependencies,
  type AgentModelConfig,
  type AgentRouting,
  resolveAgentConfig,
  systemPromptFor,
  userPromptFor,
  type VersionedPrompt,
  type PromptId,
  PROMPT_VERSIONS,
  REVIEW_SYSTEM_PROMPT,
  promptVersion,
  promptVersionLabel,
  composeSystemPrompt,
  composeBlockSystemPrompt,
  type ComposableBlock,
  type StandardPhase,
  STANDARD_PHASES,
  STANDARD_PHASE_BY_KIND,
  phaseForKind,
  standardSystemPrompt,
  renderStandardUserPrompt,
  type AcceptanceAgentKind,
  ACCEPTANCE_AGENT_KINDS,
  acceptanceSystemPrompt,
  isAcceptanceKind,
  testApproachSection,
  MOCK_AGENT_KIND,
  isMockKind,
  mockSystemPrompt,
  type BusinessLogicAgentKind,
  BUSINESS_LOGIC_AGENT_KINDS,
  BUSINESS_DOCUMENTER_KIND,
  BUSINESS_REVIEWER_KIND,
  BUSINESS_LOGIC_DOCS_DIR,
  isBusinessLogicKind,
  businessLogicSystemPrompt,
  CI_RETRY_SANITY_CHECK,
  FragmentLibraryService,
  type FragmentLibraryServiceDependencies,
  FragmentSourceService,
  type FragmentSourceServiceDependencies,
  type ResolveFragmentInstallationId,
  DeterministicFragmentSelector,
  type ResolvedCatalogEntry,
  mergeCatalog,
  toSelectable,
  entryToFragment,
  selectDeterministic,
  fragmentSourceLogic,
} from '@cat-factory/agents'

// External-system integrations (GitHub, documents, tasks, environments, runners)
export {
  GitHubInstallationService,
  type GitHubInstallationServiceDependencies,
  GitHubService,
  type GitHubServiceDependencies,
  GitHubSyncService,
  type GitHubSyncServiceDependencies,
  WebhookService,
  type WebhookServiceDependencies,
  githubProjection,
  RepoProvisioningService,
  type RepoProvisioningServiceDependencies,
  type DelegationReason,
  type ProvisionResult,
  canCreateRepo,
  DocumentConnectionService,
  type DocumentConnectionServiceDependencies,
  DocumentImportService,
  type DocumentImportServiceDependencies,
  toSourceDocument,
  DocumentPlannerService,
  type DocumentPlannerServiceDependencies,
  DocumentLinkService,
  type DocumentLinkServiceDependencies,
  type SpawnResult,
  MapDocumentSourceRegistry,
  documentsLogic,
  confluenceLogic,
  notionLogic,
  CONFLUENCE_DESCRIPTOR,
  NOTION_DESCRIPTOR,
  TaskConnectionService,
  type TaskConnectionServiceDependencies,
  TaskImportService,
  type TaskImportServiceDependencies,
  toSourceTask,
  TaskLinkService,
  type TaskLinkServiceDependencies,
  MapTaskSourceRegistry,
  type TaskContextView,
  renderTaskContext,
  buildTaskExcerpt,
  tasksLogic,
  jiraLogic,
  JIRA_DESCRIPTOR,
  EnvironmentConnectionService,
  type EnvironmentConnectionServiceDependencies,
  type ResolvedConnection,
  referencedSecretKeys,
  EnvironmentProvisioningService,
  type EnvironmentProvisioningServiceDependencies,
  type ProvisionArgs,
  type ResolvedEnvironment,
  EnvironmentTeardownService,
  type EnvironmentTeardownServiceDependencies,
  environmentsLogic,
  RunnerPoolConnectionService,
  type RunnerPoolConnectionServiceDependencies,
  type ResolvedRunnerPool,
  runnersLogic,
} from '@cat-factory/integrations'

// Delivery-workflow engine + composition root
export {
  BoardService,
  type BoardServiceDependencies,
  boardLogic,
  PipelineService,
  type PipelineServiceDependencies,
  ExecutionService,
  type ExecutionServiceDependencies,
  type AdvanceOptions,
  type AdvanceResult,
  BootstrapService,
  type BootstrapServiceDependencies,
  type BootstrapPollResult,
  BoardScanService,
  type BoardScanServiceDependencies,
  boardScanLogic,
  RequirementReviewService,
  type RequirementReviewServiceDependencies,
  requirementsLogic,
  type Core,
  type CoreDependencies,
  type GitHubModule,
  type DocumentsModule,
  type TasksModule,
  type EnvironmentsModule,
  type RunnersModule,
  type BootstrapModule,
  type BoardScanModule,
  type RequirementsModule,
  type FragmentLibraryModule,
  createCore,
} from '@cat-factory/orchestration'
